Compute Graph Framework SDK Reference: dw::core::QueueFixed< Type, CapacityAtCompileTime_ > Class Template Reference
dw::core::QueueFixed< Type, CapacityAtCompileTime_ > Class Template Reference
Detailed Description
template<typename Type, size_t CapacityAtCompileTime_ = 0>
class dw::core::QueueFixed< Type, CapacityAtCompileTime_ >
Definition at line 108 of file ComputeGraphImpl.hpp.
Public Member Functions
void clear ()
bool contains (const Type &value) const
bool empty ()
bool pop ()
bool push (const Type &value)
QueueFixed ()
QueueFixed (size_t size_)
size_t size ()
const Type & top ()
Constructor & Destructor Documentation
QueueFixed() [1/2]
template<typename Type , size_t CapacityAtCompileTime_ = 0> dw::core::QueueFixed< Type, CapacityAtCompileTime_ >::QueueFixed () inline
Definition at line 111 of file ComputeGraphImpl.hpp.
QueueFixed() [2/2]
template<typename Type , size_t CapacityAtCompileTime_ = 0> dw::core::QueueFixed< Type, CapacityAtCompileTime_ >::QueueFixed (size_t size_) inline explicit
Definition at line 116 of file ComputeGraphImpl.hpp.
Member Function Documentation
clear()
template<typename Type , size_t CapacityAtCompileTime_ = 0> void dw::core::QueueFixed< Type, CapacityAtCompileTime_ >::clear () inline
Definition at line 155 of file ComputeGraphImpl.hpp.
contains()
template<typename Type , size_t CapacityAtCompileTime_ = 0> bool dw::core::QueueFixed< Type, CapacityAtCompileTime_ >::contains (const Type & value) const inline
Definition at line 161 of file ComputeGraphImpl.hpp.
empty()
template<typename Type , size_t CapacityAtCompileTime_ = 0> bool dw::core::QueueFixed< Type, CapacityAtCompileTime_ >::empty () inline
Definition at line 126 of file ComputeGraphImpl.hpp.
References dw::core::QueueFixed< Type, CapacityAtCompileTime_ >::size().
Referenced by dw::core::QueueFixed< Type, CapacityAtCompileTime_ >::pop(), and dw::core::QueueFixed< Type, CapacityAtCompileTime_ >::top().
pop()
template<typename Type , size_t CapacityAtCompileTime_ = 0> bool dw::core::QueueFixed< Type, CapacityAtCompileTime_ >::pop () inline
Definition at line 131 of file ComputeGraphImpl.hpp.
References dw::core::QueueFixed< Type, CapacityAtCompileTime_ >::empty().
push()
template<typename Type , size_t CapacityAtCompileTime_ = 0> bool dw::core::QueueFixed< Type, CapacityAtCompileTime_ >::push (const Type & value) inline
Definition at line 121 of file ComputeGraphImpl.hpp.
size()
template<typename Type , size_t CapacityAtCompileTime_ = 0> size_t dw::core::QueueFixed< Type, CapacityAtCompileTime_ >::size () inline
Definition at line 150 of file ComputeGraphImpl.hpp.
Referenced by dw::core::QueueFixed< Type, CapacityAtCompileTime_ >::empty().
top()
template<typename Type , size_t CapacityAtCompileTime_ = 0> const Type & dw::core::QueueFixed< Type, CapacityAtCompileTime_ >::top () inline
Definition at line 141 of file ComputeGraphImpl.hpp.
References dw::core::QueueFixed< Type, CapacityAtCompileTime_ >::empty().
The documentation for this class was generated from the following file:
src/dwcgf/computegraph/impl/ComputeGraphImpl.hpp