Compute Graph Framework SDK Reference: dw::framework::PortOutput< T > Class Template Reference
dw::framework::PortOutput< T > Class Template Reference
Detailed Description
template<typename T>
class dw::framework::PortOutput< T >
PortOutput mimics an Output Block. It wrapps over a Producer Channel. Provides services like
binding(allocating channel resources, out of current scope),
getting next free element
sending data
Definition at line 78 of file Port.hpp.
Public Types
using ApiDataTypeT = T
using BaseSyncHelper = SyncPortHelperOutput< T >
using SpecimenT = typename parameter_traits< T >::SpecimenT
Public Member Functions
dwStatus bindChannel (ChannelObject *channel) override
dwStatus bindChannelWithReference (ChannelObject *channel, GenericDataReference &ref)
T * getFreeElement ()
ChannelObject::SyncSignaler & getSyncSignaler ()
ChannelObject::SyncWaiter & getSyncWaiter ()
void getWaitFences (T *frame, dw::core::span< NvSciSyncFence > fences)
bool isBound () final
PortOutput (SpecimenT &&ref)
PortOutput (SpecimenT const &ref)
PortOutput (SpecimenT const &ref, OnSetSyncAttrs signalerAttrs, OnSetSyncAttrs waiterAttrs={})
virtual dwStatus send (T *frame)
void setOnDataReady (void *opaque, ChannelObject::PacketPool::OnDataReady onDataReady)
void setSignalFences (T *frame, dw::core::span< NvSciSyncFence > fences)
dwStatus wait (dwTime_t timeout)
Public Member Functions inherited from dw::framework::SyncPortHelperOutput< T >
SyncPortHelperOutput ()
Public Member Functions inherited from dw::framework::SyncPortHelper
bool isDataSynced ()
virtual void parseDataSynced (const ChannelParams &params)
void setSyncCount (uint32_t index)
dwStatus setSyncRetriever (const CycleCountFetcher &func)
SyncPortHelper ()
Public Member Functions inherited from dw::framework::Port
virtual dwStatus bindChannel (ChannelObject *channel)=0
virtual dwStatus initialize ()
virtual bool isBound ()=0
Public Member Functions inherited from dw::framework::PortBase
virtual ~PortBase ()=default
Static Public Attributes
static constexpr PortDirection DIRECTION = PortDirection::OUTPUT
static constexpr char LOG_TAG [] = "PortOutput"
Additional Inherited Members
Protected Member Functions inherited from dw::framework::SyncPortHelperOutput< T >
T * extractInternalPacket (GenericData genericData)
SyncedPacketPayload * getSyncPacket (T *frame)
void parseDataSynced (const ChannelParams &params) override
Protected Member Functions inherited from dw::framework::SyncPortHelper
ChannelPacketTypeID getNewPacketID (ChannelPacketTypeID packetTypeID)
void stampSyncCount (uint32_t &syncCountOut) const
Protected Attributes inherited from dw::framework::SyncPortHelper
uint32_t m_dataOffset
bool m_dataSynced
uint32_t m_syncCount
CycleCountFetcher m_syncCountRetriever
Member Typedef Documentation
ApiDataTypeT
template<typename T > using dw::framework::PortOutput< T >::ApiDataTypeT = T
Definition at line 82 of file Port.hpp.
BaseSyncHelper
template<typename T > using dw::framework::PortOutput< T >::BaseSyncHelper = SyncPortHelperOutput<T>
Definition at line 84 of file Port.hpp.
SpecimenT
template<typename T > using dw::framework::PortOutput< T >::SpecimenT = typename parameter_traits<T>::SpecimenT
Definition at line 83 of file Port.hpp.
Constructor & Destructor Documentation
PortOutput() [1/3]
template<typename T > dw::framework::PortOutput< T >::PortOutput (SpecimenT const & ref) inline explicit
Definition at line 97 of file Port.hpp.
PortOutput() [2/3]
template<typename T > dw::framework::PortOutput< T >::PortOutput (SpecimenT && ref) inline explicit
Definition at line 101 of file Port.hpp.
PortOutput() [3/3]
template<typename T > dw::framework::PortOutput< T >::PortOutput (SpecimenT const & ref, OnSetSyncAttrs signalerAttrs, OnSetSyncAttrs waiterAttrs = {}) inline explicit
Definition at line 106 of file Port.hpp.
Member Function Documentation
bindChannel()
template<typename T > dwStatus dw::framework::PortOutput< T >::bindChannel (ChannelObject * channel) inline override virtual
Implements dw::framework::Port.
Definition at line 116 of file Port.hpp.
References dw::framework::PortOutput< T >::bindChannelWithReference().
bindChannelWithReference()
template<typename T > dwStatus dw::framework::PortOutput< T >::bindChannelWithReference (ChannelObject * channel, GenericDataReference & ref) inline
Definition at line 122 of file Port.hpp.
References FRWK_LOGE, dw::framework::SyncPortHelper::getNewPacketID(), dw::framework::ChannelObject::getParams(), dw::framework::ChannelObject::getProducer(), dw::framework::Exception::guard(), dw::framework::PortOutput< T >::isBound(), dw::framework::SyncPortHelper::isDataSynced(), dw::framework::GenericDataReference::packetTypeID, dw::framework::SyncPortHelperOutput< T >::parseDataSynced(), dw::framework::GenericDataReference::setSignalerAttributes, and dw::framework::GenericDataReference::setWaiterAttributes.
Referenced by dw::framework::PortOutput< T >::bindChannel().
getFreeElement()
template<typename T > T * dw::framework::PortOutput< T >::getFreeElement () inline
Definition at line 181 of file Port.hpp.
References dw::framework::SyncPortHelperOutput< T >::extractInternalPacket(), dw::framework::ChannelObject::Producer::get(), dw::framework::SyncPortHelper::isDataSynced(), and dw::framework::status.
getSyncSignaler()
template<typename T > ChannelObject::SyncSignaler & dw::framework::PortOutput< T >::getSyncSignaler () inline
Definition at line 219 of file Port.hpp.
References dw::framework::ChannelObject::PacketPool::getSyncSignaler().
getSyncWaiter()
template<typename T > ChannelObject::SyncWaiter & dw::framework::PortOutput< T >::getSyncWaiter () inline
Definition at line 240 of file Port.hpp.
References dw::framework::ChannelObject::PacketPool::getSyncWaiter().
getWaitFences()
template<typename T > void dw::framework::PortOutput< T >::getWaitFences (T * frame, dw::core::span< NvSciSyncFence > fences) inline
Definition at line 249 of file Port.hpp.
References dw::framework::SyncPortHelperOutput< T >::getSyncPacket(), dw::framework::ChannelObject::PacketPool::getSyncWaiter(), dw::framework::ChannelObject::SyncWaiter::getWaitFences(), and dw::framework::SyncPortHelper::isDataSynced().
isBound()
template<typename T > bool dw::framework::PortOutput< T >::isBound () inline final virtual
Implements dw::framework::Port.
Definition at line 164 of file Port.hpp.
Referenced by dw::framework::PortOutput< T >::bindChannelWithReference(), dw::framework::PortOutput< T >::setOnDataReady(), and dw::framework::PortOutput< T >::wait().
send()
template<typename T > virtual dwStatus dw::framework::PortOutput< T >::send (T * frame) inline virtual
Definition at line 204 of file Port.hpp.
References dw::framework::SyncPortHelperOutput< T >::getSyncPacket(), dw::framework::SyncPortHelper::isDataSynced(), and dw::framework::ChannelObject::Producer::send().
setOnDataReady()
template<typename T > void dw::framework::PortOutput< T >::setOnDataReady (void * opaque, ChannelObject::PacketPool::OnDataReady onDataReady) inline
Definition at line 155 of file Port.hpp.
References dw::framework::PortOutput< T >::isBound(), and dw::framework::ChannelObject::PacketPool::setOnDataReady().
setSignalFences()
template<typename T > void dw::framework::PortOutput< T >::setSignalFences (T * frame, dw::core::span< NvSciSyncFence > fences) inline
Definition at line 228 of file Port.hpp.
References dw::framework::SyncPortHelperOutput< T >::getSyncPacket(), dw::framework::ChannelObject::PacketPool::getSyncSignaler(), dw::framework::SyncPortHelper::isDataSynced(), and dw::framework::ChannelObject::SyncSignaler::setSignalFences().
wait()
template<typename T > dwStatus dw::framework::PortOutput< T >::wait (dwTime_t timeout) inline
Definition at line 169 of file Port.hpp.
References dw::framework::PortOutput< T >::isBound(), and dw::framework::ChannelObject::PacketPool::wait().
Member Data Documentation
DIRECTION
template<typename T > constexpr PortDirection dw::framework::PortOutput< T >::DIRECTION = PortDirection::OUTPUT static constexpr
Definition at line 81 of file Port.hpp.
LOG_TAG
template<typename T > constexpr char dw::framework::PortOutput< T >::LOG_TAG = "PortOutput" static constexpr
Definition at line 88 of file Port.hpp.
The documentation for this class was generated from the following file:
src/dwcgf/port/Port.hpp