Compute Graph Framework SDK Reference: dw::framework::dwSelfCalibrationNode Class Reference
dw::framework::dwSelfCalibrationNode Class Reference
DW Core Nodes
Detailed Description
Definition at line 108 of file dwSelfCalibrationNode.hpp.
Public Member Functions
dwSelfCalibrationNode (const dwSelfCalibrationNodeParam &param, const dwContextHandle_t ctx)
Public Member Functions inherited from dw::framework::ExceptionSafeProcessNode
ExceptionSafeProcessNode (std::unique_ptr< Node > impl)
dwStatus getErrorSignal (dwGraphErrorSignal *&errorSignal) override
dwStatus getHealthSignal (dwGraphHealthSignal *&healthSignal, bool updateFromModule=false) override
dwStatus getName (const char **name) override
size_t getPassCount () const noexcept override
dwStatus getPasses (VectorFixed< Pass * > &passList) override
dwStatus getPasses (VectorFixed< Pass * > &passList, dwProcessorType processorType, dwProcessType processType) override
dwStatus reportCurrentErrorSignal (dwGraphErrorSignal &signal) override
dwStatus reportCurrentHealthSignal (dwGraphHealthSignal &signal) override
dwStatus reset () override
void resetPorts () override
dwStatus run () override
dwStatus runPass (size_t passIndex) override
dwStatus runPassByID (uint8_t passID) override
dwStatus setInputChannel (ChannelObject *channel, uint8_t portID) override
dwStatus setInputChannel (ChannelObject *channel, uint8_t portID, dwSerializationType dataType) override
dwStatus setIterationCount (uint32_t iterationCount) override final
dwStatus setName (const char *name) override
dwStatus setOutputChannel (ChannelObject *channel, uint8_t portID) override
dwStatus setState (const char *state) override
dwStatus validate () override
~ExceptionSafeProcessNode () override=default
Public Member Functions inherited from dw::framework::Node
virtual dwStatus getErrorSignal (dwGraphErrorSignal *&errorSignal)=0
Get the pointer to the error signal for this node.
virtual dwStatus getHealthSignal (dwGraphHealthSignal *&healthSignals, bool updateFromModule=false)=0
Get the pointer to the health signal for this node.
virtual dwStatus getName (const char **name)=0
Get the name of the node.
virtual size_t getPassCount () const noexcept=0
Get number of passes in the node.
virtual dwStatus getPasses (VectorFixed< Pass * > &passList)=0
Get all the passes in the node.
virtual dwStatus getPasses (VectorFixed< Pass * > &passList, dwProcessorType processorType, dwProcessType processType)=0
Get node passes filtered by processor type and process type.
virtual dwStatus reportCurrentErrorSignal (dwGraphErrorSignal &signal)=0
A function that allows user override to update error signal It is automatically called by dwFramework when getErrorSignal is called and when pass returns non-success return code.
virtual dwStatus reportCurrentHealthSignal (dwGraphHealthSignal &signal)=0
A function that allows user override to update health signal It is automatically called by dwFramework during teardown and when pass returns non-success return code.
virtual dwStatus reset ()=0
Resets the state of the node.
virtual void resetPorts ()=0
Resets all the ports in the node.
virtual dwStatus run ()=0
Runs all the passes in the node.
virtual dwStatus runPass (size_t passIndex)=0
Run one pass by index as defined by the pass descriptors.
virtual dwStatus runPassByID (uint8_t passID)=0
Run one pass by ID as defined by the PassList enum class.
virtual dwStatus setInputChannel (ChannelObject *channel, uint8_t portID)=0
Sets an input channel for this node with an accompanying port.
virtual dwStatus setInputChannel (ChannelObject *channel, uint8_t portID, dwSerializationType dataType)=0
Sets an input channel for this node with an accompanying port.
virtual dwStatus setIterationCount (uint32_t iterationCount)=0
Sets the node's iteration count.
virtual dwStatus setName (const char *name)=0
Set the name of the node.
virtual dwStatus setOutputChannel (ChannelObject *channel, uint8_t portID)=0
Sets an output channel for this node with an accompanying port.
virtual dwStatus setState (const char *state)=0
Set the current state in node. Node implementation of this API need to be thread-safe.
virtual dwStatus validate ()=0
Checks that all mandatory ports are bound. The implementation should validate that all the ports are bound to the appropriate channels (any required ports, that is). For example, a camera node may have processed output and raw output ports, but only one is required to be bound.
virtual ~Node ()=default
Static Public Member Functions
static std::unique_ptr< dwSelfCalibrationNode > create (ParameterProvider &provider)
static constexpr auto describeInputPorts ()
static constexpr auto describeOutputPorts ()
static constexpr auto describeParameters ()
static constexpr auto describePasses ()
Static Public Attributes
static constexpr char LOG_TAG [] = "dwSelfCalibrationNode"
Static Public Attributes inherited from dw::framework::Node
static constexpr size_t MAX_NAME_LEN = 128
static constexpr uint32_t MAX_PASS_COUNT = 256
static constexpr uint32_t MAX_PORT_COUNT = 256
static constexpr uint8_t PASS_SETUP = std::numeric_limits<uint8_t>::max() - 1
static constexpr uint8_t PASS_TEARDOWN = std::numeric_limits<uint8_t>::max()
Additional Inherited Members
Public Types inherited from dw::framework::Node
using Name_t = FixedString< MAX_NAME_LEN >
Protected Attributes inherited from dw::framework::ExceptionSafeProcessNode
std::unique_ptr< Node > m_impl
Constructor & Destructor Documentation
dwSelfCalibrationNode()
dw::framework::dwSelfCalibrationNode::dwSelfCalibrationNode (const dwSelfCalibrationNodeParam & param, const dwContextHandle_t ctx)
Member Function Documentation
create()
static std::unique_ptr< dwSelfCalibrationNode > dw::framework::dwSelfCalibrationNode::create (ParameterProvider & provider) static
describeInputPorts()
static constexpr auto dw::framework::dwSelfCalibrationNode::describeInputPorts () inline static constexpr
Definition at line 113 of file dwSelfCalibrationNode.hpp.
References dw::framework::describePortCollection(), DW_DESCRIBE_PORT, DW_DESCRIBE_PORT_ARRAY, dw::framework::OPTIONAL, dw::framework::SELF_CALIBRATION_NODE_MAX_CAMERAS, dw::framework::SELF_CALIBRATION_NODE_MAX_LIDARS, and dw::framework::SELF_CALIBRATION_NODE_MAX_RADARS.
describeOutputPorts()
static constexpr auto dw::framework::dwSelfCalibrationNode::describeOutputPorts () inline static constexpr
Definition at line 126 of file dwSelfCalibrationNode.hpp.
References dw::framework::describePortCollection(), DW_DESCRIBE_PORT, DW_DESCRIBE_PORT_ARRAY, dw::framework::REQUIRED, dw::framework::SELF_CALIBRATION_NODE_MAX_CAMERAS, dw::framework::SELF_CALIBRATION_NODE_MAX_LIDARS, and dw::framework::SELF_CALIBRATION_NODE_MAX_RADARS.
describeParameters()
static constexpr auto dw::framework::dwSelfCalibrationNode::describeParameters () inline static constexpr
Definition at line 157 of file dwSelfCalibrationNode.hpp.
References dw::framework::dwSelfCalibrationNodeParam::calibrateOdometryPropertyRadar, dw::framework::dwSelfCalibrationNodeParam::calibrateVehicle, dw::framework::dwSelfCalibrationNodeParam::channelFifoSize, dw::framework::describeConstructorArgument(), DW_DESCRIBE_ABSTRACT_ARRAY_PARAMETER, DW_DESCRIBE_PARAMETER, DW_DESCRIBE_UNNAMED_PARAMETER, dw::framework::dwSelfCalibrationNodeParam::enforceDependencies, dw::framework::dwSelfCalibrationNodeParam::rigHandle, dw::framework::SELF_CALIBRATION_NODE_MAX_CAMERAS, dw::framework::SELF_CALIBRATION_NODE_MAX_LIDARS, and dw::framework::SELF_CALIBRATION_NODE_MAX_RADARS.
describePasses()
static constexpr auto dw::framework::dwSelfCalibrationNode::describePasses () inline static constexpr
Definition at line 139 of file dwSelfCalibrationNode.hpp.
References dw::framework::describePass(), and dw::framework::describePassCollection().
Member Data Documentation
LOG_TAG
constexpr char dw::framework::dwSelfCalibrationNode::LOG_TAG[] = "dwSelfCalibrationNode" static constexpr
Definition at line 111 of file dwSelfCalibrationNode.hpp.
The documentation for this class was generated from the following file:
src/dwframework/dwnodes/dwselfcalibrationnode/dwSelfCalibrationNode.hpp