Compute Graph Framework SDK Reference: dw::framework::SyncPortHelperOutput< T > Class Template Reference
dw::framework::SyncPortHelperOutput< T > Class Template Reference
Detailed Description
template<typename T>
class dw::framework::SyncPortHelperOutput< T >
Definition at line 75 of file SyncPortHelper.hpp.
Public Member Functions
SyncPortHelperOutput ()
Public Member Functions inherited from dw::framework::SyncPortHelper
bool isDataSynced ()
virtual void parseDataSynced (const ChannelParams &params)
void setSyncCount (uint32_t index)
dwStatus setSyncRetriever (const CycleCountFetcher &func)
SyncPortHelper ()
Protected Member Functions
T * extractInternalPacket (GenericData genericData)
SyncedPacketPayload * getSyncPacket (T *frame)
void parseDataSynced (const ChannelParams &params) override
Protected Member Functions inherited from dw::framework::SyncPortHelper
ChannelPacketTypeID getNewPacketID (ChannelPacketTypeID packetTypeID)
void stampSyncCount (uint32_t &syncCountOut) const
Additional Inherited Members
Protected Attributes inherited from dw::framework::SyncPortHelper
uint32_t m_dataOffset
bool m_dataSynced
uint32_t m_syncCount
CycleCountFetcher m_syncCountRetriever
Constructor & Destructor Documentation
SyncPortHelperOutput()
template<typename T > dw::framework::SyncPortHelperOutput< T >::SyncPortHelperOutput () inline
Definition at line 78 of file SyncPortHelper.hpp.
Member Function Documentation
extractInternalPacket()
template<typename T > T * dw::framework::SyncPortHelperOutput< T >::extractInternalPacket (GenericData genericData) inline protected
Definition at line 84 of file SyncPortHelper.hpp.
Referenced by dw::framework::PortOutput< T >::getFreeElement().
getSyncPacket()
template<typename T > SyncedPacketPayload * dw::framework::SyncPortHelperOutput< T >::getSyncPacket (T * frame) inline protected
Definition at line 103 of file SyncPortHelper.hpp.
References dw::framework::SyncPortHelper::stampSyncCount(), and dw::framework::SyncedPacketPayload::syncCount.
Referenced by dw::framework::PortOutput< T >::getWaitFences(), dw::framework::PortOutput< T >::send(), and dw::framework::PortOutput< T >::setSignalFences().
parseDataSynced()
template<typename T > void dw::framework::SyncPortHelperOutput< T >::parseDataSynced (const ChannelParams & params) inline override protected virtual
Reimplemented from dw::framework::SyncPortHelper.
Definition at line 116 of file SyncPortHelper.hpp.
References dw::framework::ChannelParams::getPoolCapacity(), dw::framework::SyncPortHelper::isDataSynced(), and dw::framework::SyncPortHelper::parseDataSynced().
Referenced by dw::framework::PortOutput< T >::bindChannelWithReference().
The documentation for this class was generated from the following file:
src/dwcgf/port/SyncPortHelper.hpp