Compute Graph Framework SDK Reference: dw::framework::ChannelSocketPacketBase Class Reference
dw::framework::ChannelSocketPacketBase Class Reference
Detailed Description
Definition at line 42 of file ChannelPacketImpl.hpp.
Public Member Functions
void deserialize (size_t) override
uint8_t * getBuffer () override
size_t getBufferSize () override
size_t serialize () override
virtual void serializeImpl ()
virtual void deserialize (size_t)=0
virtual uint8_t * getBuffer ()=0
virtual size_t getBufferSize ()=0
virtual size_t serialize ()=0
Protected Member Functions
ChannelSocketPacketBase ()=default
ChannelSocketPacketBase (size_t bufferSize)
void initBuffer (size_t bufferSize)
Protected Attributes
std::unique_ptr< uint8_t[]> m_buffer
size_t m_bufferSize = 0
Constructor & Destructor Documentation
ChannelSocketPacketBase() [1/2]
dw::framework::ChannelSocketPacketBase::ChannelSocketPacketBase () protected default
ChannelSocketPacketBase() [2/2]
dw::framework::ChannelSocketPacketBase::ChannelSocketPacketBase (size_t bufferSize) inline protected
Definition at line 76 of file ChannelPacketImpl.hpp.
References initBuffer().
Member Function Documentation
deserialize()
void dw::framework::ChannelSocketPacketBase::deserialize (size_t) inline override virtual
Implements dw::framework::IChannelPacket::SocketCallbacks.
Reimplemented in dw::framework::ChannelPacket< dwImageHandle_t >, dw::framework::ChannelPacket< dwLatency >, dw::framework::ChannelPacket< dwSensorNodeRawData >, dw::framework::ChannelPacket< dwRadarScan >, dw::framework::ChannelPacket< dwLidarDecodedPacket >, dw::framework::ChannelPacket< dwEgomotionStateHandle_t >, dw::framework::ChannelPacket< dwPointCloud >, dw::framework::ChannelPacket< dwLidarPacketsArray >, dw::framework::ChannelPacket< dwTraceNodeData >, dw::framework::ChannelPacket< dwCodecPacket >, dw::framework::ChannelPacket< SensorServiceNodeRawData >, dw::framework::ChannelPacket< dwPyramidImage >, dw::framework::ChannelPacket< dwFeatureNccScores >, dw::framework::ChannelPacket< dwFeatureArray >, and dw::framework::ChannelPacket< dwFeatureHistoryArray >.
Definition at line 68 of file ChannelPacketImpl.hpp.
getBuffer()
uint8_t * dw::framework::ChannelSocketPacketBase::getBuffer () inline override virtual
Implements dw::framework::IChannelPacket::SocketCallbacks.
Definition at line 45 of file ChannelPacketImpl.hpp.
References m_buffer.
getBufferSize()
size_t dw::framework::ChannelSocketPacketBase::getBufferSize () inline override virtual
Implements dw::framework::IChannelPacket::SocketCallbacks.
Definition at line 50 of file ChannelPacketImpl.hpp.
References m_bufferSize.
initBuffer()
void dw::framework::ChannelSocketPacketBase::initBuffer (size_t bufferSize) inline protected
Definition at line 81 of file ChannelPacketImpl.hpp.
References m_buffer, and m_bufferSize.
Referenced by ChannelSocketPacketBase().
serialize()
size_t dw::framework::ChannelSocketPacketBase::serialize () inline override virtual
Implements dw::framework::IChannelPacket::SocketCallbacks.
Reimplemented in dw::framework::ChannelPacket< dwRadarScan >.
Definition at line 55 of file ChannelPacketImpl.hpp.
References m_bufferSize, and serializeImpl().
serializeImpl()
virtual void dw::framework::ChannelSocketPacketBase::serializeImpl () inline virtual
Reimplemented in dw::framework::ChannelPacket< dwImageHandle_t >, dw::framework::ChannelPacket< dwLatency >, dw::framework::ChannelPacket< dwSensorNodeRawData >, dw::framework::ChannelPacket< dwLidarDecodedPacket >, dw::framework::ChannelPacket< dwEgomotionStateHandle_t >, dw::framework::ChannelPacket< dwPointCloud >, dw::framework::ChannelPacket< dwLidarPacketsArray >, dw::framework::ChannelPacket< dwTraceNodeData >, dw::framework::ChannelPacket< dwCodecPacket >, dw::framework::ChannelPacket< SensorServiceNodeRawData >, dw::framework::ChannelPacket< dwPyramidImage >, dw::framework::ChannelPacket< dwFeatureNccScores >, dw::framework::ChannelPacket< dwFeatureArray >, and dw::framework::ChannelPacket< dwFeatureHistoryArray >.
Definition at line 62 of file ChannelPacketImpl.hpp.
Referenced by serialize().
Member Data Documentation
m_buffer
std::unique_ptr<uint8_t[]> dw::framework::ChannelSocketPacketBase::m_buffer protected
Definition at line 98 of file ChannelPacketImpl.hpp.
Referenced by getBuffer(), and initBuffer().
m_bufferSize
size_t dw::framework::ChannelSocketPacketBase::m_bufferSize = 0 protected
Definition at line 97 of file ChannelPacketImpl.hpp.
Referenced by getBufferSize(), initBuffer(), and serialize().
The documentation for this class was generated from the following file:
src/dwcgf/channel/ChannelPacketImpl.hpp