Compute Graph Framework SDK Reference: dw::framework::SyncPortHelper Struct Reference
dw::framework::SyncPortHelper Struct Reference
Detailed Description
Definition at line 47 of file SyncPortHelper.hpp.
Public Member Functions
bool isDataSynced ()
virtual void parseDataSynced (const ChannelParams &params)
void setSyncCount (uint32_t index)
dwStatus setSyncRetriever (const CycleCountFetcher &func)
SyncPortHelper ()
Protected Member Functions
ChannelPacketTypeID getNewPacketID (ChannelPacketTypeID packetTypeID)
void stampSyncCount (uint32_t &syncCountOut) const
Protected Attributes
uint32_t m_dataOffset
bool m_dataSynced
uint32_t m_syncCount
CycleCountFetcher m_syncCountRetriever
Constructor & Destructor Documentation
SyncPortHelper()
dw::framework::SyncPortHelper::SyncPortHelper () inline
Definition at line 50 of file SyncPortHelper.hpp.
Member Function Documentation
getNewPacketID()
ChannelPacketTypeID dw::framework::SyncPortHelper::getNewPacketID (ChannelPacketTypeID packetTypeID) protected
Referenced by dw::framework::PortInput< T >::bindChannel(), and dw::framework::PortOutput< T >::bindChannelWithReference().
isDataSynced()
bool dw::framework::SyncPortHelper::isDataSynced ()
Referenced by dw::framework::PortInput< T >::bindChannel(), dw::framework::PortOutput< T >::bindChannelWithReference(), dw::framework::PortOutput< T >::getFreeElement(), dw::framework::PortOutput< T >::getWaitFences(), dw::framework::PortInput< T >::getWaitFences(), dw::framework::SyncPortHelperOutput< T >::parseDataSynced(), dw::framework::PortInput< T >::recv(), dw::framework::PortOutput< T >::send(), dw::framework::PortOutput< T >::setSignalFences(), dw::framework::PortInput< T >::setSignalFences(), and dw::framework::PortInput< T >::wait().
parseDataSynced()
virtual void dw::framework::SyncPortHelper::parseDataSynced (const ChannelParams & params) virtual
Reimplemented in dw::framework::SyncPortHelperOutput< T >.
Referenced by dw::framework::PortInput< T >::bindChannel(), and dw::framework::SyncPortHelperOutput< T >::parseDataSynced().
setSyncCount()
void dw::framework::SyncPortHelper::setSyncCount (uint32_t index)
setSyncRetriever()
dwStatus dw::framework::SyncPortHelper::setSyncRetriever (const CycleCountFetcher & func)
stampSyncCount()
void dw::framework::SyncPortHelper::stampSyncCount (uint32_t & syncCountOut) const protected
Referenced by dw::framework::SyncPortHelperOutput< T >::getSyncPacket().
Member Data Documentation
m_dataOffset
uint32_t dw::framework::SyncPortHelper::m_dataOffset protected
Definition at line 68 of file SyncPortHelper.hpp.
m_dataSynced
bool dw::framework::SyncPortHelper::m_dataSynced protected
Definition at line 66 of file SyncPortHelper.hpp.
m_syncCount
uint32_t dw::framework::SyncPortHelper::m_syncCount protected
Definition at line 67 of file SyncPortHelper.hpp.
m_syncCountRetriever
CycleCountFetcher dw::framework::SyncPortHelper::m_syncCountRetriever protected
Definition at line 69 of file SyncPortHelper.hpp.
The documentation for this struct was generated from the following file:
src/dwcgf/port/SyncPortHelper.hpp