Compute Graph Framework SDK Reference: dw::framework::ChannelParams Class Reference
dw::framework::ChannelParams Class Reference
Detailed Description
Class to hold the parsed Channel parameters.
Definition at line 498 of file ChannelParameters.hpp.
Public Member Functions
ChannelParams (const ChannelParams &other)
ChannelParams (const char *params)
uint32_t getDataOffset () const
bool getDebugMode () const
uint16_t getDebugPort () const
uint16_t getExpectedConnectionsCount () const
uint16_t getExpectedDebugConnectionsCount () const
size_t getFifoSize () const
ChannelParamStr getId () const
bool getMailboxMode () const
const ChannelNvSciStreamParams & getNvSciStreamParams () const
size_t getPoolCapacity () const
bool getReuseEnabled () const
ChannelRole getRole () const
ChannelParamStr getSingletonId () const
bool getSingletonMode () const
const ChannelSocketParams & getSocketParams () const
const char * getStr () const
bool getSyncEnabled () const
ChannelType getType () const
bool isStrictFifo () const
ChannelParams & operator= (const ChannelParams &other)=default
void setMailboxMode (bool mailboxEnabled)
void setStrictFifo (bool strictFifo)
~ChannelParams ()=default
Constructor & Destructor Documentation
ChannelParams() [1/2]
dw::framework::ChannelParams::ChannelParams (const char * params) inline explicit
Definition at line 501 of file ChannelParameters.hpp.
References dw::framework::MAILBOX, dw::framework::ParseAllChannelParameters(), and dw::framework::SINGLETON.
ChannelParams() [2/2]
dw::framework::ChannelParams::ChannelParams (const ChannelParams & other) inline
Definition at line 570 of file ChannelParameters.hpp.
~ChannelParams()
dw::framework::ChannelParams::~ChannelParams () default
Member Function Documentation
getDataOffset()
uint32_t dw::framework::ChannelParams::getDataOffset () const inline
Definition at line 601 of file ChannelParameters.hpp.
getDebugMode()
bool dw::framework::ChannelParams::getDebugMode () const inline
Definition at line 606 of file ChannelParameters.hpp.
getDebugPort()
uint16_t dw::framework::ChannelParams::getDebugPort () const inline
Definition at line 581 of file ChannelParameters.hpp.
getExpectedConnectionsCount()
uint16_t dw::framework::ChannelParams::getExpectedConnectionsCount () const inline
Definition at line 607 of file ChannelParameters.hpp.
getExpectedDebugConnectionsCount()
uint16_t dw::framework::ChannelParams::getExpectedDebugConnectionsCount () const inline
Definition at line 608 of file ChannelParameters.hpp.
getFifoSize()
size_t dw::framework::ChannelParams::getFifoSize () const inline
Definition at line 582 of file ChannelParameters.hpp.
getId()
ChannelParamStr dw::framework::ChannelParams::getId () const inline
Definition at line 579 of file ChannelParameters.hpp.
getMailboxMode()
bool dw::framework::ChannelParams::getMailboxMode () const inline
Definition at line 593 of file ChannelParameters.hpp.
getNvSciStreamParams()
const ChannelNvSciStreamParams & dw::framework::ChannelParams::getNvSciStreamParams () const inline
Definition at line 621 of file ChannelParameters.hpp.
getPoolCapacity()
size_t dw::framework::ChannelParams::getPoolCapacity () const inline
Definition at line 592 of file ChannelParameters.hpp.
Referenced by dw::framework::SyncPortHelperOutput< T >::parseDataSynced(), and dw::framework::SyncPortHelperInput< T >::parseDataSynced().
getReuseEnabled()
bool dw::framework::ChannelParams::getReuseEnabled () const inline
Definition at line 605 of file ChannelParameters.hpp.
Referenced by dw::framework::PortInput< T >::bindChannel().
getRole()
ChannelRole dw::framework::ChannelParams::getRole () const inline
Definition at line 609 of file ChannelParameters.hpp.
getSingletonId()
ChannelParamStr dw::framework::ChannelParams::getSingletonId () const inline
Definition at line 580 of file ChannelParameters.hpp.
getSingletonMode()
bool dw::framework::ChannelParams::getSingletonMode () const inline
Definition at line 604 of file ChannelParameters.hpp.
getSocketParams()
const ChannelSocketParams & dw::framework::ChannelParams::getSocketParams () const inline
Definition at line 612 of file ChannelParameters.hpp.
getStr()
const char * dw::framework::ChannelParams::getStr () const inline
Definition at line 578 of file ChannelParameters.hpp.
getSyncEnabled()
bool dw::framework::ChannelParams::getSyncEnabled () const inline
Definition at line 602 of file ChannelParameters.hpp.
getType()
ChannelType dw::framework::ChannelParams::getType () const inline
Definition at line 610 of file ChannelParameters.hpp.
isStrictFifo()
bool dw::framework::ChannelParams::isStrictFifo () const inline
Definition at line 587 of file ChannelParameters.hpp.
operator=()
ChannelParams & dw::framework::ChannelParams::operator= (const ChannelParams & other) default
setMailboxMode()
void dw::framework::ChannelParams::setMailboxMode (bool mailboxEnabled) inline
Definition at line 603 of file ChannelParameters.hpp.
setStrictFifo()
void dw::framework::ChannelParams::setStrictFifo (bool strictFifo) inline
Definition at line 588 of file ChannelParameters.hpp.
The documentation for this class was generated from the following file:
src/dwcgf/channel/ChannelParameters.hpp