Compute Graph Framework SDK Reference: dw::framework::dwTraceCollectorNode Class Reference
dw::framework::dwTraceCollectorNode Class Reference
DW Core Nodes
Detailed Description
Definition at line 91 of file dwTraceCollectorNode.hpp.
Public Member Functions
dwTraceCollectorNode (const dwTraceCollectorNodeParams &params, const dwContextHandle_t ctx)
dwStatus executeAsyncReset () override
dwStatus setAsyncReset () override
Public Member Functions inherited from dw::framework::ExceptionSafeProcessNode
ExceptionSafeProcessNode (std::unique_ptr< Node > impl)
dwStatus getErrorSignal (dwGraphErrorSignal *&errorSignal) override
dwStatus getHealthSignal (dwGraphHealthSignal *&healthSignal, bool updateFromModule=false) override
dwStatus getInputChannel (const uint8_t portID, ChannelObject *&channel) const override
dwStatus getInputPort (const uint8_t portID, dw::framework::PortBase *&port) const override
dwStatus getName (const char **name) override
dwStatus getOutputChannel (const uint8_t portID, ChannelObject *&channel) const override
dwStatus getOutputPort (const uint8_t portID, dw::framework::PortBase *&port) const override
dwStatus getPass (Pass **pass, uint8_t index) override
size_t getPassCount () const noexcept override
dwStatus getPasses (VectorFixed< Pass * > &passList) override
dwStatus getPasses (VectorFixed< Pass * > &passList, dwProcessorType processorType, dwProcessType processType) override
dwStatus reportCurrentErrorSignal (dwGraphErrorSignal &signal) override
dwStatus reportCurrentHealthSignal (dwGraphHealthSignal &signal) override
dwStatus reset () override
void resetPorts () override
dwStatus run () override
dwStatus runPass (size_t passIndex) override
dwStatus setInputChannel (ChannelObject *channel, uint8_t portID) override
dwStatus setInputChannel (ChannelObject *channel, uint8_t portID, dwSerializationType dataType) override
dwStatus setIterationCount (uint32_t iterationCount) override final
dwStatus setName (const char *name) override
dwStatus setNodePeriod (uint32_t period) override final
dwStatus setOutputChannel (ChannelObject *channel, uint8_t portID) override
dwStatus setState (const char *state) override
dwStatus validate () override
~ExceptionSafeProcessNode () override=default
Public Member Functions inherited from dw::framework::Node
virtual dwStatus getErrorSignal (dwGraphErrorSignal *&errorSignal)=0
Get the pointer to the error signal for this node.
virtual dwStatus getHealthSignal (dwGraphHealthSignal *&healthSignals, bool updateFromModule=false)=0
Get the pointer to the health signal for this node.
virtual dwStatus getInputChannel (const uint8_t portID, ChannelObject *&channel) const =0
Gets the input channel associated with the input port.
virtual dwStatus getInputPort (const uint8_t portID, dw::framework::PortBase *&port) const =0
Gets the input port associated with the port id.
virtual dwStatus getName (const char **name)=0
Get the name of the node.
virtual dwStatus getOutputChannel (const uint8_t portID, ChannelObject *&channel) const =0
Gets the output channel associated with the output port.
virtual dwStatus getOutputPort (const uint8_t portID, dw::framework::PortBase *&port) const =0
Gets the output port associated with the port id.
virtual dwStatus getPass (Pass **pass, uint8_t index)=0
Get a const pointer to the pass at a specific index.
virtual size_t getPassCount () const noexcept=0
Get number of passes in the node.
virtual dwStatus getPasses (VectorFixed< Pass * > &passList)=0
Get all the passes in the node.
virtual dwStatus getPasses (VectorFixed< Pass * > &passList, dwProcessorType processorType, dwProcessType processType)=0
Get node passes filtered by processor type and process type.
virtual dwStatus reportCurrentErrorSignal (dwGraphErrorSignal &signal)=0
A function that allows user override to update error signal It is automatically called by dwFramework when getErrorSignal is called and when pass returns non-success return code.
virtual dwStatus reportCurrentHealthSignal (dwGraphHealthSignal &signal)=0
A function that allows user override to update health signal It is automatically called by dwFramework during teardown and when pass returns non-success return code.
virtual dwStatus reset ()=0
Resets the state of the node.
virtual void resetPorts ()=0
Resets all the ports in the node.
virtual dwStatus run ()=0
Runs all the passes in the node.
virtual dwStatus runPass (size_t passIndex)=0
Run one pass by index as defined by the pass descriptors.
virtual dwStatus setInputChannel (ChannelObject *channel, uint8_t portID)=0
Sets an input channel for this node with an accompanying port.
virtual dwStatus setInputChannel (ChannelObject *channel, uint8_t portID, dwSerializationType dataType)=0
Sets an input channel for this node with an accompanying port.
virtual dwStatus setIterationCount (uint32_t iterationCount)=0
Sets the node's iteration count.
virtual dwStatus setName (const char *name)=0
Set the name of the node.
virtual dwStatus setNodePeriod (uint32_t period)=0
Set the node's period.
virtual dwStatus setOutputChannel (ChannelObject *channel, uint8_t portID)=0
Sets an output channel for this node with an accompanying port.
virtual dwStatus setState (const char *state)=0
Set the current state in node. Node implementation of this API need to be thread-safe.
virtual dwStatus validate ()=0
Checks that all mandatory ports are bound. The implementation should validate that all the ports are bound to the appropriate channels (any required ports, that is). For example, a camera node may have processed output and raw output ports, but only one is required to be bound.
virtual ~Node ()=default
Public Member Functions inherited from dw::framework::IAsyncResetable
virtual dwStatus executeAsyncReset ()=0
Executes a reset if the async reset flag is set.
virtual dwStatus setAsyncReset ()=0
Set the async reset flag.
virtual ~IAsyncResetable ()=default
Static Public Member Functions
static std::unique_ptr< dwTraceCollectorNode > create (ParameterProvider &provider)
static constexpr auto describeInputPorts ()
static constexpr auto describeOutputPorts ()
static constexpr auto describeParameters ()
static constexpr auto describePasses ()
Static Public Attributes
static constexpr char LOG_TAG [] = "dwTraceCollectorNode"
Static Public Attributes inherited from dw::framework::Node
static constexpr size_t MAX_NAME_LEN = 128
static constexpr uint32_t MAX_PASS_COUNT = 256
static constexpr uint32_t MAX_PORT_COUNT = 256
Additional Inherited Members
Public Types inherited from dw::framework::Node
using Name_t = FixedString< MAX_NAME_LEN >
Protected Attributes inherited from dw::framework::ExceptionSafeProcessNode
std::unique_ptr< Node > m_impl
Constructor & Destructor Documentation
dwTraceCollectorNode()
dw::framework::dwTraceCollectorNode::dwTraceCollectorNode (const dwTraceCollectorNodeParams & params, const dwContextHandle_t ctx)
Member Function Documentation
create()
static std::unique_ptr< dwTraceCollectorNode > dw::framework::dwTraceCollectorNode::create (ParameterProvider & provider) static
describeInputPorts()
static constexpr auto dw::framework::dwTraceCollectorNode::describeInputPorts () inline static constexpr
Definition at line 96 of file dwTraceCollectorNode.hpp.
References dw::framework::describePortCollection(), DW_DESCRIBE_PORT_ARRAY, and dw::framework::MAX_INPUT_TRACE_PORTS.
describeOutputPorts()
static constexpr auto dw::framework::dwTraceCollectorNode::describeOutputPorts () inline static constexpr
Definition at line 102 of file dwTraceCollectorNode.hpp.
References dw::framework::describePortCollection().
describeParameters()
static constexpr auto dw::framework::dwTraceCollectorNode::describeParameters () inline static constexpr
Definition at line 115 of file dwTraceCollectorNode.hpp.
References dw::framework::channelMask, dw::framework::describeConstructorArgument(), dw::framework::diskIOStatsEnabled, DW_DESCRIBE_PARAMETER, DW_DESCRIBE_UNNAMED_PARAMETER, dw::framework::enabled, dw::framework::fileBackendEnabled, dw::framework::filePath, dw::framework::ftraceBackendEnabled, dw::framework::fullMemUsage, dw::framework::ipAddr, dw::framework::maxFileSizeMB, dw::framework::memTraceEnabled, dw::framework::networkBackendEnabled, dw::framework::nvtxBackendEnabled, dw::framework::serverPort, and dw::framework::tracingLevel.
describePasses()
static constexpr auto dw::framework::dwTraceCollectorNode::describePasses () inline static constexpr
Definition at line 107 of file dwTraceCollectorNode.hpp.
References dw::framework::describePass(), and dw::framework::describePassCollection().
executeAsyncReset()
dwStatus dw::framework::dwTraceCollectorNode::executeAsyncReset () inline override virtual
Implements dw::framework::IAsyncResetable.
Definition at line 201 of file dwTraceCollectorNode.hpp.
References dw::framework::IAsyncResetable::executeAsyncReset(), and dw::framework::ExceptionSafeProcessNode::m_impl.
setAsyncReset()
dwStatus dw::framework::dwTraceCollectorNode::setAsyncReset () inline override virtual
Implements dw::framework::IAsyncResetable.
Definition at line 188 of file dwTraceCollectorNode.hpp.
References dw::framework::ExceptionSafeProcessNode::m_impl, and dw::framework::IAsyncResetable::setAsyncReset().
Member Data Documentation
LOG_TAG
constexpr char dw::framework::dwTraceCollectorNode::LOG_TAG[] = "dwTraceCollectorNode" static constexpr
Definition at line 94 of file dwTraceCollectorNode.hpp.
The documentation for this class was generated from the following file:
src/dwframework/dwnodes/dwtrace/tracecollectornode/dwTraceCollectorNode.hpp