Compute Graph Framework SDK Reference: dw::framework::ChannelObject Class Reference
dw::framework::ChannelObject Class Reference abstract
Detailed Description
Top-level interface for a specific channel instance.
Definition at line 56 of file Channel.hpp.
Classes
class Consumer
class PacketPool
class Producer
class SyncClient
class SyncSignaler
class SyncWaiter
Public Member Functions
virtual dwStatus connect (dwTime_t timeout)=0
virtual void connectEndpoint (const char *nvsciipcEndpoint)=0
virtual void disconnectEndpoint (const char *nvsciipcEndpoint)=0
virtual Consumer * getConsumer (GenericDataReference ref)=0
virtual const ChannelParams & getParams () const =0
virtual Producer * getProducer (GenericDataReference ref)=0
virtual bool hasClients () const =0
virtual bool isConnected () const =0
virtual ~ChannelObject ()=default
Constructor & Destructor Documentation
~ChannelObject()
virtual dw::framework::ChannelObject::~ChannelObject () virtual default
Member Function Documentation
connect()
virtual dwStatus dw::framework::ChannelObject::connect (dwTime_t timeout) pure virtual
Establish connection over the channel's protocol.
Parameters
[in] timeout The maximum time to attempt connection. timeout of zero implies to do most atomic connection attempt.
Returns
DW_TIME_OUT The time out was reached before connection could be established. DW_CALL_NOT_ALLOWED There are no client interfaces to connect. DW_SUCCESS
connectEndpoint()
virtual void dw::framework::ChannelObject::connectEndpoint (const char * nvsciipcEndpoint) pure virtual
Connect consumer endpoint
Note
only supported for NvSci producer channels
disconnectEndpoint()
virtual void dw::framework::ChannelObject::disconnectEndpoint (const char * nvsciipcEndpoint) pure virtual
Disconnect consumer endpoint
Note
only supported for NvSci producer channels
getConsumer()
virtual Consumer * dw::framework::ChannelObject::getConsumer (GenericDataReference ref) pure virtual
Register a consumer client.
Note
The client interface is owned by the ChannelObject and should not be used after the ChannelObject has been destroyed.
allocates new objects to back the requested interface.
Parameters
[in] ref A reference for the data to be transfered over the channel
Returns
consumer interface
Exceptions
if parameters disallow consumer role.
Referenced by dw::framework::PortInput< T >::bindChannel().
getParams()
virtual const ChannelParams & dw::framework::ChannelObject::getParams () const pure virtual
Get the parameters for this channel
Referenced by dw::framework::PortInput< T >::bindChannel(), and dw::framework::PortOutput< T >::bindChannelWithReference().
getProducer()
virtual Producer * dw::framework::ChannelObject::getProducer (GenericDataReference ref) pure virtual
Register a producer client.
Note
The client interface is owned by the ChannelObject and should not be used after the ChannelObject has been destroyed.
This method shall only be called once per instance.
allocates new objects to back the requested interface.
Parameters
[in] ref A reference for the data to be transfered over the channel
Returns
producer interface
Exceptions
if parameters disallow producer role.
Referenced by dw::framework::PortOutput< T >::bindChannelWithReference().
hasClients()
virtual bool dw::framework::ChannelObject::hasClients () const pure virtual
Query if the channel has any clients
Note
The channel will not have client interfaces unless requested via getProducer or getConsumer.
isConnected()
virtual bool dw::framework::ChannelObject::isConnected () const pure virtual
Query if the channel and its client interfaces are connected to downstream/upstream channels and are ready for use
The documentation for this class was generated from the following file:
src/dwcgf/channel/Channel.hpp