Compute Graph Framework SDK Reference: dw::framework::ChannelObject::PacketPool Class Reference
dw::framework::ChannelObject::PacketPool Class Reference abstract
Detailed Description
Common interface for both Producers and Consumers.
Definition at line 116 of file Channel.hpp.
Public Types
using OnDataReady = dw::core::Function< void()>
Public Member Functions
SyncSignaler & getSyncSignaler ()
SyncWaiter & getSyncWaiter ()
virtual void setOnDataReady (void *opaque, OnDataReady onDataReady)=0
virtual dwStatus wait (dwTime_t timeout)=0
Member Typedef Documentation
OnDataReady
using dw::framework::ChannelObject::PacketPool::OnDataReady = dw::core::Function<void()>
Definition at line 134 of file Channel.hpp.
Member Function Documentation
getSyncSignaler()
SyncSignaler & dw::framework::ChannelObject::PacketPool::getSyncSignaler ()
Referenced by dw::framework::PortOutput< T >::getSyncSignaler(), dw::framework::PortInput< T >::getSyncSignaler(), dw::framework::PortOutput< T >::setSignalFences(), and dw::framework::PortInput< T >::setSignalFences().
getSyncWaiter()
SyncWaiter & dw::framework::ChannelObject::PacketPool::getSyncWaiter ()
Referenced by dw::framework::PortOutput< T >::getSyncWaiter(), dw::framework::PortInput< T >::getSyncWaiter(), dw::framework::PortOutput< T >::getWaitFences(), and dw::framework::PortInput< T >::getWaitFences().
setOnDataReady()
virtual void dw::framework::ChannelObject::PacketPool::setOnDataReady (void * opaque, OnDataReady onDataReady) pure virtual
Set callback for when data is ready.
Exceptions
DW_NOT_SUPPORTED if not supported
Referenced by dw::framework::PortOutput< T >::setOnDataReady(), and dw::framework::PortInput< T >::setOnDataReady().
wait()
virtual dwStatus dw::framework::ChannelObject::PacketPool::wait (dwTime_t timeout) pure virtual
Wait for packets
Parameters
[in] timeout Maximum time to wait for packet to become available.
Returns
DW_TIME_OUT Timeout was reached and no packets became available. DW_END_OF_STREAM Upstream producer disconnected, so no further packets will come. DW_SUCCESS
Referenced by dw::framework::PortOutput< T >::wait(), and dw::framework::PortInput< T >::wait().
The documentation for this class was generated from the following file:
src/dwcgf/channel/Channel.hpp