Compute Graph Framework SDK Reference: dw::framework::PortInput< T > Class Template Reference
dw::framework::PortInput< T > Class Template Reference
Detailed Description
template<typename T>
class dw::framework::PortInput< T >
PortInput mimics an Output Block. It wrapps over a Consumer Channel. Provides services like
binding(allocating channel resources, out of current scope),
waiting for next event
receiving packet
Definition at line 286 of file Port.hpp.
Public Types
using ApiDataTypeT = T
using BaseSyncHelper = SyncPortHelperInput< T >
using SpecimenT = typename parameter_traits< T >::SpecimenT
Public Member Functions
dwStatus bindChannel (ChannelObject *channel) override
ChannelMetadata & getMetadata (T *frame)
ChannelObject::SyncSignaler & getSyncSignaler ()
ChannelObject::SyncWaiter & getSyncWaiter ()
void getWaitFences (T *frame, dw::core::span< NvSciSyncFence > fences)
bool isBound () override
PortInput ()
PortInput (OnSetSyncAttrs waiterAttrs, OnSetSyncAttrs signalerAttrs={})
PortInput (SpecimenT &&ref)
PortInput (SpecimenT const &ref)
PortInput (SpecimenT const &ref, OnSetSyncAttrs waiterAttrs, OnSetSyncAttrs signalerAttrs={})
virtual std::shared_ptr< T > recv ()
void setOnDataReady (void *opaque, ChannelObject::PacketPool::OnDataReady onDataReady)
void setSignalFences (T *frame, dw::core::span< NvSciSyncFence > fences)
dwStatus wait (dwTime_t timeout)
~PortInput () override=default
Public Member Functions inherited from dw::framework::SyncPortHelperInput< T >
SyncPortHelperInput ()
Public Member Functions inherited from dw::framework::SyncPortHelper
bool isDataSynced ()
virtual void parseDataSynced (const ChannelParams &params)
void setSyncCount (uint32_t index)
dwStatus setSyncRetriever (const CycleCountFetcher &func)
SyncPortHelper ()
Public Member Functions inherited from dw::framework::Port
virtual dwStatus bindChannel (ChannelObject *channel)=0
virtual ChannelObject * getChannel ()
virtual dwStatus initialize ()
virtual bool isBound ()=0
Public Member Functions inherited from dw::framework::PortBase
virtual ~PortBase ()=default
Static Public Attributes
static constexpr PortDirection DIRECTION = PortDirection::INPUT
Additional Inherited Members
Protected Member Functions inherited from dw::framework::SyncPortHelperInput< T >
T * extractInternalPacket (GenericData genericData)
T * extractSyncPacket (GenericData genericData)
GenericData getBufferedPacket ()
MetadataPayload * getMetadataPacket (T *frame)
bool isPacketBuffered ()
bool isValidPacketBuffered ()
void parseDataSynced (const ChannelParams &params) override
Protected Member Functions inherited from dw::framework::SyncPortHelper
ChannelPacketTypeID getNewPacketID (ChannelPacketTypeID packetTypeID)
void stampSyncCount (uint32_t &syncCountOut) const
Protected Attributes inherited from dw::framework::SyncPortHelper
uint32_t m_dataOffset
bool m_dataSynced
uint32_t m_syncCount
CycleCountFetcher m_syncCountRetriever
Protected Attributes inherited from dw::framework::Port
ChannelObject * m_channel {nullptr}
Member Typedef Documentation
ApiDataTypeT
template<typename T > using dw::framework::PortInput< T >::ApiDataTypeT = T
Definition at line 296 of file Port.hpp.
BaseSyncHelper
template<typename T > using dw::framework::PortInput< T >::BaseSyncHelper = SyncPortHelperInput<T>
Definition at line 298 of file Port.hpp.
SpecimenT
template<typename T > using dw::framework::PortInput< T >::SpecimenT = typename parameter_traits<T>::SpecimenT
Definition at line 297 of file Port.hpp.
Constructor & Destructor Documentation
PortInput() [1/5]
template<typename T > dw::framework::PortInput< T >::PortInput (SpecimenT const & ref) inline explicit
Definition at line 302 of file Port.hpp.
PortInput() [2/5]
template<typename T > dw::framework::PortInput< T >::PortInput (SpecimenT && ref) inline explicit
Definition at line 306 of file Port.hpp.
PortInput() [3/5]
template<typename T > dw::framework::PortInput< T >::PortInput () inline
Definition at line 311 of file Port.hpp.
PortInput() [4/5]
template<typename T > dw::framework::PortInput< T >::PortInput (OnSetSyncAttrs waiterAttrs, OnSetSyncAttrs signalerAttrs = {}) inline explicit
Definition at line 315 of file Port.hpp.
PortInput() [5/5]
template<typename T > dw::framework::PortInput< T >::PortInput (SpecimenT const & ref, OnSetSyncAttrs waiterAttrs, OnSetSyncAttrs signalerAttrs = {}) inline explicit
Definition at line 322 of file Port.hpp.
~PortInput()
template<typename T > dw::framework::PortInput< T >::~PortInput () override default
Member Function Documentation
bindChannel()
template<typename T > dwStatus dw::framework::PortInput< T >::bindChannel (ChannelObject * channel) inline override virtual
Implements dw::framework::Port.
Definition at line 334 of file Port.hpp.
References dw::framework::ChannelObject::getConsumer(), dw::framework::SyncPortHelper::getNewPacketID(), dw::framework::ChannelObject::getParams(), dw::framework::ChannelParams::getReuseEnabled(), dw::framework::PortInput< T >::isBound(), dw::framework::Port::m_channel, and dw::framework::SyncPortHelperInput< T >::parseDataSynced().
getMetadata()
template<typename T > ChannelMetadata & dw::framework::PortInput< T >::getMetadata (T * frame) inline
Definition at line 488 of file Port.hpp.
References dw::framework::SyncPortHelperInput< T >::getMetadataPacket(), and dw::framework::MetadataPayload::header.
getSyncSignaler()
template<typename T > ChannelObject::SyncSignaler & dw::framework::PortInput< T >::getSyncSignaler () inline
Definition at line 499 of file Port.hpp.
References dw::framework::ChannelObject::PacketPool::getSyncSignaler().
getSyncWaiter()
template<typename T > ChannelObject::SyncWaiter & dw::framework::PortInput< T >::getSyncWaiter () inline
Definition at line 513 of file Port.hpp.
References dw::framework::ChannelObject::PacketPool::getSyncWaiter().
getWaitFences()
template<typename T > void dw::framework::PortInput< T >::getWaitFences (T * frame, dw::core::span< NvSciSyncFence > fences) inline
Definition at line 522 of file Port.hpp.
References dw::framework::SyncPortHelperInput< T >::getMetadataPacket(), dw::framework::ChannelObject::PacketPool::getSyncWaiter(), and dw::framework::ChannelObject::SyncWaiter::getWaitFences().
isBound()
template<typename T > bool dw::framework::PortInput< T >::isBound () inline override virtual
Implements dw::framework::Port.
Definition at line 372 of file Port.hpp.
Referenced by dw::framework::PortInput< T >::bindChannel(), dw::framework::ReadProcessedDataFromChannel< OutputProcessedDataType, InputProcessedDataType >::readNextData(), dw::framework::PortInput< T >::recv(), dw::framework::PortInput< T >::setOnDataReady(), and dw::framework::PortInput< T >::wait().
recv()
template<typename T > virtual std::shared_ptr< T > dw::framework::PortInput< T >::recv () inline virtual
Definition at line 421 of file Port.hpp.
References dw::framework::SyncPortHelperInput< T >::extractInternalPacket(), dw::framework::SyncPortHelperInput< T >::extractSyncPacket(), dw::framework::SyncPortHelperInput< T >::getBufferedPacket(), dw::framework::PortInput< T >::isBound(), dw::framework::SyncPortHelper::isDataSynced(), dw::framework::SyncPortHelperInput< T >::isPacketBuffered(), dw::framework::SyncPortHelperInput< T >::isValidPacketBuffered(), and dw::framework::ChannelObject::Consumer::recv().
Referenced by dw::framework::ReadProcessedDataFromChannel< OutputProcessedDataType, InputProcessedDataType >::readNextData().
setOnDataReady()
template<typename T > void dw::framework::PortInput< T >::setOnDataReady (void * opaque, ChannelObject::PacketPool::OnDataReady onDataReady) inline
Definition at line 377 of file Port.hpp.
References dw::framework::PortInput< T >::isBound(), and dw::framework::ChannelObject::PacketPool::setOnDataReady().
setSignalFences()
template<typename T > void dw::framework::PortInput< T >::setSignalFences (T * frame, dw::core::span< NvSciSyncFence > fences) inline
Definition at line 508 of file Port.hpp.
References dw::framework::SyncPortHelperInput< T >::getMetadataPacket(), dw::framework::ChannelObject::PacketPool::getSyncSignaler(), and dw::framework::ChannelObject::SyncSignaler::setSignalFences().
wait()
template<typename T > dwStatus dw::framework::PortInput< T >::wait (dwTime_t timeout) inline
Definition at line 387 of file Port.hpp.
References dw::framework::PortInput< T >::isBound(), dw::framework::SyncPortHelper::isDataSynced(), dw::framework::SyncPortHelperInput< T >::isPacketBuffered(), dw::framework::SyncPortHelperInput< T >::isValidPacketBuffered(), and dw::framework::ChannelObject::PacketPool::wait().
Referenced by dw::framework::ReadProcessedDataFromChannel< OutputProcessedDataType, InputProcessedDataType >::readNextData().
Member Data Documentation
DIRECTION
template<typename T > constexpr PortDirection dw::framework::PortInput< T >::DIRECTION = PortDirection::INPUT static constexpr
Definition at line 295 of file Port.hpp.
The documentation for this class was generated from the following file:
src/dwcgf/core/dwcgf/port/Port.hpp