Compute Graph Framework SDK Reference: dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc > Class Template Reference
dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc > Class Template Reference
Detailed Description
template<typename ProcessedDataType, typename ReadProcessedDataFunc>
class dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >
Definition at line 412 of file dwSensorDrainerTemplate.hpp.
Public Types
using Base = dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >
Public Types inherited from dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >
using OnDataDropped = dw::core::Function< void(dwTime_t const)>
Public Member Functions
dwSensorDrainerTemplate (dwSensorDrainerParams params, std::unique_ptr< ReadProcessedDataFunc > readProcessedDataFunc, dwSensorHandle_t hsensor)
dwStatus getNextTimestamp (dwTime_t &timestamp, dwTime_t timeout) override
dwStatus readProcessedData (ProcessedDataType *outFrame, dwTime_t &latestTimestamp, dwTime_t timeout, bool isDroppingData=false) override
dwStatus replayDroppedFrames (ProcessedDataType *processedOutput, SensorNode::DataEvent &dataEvent, SensorNode::DataEventReadCallback readCb)
virtual dwStatus replayProcessedData (ProcessedDataType *processedOutput, dwTime_t &timestampOutput, SensorNode::DataEventReadCallback readCb)
virtual dwStatus reset () override
virtual ~dwSensorDrainerTemplate ()=default
Public Member Functions inherited from dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >
virtual dwStatus drainProcessedData (ProcessedDataType *processedOutput, dwTime_t &timestampOutput, dwTime_t &nextTimestampOutput, dwTime_t virtualSyncTime)
dwBaseDrainerTemplate (dwSensorDrainerParams params, std::unique_ptr< ReadProcessedDataFunc > readProcessedDataFunc, dwSensorHandle_t dataSource)
virtual dwStatus getNextData (ProcessedDataType *outFrame, dwTime_t timeout)
virtual dwStatus getNextTimestamp (dwTime_t &timestamp, dwTime_t timeout)
virtual dwTime_t getReadTimeout () const
virtual void isLockstepDataAvailable (dwStatus &status, dwTime_t &readTimeout)
virtual bool isVirtualDataReady (dwTime_t dataTime, dwTime_t timeout)
void populateNextTimestamp (dwTime_t &nextTimestampOutput)
dwStatus readNextWithFrameMask (dwTime_t timeout)
virtual dwStatus readProcessedData (ProcessedDataType *outFrame, dwTime_t &latestTimestamp, dwTime_t timeout, bool isDroppingData=false)=0
virtual dwStatus reset ()
virtual void setLockstepDeterministicMode (bool enable)
void setOnDataDropped (OnDataDropped onDataDropped)
virtual void setVirtualSyncTime (dwTime_t virtualSyncTime)
virtual dwStatus tryRead (ProcessedDataType *outFrame, dwTime_t &latestTimestamp, dwTime_t timeout, bool isDroppingData=false)
Static Public Attributes
static constexpr char LOG_TAG [] = "dwSensorDrainerTemplate"
Static Public Attributes inherited from dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >
static constexpr int32_t DRAIN_SENSOR_DATA_COUNT_MAX
static constexpr char LOG_TAG []
Protected Attributes
bool m_autoReset = false
bool m_isLockstep = false
Protected Attributes inherited from dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >
dwTime_t m_blockingTimeout
dwSensorHandle_t m_dataSource
bool m_dropStaleData
FixedString< 32 > m_frameReadMask
bool m_frameSkipEnabled
uint32_t m_framesRead
bool m_isLockstep
bool m_isVirtual
bool m_lockstepDeterministicMode
Node::Name_t m_name
bool m_nextDataReady
dwTime_t m_nonBlockingTimeout
OnDataDropped m_onDataDropped
bool m_outputAvailable
std::unique_ptr< ReadProcessedDataFunc > m_readProcessedDataFunc
dwTime_t m_stashedNextTime
dwTime_t m_virtualSyncTime
bool m_waitForNewData
Additional Inherited Members
Static Protected Attributes inherited from dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >
static constexpr dwTime_t REPLAY_SENSOR_READ_TIMEOUT
Member Typedef Documentation
Base
template<typename ProcessedDataType , typename ReadProcessedDataFunc > using dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::Base = dwBaseDrainerTemplate<ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t>
Definition at line 416 of file dwSensorDrainerTemplate.hpp.
Constructor & Destructor Documentation
dwSensorDrainerTemplate()
template<typename ProcessedDataType , typename ReadProcessedDataFunc > dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::dwSensorDrainerTemplate (dwSensorDrainerParams params, std::unique_ptr< ReadProcessedDataFunc > readProcessedDataFunc, dwSensorHandle_t hsensor) inline explicit
Definition at line 418 of file dwSensorDrainerTemplate.hpp.
~dwSensorDrainerTemplate()
template<typename ProcessedDataType , typename ReadProcessedDataFunc > virtual dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::~dwSensorDrainerTemplate () virtual default
Member Function Documentation
getNextTimestamp()
template<typename ProcessedDataType , typename ReadProcessedDataFunc > dwStatus dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::getNextTimestamp (dwTime_t & timestamp, dwTime_t timeout) inline override virtual
Reimplemented from dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >.
Definition at line 425 of file dwSensorDrainerTemplate.hpp.
References dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >::getNextTimestamp(), dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >::m_dataSource, dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >::m_frameSkipEnabled, dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >::m_isVirtual, and dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >::m_lockstepDeterministicMode.
readProcessedData()
template<typename ProcessedDataType , typename ReadProcessedDataFunc > dwStatus dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::readProcessedData (ProcessedDataType * outFrame, dwTime_t & latestTimestamp, dwTime_t timeout, bool isDroppingData = false) inline override virtual
Implements dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >.
Definition at line 460 of file dwSensorDrainerTemplate.hpp.
References dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::m_autoReset, dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >::m_blockingTimeout, dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::reset(), and dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >::tryRead().
Referenced by dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::replayDroppedFrames(), and dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::replayProcessedData().
replayDroppedFrames()
template<typename ProcessedDataType , typename ReadProcessedDataFunc > dwStatus dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::replayDroppedFrames (ProcessedDataType * processedOutput, SensorNode::DataEvent & dataEvent, SensorNode::DataEventReadCallback readCb) inline
Definition at line 483 of file dwSensorDrainerTemplate.hpp.
References dw::framework::ISensorNode::DataEvent::dataEventType, dw::framework::ISensorNode::DROP, dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::readProcessedData(), dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >::REPLAY_SENSOR_READ_TIMEOUT, and dw::framework::ISensorNode::DataEvent::timestamp.
Referenced by dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::replayProcessedData().
replayProcessedData()
template<typename ProcessedDataType , typename ReadProcessedDataFunc > virtual dwStatus dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::replayProcessedData (ProcessedDataType * processedOutput, dwTime_t & timestampOutput, SensorNode::DataEventReadCallback readCb) inline virtual
Reimplemented in dw::framework::dwVehicleStateDrainer.
Definition at line 534 of file dwSensorDrainerTemplate.hpp.
References dw::framework::ISensorNode::NONE, dw::framework::ISensorNode::PRODUCE, dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::readProcessedData(), dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >::REPLAY_SENSOR_READ_TIMEOUT, and dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::replayDroppedFrames().
Referenced by dw::framework::dwVehicleStateDrainer::replayProcessedData().
reset()
template<typename ProcessedDataType , typename ReadProcessedDataFunc > virtual dwStatus dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::reset () inline override virtual
Reimplemented from dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >.
Definition at line 442 of file dwSensorDrainerTemplate.hpp.
References dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >::m_dataSource, and dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, dwSensorHandle_t >::reset().
Referenced by dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::readProcessedData().
Member Data Documentation
LOG_TAG
template<typename ProcessedDataType , typename ReadProcessedDataFunc > constexpr char dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::LOG_TAG = "dwSensorDrainerTemplate" static constexpr
Definition at line 415 of file dwSensorDrainerTemplate.hpp.
m_autoReset
template<typename ProcessedDataType , typename ReadProcessedDataFunc > bool dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::m_autoReset = false protected
Definition at line 615 of file dwSensorDrainerTemplate.hpp.
Referenced by dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::readProcessedData().
m_isLockstep
template<typename ProcessedDataType , typename ReadProcessedDataFunc > bool dw::framework::dwSensorDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc >::m_isLockstep = false protected
Definition at line 616 of file dwSensorDrainerTemplate.hpp.
The documentation for this class was generated from the following file:
src/dwframework/dwnodes/sensors/dwsensornode/dwSensorDrainerTemplate.hpp