Compute Graph Framework SDK Reference: dw::framework::IAsyncResetable Class Reference
dw::framework::IAsyncResetable Class Reference abstract
Detailed Description
Definition at line 461 of file Node.hpp.
Public Member Functions
virtual dwStatus executeAsyncReset ()=0
Executes a reset if the async reset flag is set.
virtual dwStatus setAsyncReset ()=0
Set the async reset flag.
virtual ~IAsyncResetable ()=default
Constructor & Destructor Documentation
~IAsyncResetable()
virtual dw::framework::IAsyncResetable::~IAsyncResetable () virtual default
Member Function Documentation
executeAsyncReset()
virtual dwStatus dw::framework::IAsyncResetable::executeAsyncReset () pure virtual
Executes a reset if the async reset flag is set.
Returns
DW_SUCCESS, DW_FAILURE
Implemented in dw::framework::dwTraceCollectorNode, dw::framework::dwGlobalEgomotionNode, dw::framework::dwRelativeEgomotionIMUNode, and dw::framework::dwRelativeEgomotionIMUNodeImpl.
Referenced by dw::framework::dwTraceCollectorNode::executeAsyncReset(), dw::framework::dwGlobalEgomotionNode::executeAsyncReset(), and dw::framework::dwRelativeEgomotionIMUNode::executeAsyncReset().
setAsyncReset()
virtual dwStatus dw::framework::IAsyncResetable::setAsyncReset () pure virtual
Set the async reset flag.
Returns
DW_SUCCESS, DW_FAILURE
Implemented in dw::framework::dwTraceCollectorNode, dw::framework::dwGlobalEgomotionNode, dw::framework::dwRelativeEgomotionIMUNode, and dw::framework::dwRelativeEgomotionIMUNodeImpl.
Referenced by dw::framework::dwTraceCollectorNode::setAsyncReset(), dw::framework::dwGlobalEgomotionNode::setAsyncReset(), and dw::framework::dwRelativeEgomotionIMUNode::setAsyncReset().
The documentation for this class was generated from the following file:
src/dwcgf/core/dwcgf/node/Node.hpp