Compute Graph Framework SDK Reference: dw::framework::SimpleNodeT< T > Class Template Reference
dw::framework::SimpleNodeT< T > Class Template Reference
Detailed Description
template<typename T>
class dw::framework::SimpleNodeT< T >
Definition at line 107 of file SimpleNodeT.hpp.
Public Types
using NodeT = T
Public Types inherited from dw::framework::Node
using Name_t = FixedString< MAX_NAME_LEN >
Public Member Functions
std::unique_ptr< Pass > createSetupPass () override
std::unique_ptr< Pass > createTeardownPass () override
dwStatus reset () override
The default implementation calls SimpleNode::resetPorts.
virtual dwStatus setupImpl ()
The default implementation calls SimpleNode::setup.
SimpleNodeT ()
Default constructor registering the setup and teardown passes.
SimpleNodeT (NodeAllocationParams params)
virtual dwStatus teardownImpl ()
The default implementation calls SimpleNode::teardown.
dwStatus validate () override
Validate that all registered ports which have the flag binding-required are bound to a channel.
Public Member Functions inherited from dw::framework::SimpleNode
void addPass (Pass *pass)
dwStatus clearHealthSignal ()
Clears the current Health Signals from the Health Signal Array.
dwStatus copyModuleHealthSignals (dwHealthSignal &outSignal)
Copy health signals from the module over to the node and stores in outSignal.
dwStatus getErrorSignal (dwGraphErrorSignal *&errorSignal) override
dwStatus getHealthSignal (dwGraphHealthSignal *&healthSignals, bool updateFromModule=false) override
dwStatus getInputChannel (const uint8_t portID, ChannelObject *&channel) const override
Gets the input channel associated with the input port.
template<typename NodeT , size_t PortIndex>
ManagedPortInput< decltype(portType< NodeT, PortDirection::INPUT, PortIndex >())> & getInputPort ()
Get a previously initialized non-array ManagedPortInput.
dwStatus getInputPort (const uint8_t portID, dw::framework::PortBase *&port) const override
Gets the input port associated with the input port Id.
template<typename NodeT , size_t PortIndex>
ManagedPortInput< decltype(portType< NodeT, PortDirection::INPUT, PortIndex >())> & getInputPort (size_t arrayIndex)
Get one specific ManagedPortInput from a previously initialized input array port.
uint32_t getIterationCount () const
dwStatus getName (const char **name) override
uint32_t getNodePeriod () const
dwStatus getOutputChannel (const uint8_t portID, ChannelObject *&channel) const override
Gets the output channel associated with the output port.
template<typename NodeT , size_t PortIndex>
ManagedPortOutput< decltype(portType< NodeT, PortDirection::OUTPUT, PortIndex >())> & getOutputPort ()
Get a previously initialized non-array ManagedPortOutput.
dwStatus getOutputPort (const uint8_t portID, dw::framework::PortBase *&port) const override
Gets the output port associated with the output port Id.
template<typename NodeT , size_t PortIndex>
ManagedPortOutput< decltype(portType< NodeT, PortDirection::OUTPUT, PortIndex >())> & getOutputPort (size_t arrayIndex)
Get one specific ManagedPortOutput from a previously initialized output array port.
dwStatus getPass (Pass **pass, uint8_t index) override
size_t getPassCount () const noexcept override
dwStatus getPasses (VectorFixed< Pass * > &passList) override
dwStatus getPasses (VectorFixed< Pass * > &passList, dwProcessorType processorType, dwProcessType processType) override
const dw::core::HeapHashMap< size_t, std::shared_ptr< PortBase > > & getRegisteredInputPorts () const
const dw::core::HeapHashMap< size_t, std::shared_ptr< PortBase > > & getRegisteredOutputPorts () const
template<typename NodeT , size_t PortIndex, typename... Args>
void initInputArrayPort (Args &&... args)
Initialize an array of ManagedPortInput which will be owned by the base class and can be retrieved using getInputPort(size_t).
template<typename NodeT , size_t PortIndex, typename... Args>
void initInputPort (Args &&... args)
Initialize a ManagedPortInput which will be owned by the base class and can be retrieved using getInputPort().
template<typename NodeT , size_t PortIndex, typename... Args>
void initOutputArrayPort (Args &&... args)
Initialize an array of ManagedPortOutput which will be owned by the base class and can be retrieved using getOutputPort(size_t).
template<typename NodeT , size_t PortIndex, typename... Args>
void initOutputPort (Args &&... args)
Initialize a ManagedPortOutput which will be owned by the base class and can be retrieved using getOutputPort().
template<typename Func >
void iterateManagedInputPorts (Func func)
template<typename Func >
void iterateManagedOutputPorts (Func func)
template<typename Func , typename PortList >
void iteratePorts (PortList &portList, Func func)
template<typename TPort , typename... Args>
std::unique_ptr< TPort > make_port (Args &&... args)
dwStatus reportCurrentErrorSignal (dwGraphErrorSignal &signal) override
A function that allows user override to update error signal It is automatically called by dwFramework when getErrorSignal is called and when pass returns non-success return code.
dwStatus reportCurrentHealthSignal (dwGraphHealthSignal &signal) override
A function that allows user override to update health signal It is automatically called by dwFramework during teardown and when pass returns non-success return code.
dwStatus reset () override
void resetPorts () override
Default implementation to reset ports managed by the base class.
dwStatus run () override
dwStatus runPass (size_t passIndex) override
dwStatus setInputChannel (ChannelObject *, uint8_t, dwSerializationType) override
dwStatus setInputChannel (ChannelObject *channel, uint8_t portID) override
Associate an input port with a channel instances.
dwStatus setIterationCount (uint32_t iterationCount) override
template<typename ModuleHandle_t >
dwStatus setModuleHandle (ModuleHandle_t handle, dwContextHandle_t context)
dwStatus setName (const char *name) final
dwStatus setNodePeriod (uint32_t period) override
virtual dwStatus setObjectHandle (dwModuleHandle_t handle)
dwStatus setOutputChannel (ChannelObject *channel, uint8_t portID) override
Associate an output port with a channel instances.
dwStatus setState (const char *state) override
dwStatus setup ()
Default implementation of the setup pass.
SimpleNode ()
SimpleNode (NodeAllocationParams params)
Constructor which tailors the preallocated size of the internal collections for ports and passes to the need of the concrete node.
dwStatus teardown ()
Default implementation of the teardown pass.
dwStatus updateHealthSignal (const dwGraphHealthSignal &signal)
Adds the provided Health Signal to the Health Signal Array. If the array is full, the new signal will not be added.
dwStatus validate () override
dwStatus validate (const char *direction, const PortCollectionDescriptor &collection, const dw::core::HeapHashMap< size_t, std::shared_ptr< PortBase > > &ports, size_t indexOffset=0)
Helper function used by dw::framework::SimpleNodeT::validate.
virtual ~SimpleNode ()
Public Member Functions inherited from dw::framework::Node
virtual dwStatus getErrorSignal (dwGraphErrorSignal *&errorSignal)=0
Get the pointer to the error signal for this node.
virtual dwStatus getHealthSignal (dwGraphHealthSignal *&healthSignals, bool updateFromModule=false)=0
Get the pointer to the health signal for this node.
virtual dwStatus getInputChannel (const uint8_t portID, ChannelObject *&channel) const =0
Gets the input channel associated with the input port.
virtual dwStatus getInputPort (const uint8_t portID, dw::framework::PortBase *&port) const =0
Gets the input port associated with the port id.
virtual dwStatus getName (const char **name)=0
Get the name of the node.
virtual dwStatus getOutputChannel (const uint8_t portID, ChannelObject *&channel) const =0
Gets the output channel associated with the output port.
virtual dwStatus getOutputPort (const uint8_t portID, dw::framework::PortBase *&port) const =0
Gets the output port associated with the port id.
virtual dwStatus getPass (Pass **pass, uint8_t index)=0
Get a const pointer to the pass at a specific index.
virtual size_t getPassCount () const noexcept=0
Get number of passes in the node.
virtual dwStatus getPasses (VectorFixed< Pass * > &passList)=0
Get all the passes in the node.
virtual dwStatus getPasses (VectorFixed< Pass * > &passList, dwProcessorType processorType, dwProcessType processType)=0
Get node passes filtered by processor type and process type.
virtual dwStatus reportCurrentErrorSignal (dwGraphErrorSignal &signal)=0
A function that allows user override to update error signal It is automatically called by dwFramework when getErrorSignal is called and when pass returns non-success return code.
virtual dwStatus reportCurrentHealthSignal (dwGraphHealthSignal &signal)=0
A function that allows user override to update health signal It is automatically called by dwFramework during teardown and when pass returns non-success return code.
virtual dwStatus reset ()=0
Resets the state of the node.
virtual void resetPorts ()=0
Resets all the ports in the node.
virtual dwStatus run ()=0
Runs all the passes in the node.
virtual dwStatus runPass (size_t passIndex)=0
Run one pass by index as defined by the pass descriptors.
virtual dwStatus setInputChannel (ChannelObject *channel, uint8_t portID)=0
Sets an input channel for this node with an accompanying port.
virtual dwStatus setInputChannel (ChannelObject *channel, uint8_t portID, dwSerializationType dataType)=0
Sets an input channel for this node with an accompanying port.
virtual dwStatus setIterationCount (uint32_t iterationCount)=0
Sets the node's iteration count.
virtual dwStatus setName (const char *name)=0
Set the name of the node.
virtual dwStatus setNodePeriod (uint32_t period)=0
Set the node's period.
virtual dwStatus setOutputChannel (ChannelObject *channel, uint8_t portID)=0
Sets an output channel for this node with an accompanying port.
virtual dwStatus setState (const char *state)=0
Set the current state in node. Node implementation of this API need to be thread-safe.
virtual dwStatus validate ()=0
Checks that all mandatory ports are bound. The implementation should validate that all the ports are bound to the appropriate channels (any required ports, that is). For example, a camera node may have processed output and raw output ports, but only one is required to be bound.
virtual ~Node ()=default
Additional Inherited Members
Static Public Attributes inherited from dw::framework::SimpleNode
static constexpr const char * PASS_SETUP_NAME = "SETUP"
static constexpr const char * PASS_TEARDOWN_NAME = "TEARDOWN"
Static Public Attributes inherited from dw::framework::Node
static constexpr size_t MAX_NAME_LEN = 128
static constexpr uint32_t MAX_PASS_COUNT = 256
static constexpr uint32_t MAX_PORT_COUNT = 256
Protected Member Functions inherited from dw::framework::SimpleNode
virtual std::unique_ptr< Pass > createSetupPass ()
virtual std::unique_ptr< Pass > createTeardownPass ()
dwStatus getModuleHandle (dwModuleHandle_t *moduleHandle, void *handle, dwContextHandle_t context)
template<typename PassFunctionT , typename... Args>
std::unique_ptr< PassImpl< PassFunctionT > > make_pass (PassFunctionT func, Args &&... args)
template<typename NodeT , size_t PassIndex, typename PassFunctionT >
void registerPass (PassFunctionT func, NvMediaDla *dlaEngine=nullptr)
Register a pass function with the node base class.
Protected Attributes inherited from dw::framework::SimpleNode
std::atomic< bool > m_asyncResetFlag {false}
dw::core::HeapHashMap< size_t, std::shared_ptr< PortBase > > m_inputPorts
dw::core::HeapHashMap< size_t, std::shared_ptr< PortBase > > m_outputPorts
Member Typedef Documentation
NodeT
template<typename T > using dw::framework::SimpleNodeT< T >::NodeT = T
Definition at line 110 of file SimpleNodeT.hpp.
Constructor & Destructor Documentation
SimpleNodeT() [1/2]
template<typename T > dw::framework::SimpleNodeT< T >::SimpleNodeT () inline
Default constructor registering the setup and teardown passes.
Definition at line 113 of file SimpleNodeT.hpp.
SimpleNodeT() [2/2]
template<typename T > dw::framework::SimpleNodeT< T >::SimpleNodeT (NodeAllocationParams params) inline
Definition at line 119 of file SimpleNodeT.hpp.
Member Function Documentation
createSetupPass()
template<typename T > std::unique_ptr< Pass > dw::framework::SimpleNodeT< T >::createSetupPass () inline override virtual
Deprecated:
When using SimpleProcessNodeT as the base class for a concrete node this methods shouldn't be invoked since the base class provides a default implementation for the setup pass in SimpleProcessNodeT::setupImpl.
Reimplemented from dw::framework::SimpleNode.
Definition at line 127 of file SimpleNodeT.hpp.
createTeardownPass()
template<typename T > std::unique_ptr< Pass > dw::framework::SimpleNodeT< T >::createTeardownPass () inline override virtual
Deprecated:
When using SimpleProcessNodeT as the base class for a concrete node this methods shouldn't be invoked since the base class provides a default implementation for the setup pass in SimpleProcessNodeT::teardownImpl.
Reimplemented from dw::framework::SimpleNode.
Definition at line 134 of file SimpleNodeT.hpp.
reset()
template<typename T > dwStatus dw::framework::SimpleNodeT< T >::reset () inline override virtual
The default implementation calls SimpleNode::resetPorts.
Reimplemented from dw::framework::SimpleNode.
Definition at line 152 of file SimpleNodeT.hpp.
References dw::framework::SimpleNode::resetPorts().
setupImpl()
template<typename T > virtual dwStatus dw::framework::SimpleNodeT< T >::setupImpl () inline virtual
The default implementation calls SimpleNode::setup.
Reimplemented in dw::framework::dwRelativeEgomotionIMUNodeImpl.
Definition at line 140 of file SimpleNodeT.hpp.
References dw::framework::SimpleNode::setup().
teardownImpl()
template<typename T > virtual dwStatus dw::framework::SimpleNodeT< T >::teardownImpl () inline virtual
The default implementation calls SimpleNode::teardown.
Definition at line 146 of file SimpleNodeT.hpp.
References dw::framework::SimpleNode::teardown().
validate()
template<typename T > dwStatus dw::framework::SimpleNodeT< T >::validate () inline override virtual
Validate that all registered ports which have the flag binding-required are bound to a channel.
Reimplemented from dw::framework::SimpleNode.
Definition at line 159 of file SimpleNodeT.hpp.
References dw::framework::PortCollectionDescriptor::getPortSize(), dw::framework::SimpleNode::getRegisteredInputPorts(), dw::framework::SimpleNode::getRegisteredOutputPorts(), and dw::framework::SimpleNode::validate().
The documentation for this class was generated from the following file:
src/dwcgf/core/dwcgf/node/SimpleNodeT.hpp