Compute Graph Framework SDK Reference: dw::framework::dwLidarBatchNode Class Reference
dw::framework::dwLidarBatchNode Class Reference
DW Core Nodes
Detailed Description
Definition at line 53 of file dwLidarBatchNode.hpp.
Public Member Functions
dwLidarBatchNode (const char *sensorName, dwConstRigHandle_t rigHandle, dwSALHandle_t sal, dwContextHandle_t ctx, const FixedString< 32 > &frameSkipMask)
dwLidarBatchNode (const dwSensorParams &params, dwSALHandle_t sal, dwContextHandle_t ctx)
dwStatus getLidarProperties (dwLidarProperties *prop)
Public Member Functions inherited from dw::framework::ExceptionSafeSensorNode
ExceptionSafeSensorNode (std::unique_ptr< Node > impl)
dwStatus getErrorSignal (dwGraphErrorSignal *&errorSignal) override
dwStatus getHealthSignal (dwGraphHealthSignal *&healthSignal, bool updateFromModule=false) override
dwStatus getInputChannel (const uint8_t portID, ChannelObject *&channel) const override
dwStatus getInputPort (const uint8_t portID, dw::framework::PortBase *&port) const override
dwStatus getName (const char **name) override
dwStatus getNextTimestamp (dwTime_t &nextTimestamp) final
dwStatus getOutputChannel (const uint8_t portID, ChannelObject *&channel) const override
dwStatus getOutputPort (const uint8_t portID, dw::framework::PortBase *&port) const override
dwStatus getPass (Pass **pass, uint8_t index) override
size_t getPassCount () const noexcept override
dwStatus getPasses (VectorFixed< Pass * > &passList) override
dwStatus getPasses (VectorFixed< Pass * > &passList, dwProcessorType processorType, dwProcessType processType) override
dwStatus isVirtual (bool *isVirtualBool) override
dwStatus reportCurrentErrorSignal (dwGraphErrorSignal &signal) override
dwStatus reportCurrentHealthSignal (dwGraphHealthSignal &signal) override
dwStatus reset () override
void resetPorts () override
dwStatus run () override
dwStatus runPass (size_t passIndex) override
dwStatus setAffinityMask (uint mask) override
dwStatus setDataEventReadCallback (DataEventReadCallback cb) override
dwStatus setDataEventWriteCallback (DataEventWriteCallback cb) override
dwStatus setEndTime (dwTime_t endTime) override
dwStatus setInputChannel (ChannelObject *channel, uint8_t portID) override
dwStatus setInputChannel (ChannelObject *channel, uint8_t portID, dwSerializationType dataType) override
dwStatus setIterationCount (uint32_t iterationCount) override final
dwStatus setLockstepDeterministicMode (bool enable) final
dwStatus setName (const char *name) override
void setNodeImple (std::unique_ptr< Node > impl)
dwStatus setNodePeriod (uint32_t period) override final
dwStatus setOutputChannel (ChannelObject *channel, uint8_t portID) override
dwStatus setStartTime (dwTime_t startTime) override
dwStatus setState (const char *state) override
dwStatus setThreadPriority (int prio) override
dwStatus start () override
dwStatus stop () override
dwStatus validate () override
~ExceptionSafeSensorNode () override=default
Public Member Functions inherited from dw::framework::Node
virtual dwStatus getErrorSignal (dwGraphErrorSignal *&errorSignal)=0
Get the pointer to the error signal for this node.
virtual dwStatus getHealthSignal (dwGraphHealthSignal *&healthSignals, bool updateFromModule=false)=0
Get the pointer to the health signal for this node.
virtual dwStatus getInputChannel (const uint8_t portID, ChannelObject *&channel) const =0
Gets the input channel associated with the input port.
virtual dwStatus getInputPort (const uint8_t portID, dw::framework::PortBase *&port) const =0
Gets the input port associated with the port id.
virtual dwStatus getName (const char **name)=0
Get the name of the node.
virtual dwStatus getOutputChannel (const uint8_t portID, ChannelObject *&channel) const =0
Gets the output channel associated with the output port.
virtual dwStatus getOutputPort (const uint8_t portID, dw::framework::PortBase *&port) const =0
Gets the output port associated with the port id.
virtual dwStatus getPass (Pass **pass, uint8_t index)=0
Get a const pointer to the pass at a specific index.
virtual size_t getPassCount () const noexcept=0
Get number of passes in the node.
virtual dwStatus getPasses (VectorFixed< Pass * > &passList)=0
Get all the passes in the node.
virtual dwStatus getPasses (VectorFixed< Pass * > &passList, dwProcessorType processorType, dwProcessType processType)=0
Get node passes filtered by processor type and process type.
virtual dwStatus reportCurrentErrorSignal (dwGraphErrorSignal &signal)=0
A function that allows user override to update error signal It is automatically called by dwFramework when getErrorSignal is called and when pass returns non-success return code.
virtual dwStatus reportCurrentHealthSignal (dwGraphHealthSignal &signal)=0
A function that allows user override to update health signal It is automatically called by dwFramework during teardown and when pass returns non-success return code.
virtual dwStatus reset ()=0
Resets the state of the node.
virtual void resetPorts ()=0
Resets all the ports in the node.
virtual dwStatus run ()=0
Runs all the passes in the node.
virtual dwStatus runPass (size_t passIndex)=0
Run one pass by index as defined by the pass descriptors.
virtual dwStatus setInputChannel (ChannelObject *channel, uint8_t portID)=0
Sets an input channel for this node with an accompanying port.
virtual dwStatus setInputChannel (ChannelObject *channel, uint8_t portID, dwSerializationType dataType)=0
Sets an input channel for this node with an accompanying port.
virtual dwStatus setIterationCount (uint32_t iterationCount)=0
Sets the node's iteration count.
virtual dwStatus setName (const char *name)=0
Set the name of the node.
virtual dwStatus setNodePeriod (uint32_t period)=0
Set the node's period.
virtual dwStatus setOutputChannel (ChannelObject *channel, uint8_t portID)=0
Sets an output channel for this node with an accompanying port.
virtual dwStatus setState (const char *state)=0
Set the current state in node. Node implementation of this API need to be thread-safe.
virtual dwStatus validate ()=0
Checks that all mandatory ports are bound. The implementation should validate that all the ports are bound to the appropriate channels (any required ports, that is). For example, a camera node may have processed output and raw output ports, but only one is required to be bound.
virtual ~Node ()=default
virtual dwStatus getNextTimestamp (dwTime_t &nextTimestamp)=0
Get the next timestamp of the sensor.
virtual dwStatus isVirtual (bool *isVirtualBool)=0
distinguishes between a live and virtual sensor
virtual dwStatus setAffinityMask (uint)=0
Sets the affinity mask of the sensor.
virtual dwStatus setDataEventReadCallback (DataEventReadCallback cb)=0
Set read timestamp function for dataset replay. Timestamps not in the sequence returned by the callback will be dropped.
virtual dwStatus setDataEventWriteCallback (DataEventWriteCallback cb)=0
Set write timestamp function for live case. Each timestamp of data output from the node will be passed to this callback.
virtual dwStatus setEndTime (dwTime_t)=0
Set end timestamp for dataset replay.
virtual dwStatus setLockstepDeterministicMode (bool enable)=0
Set whether replay is running in lockstep deterministic mode.
virtual dwStatus setStartTime (dwTime_t)=0
Set start timestamp for dataset replay.
virtual dwStatus setThreadPriority (int)=0
Sets the thread priority of the sensor.
virtual dwStatus start ()=0
Start the sensor.
virtual dwStatus stop ()=0
Stop the sensor.
Static Public Member Functions
static std::unique_ptr< dwLidarBatchNode > create (ParameterProvider &provider)
static constexpr auto describeInputPorts ()
static constexpr auto describeOutputPorts ()
static constexpr auto describeParameters ()
static constexpr auto describePasses ()
Static Public Attributes
static constexpr char LOG_TAG [] = "dwLidarBatchNode"
Static Public Attributes inherited from dw::framework::Node
static constexpr size_t MAX_NAME_LEN = 128
static constexpr uint32_t MAX_PASS_COUNT = 256
static constexpr uint32_t MAX_PORT_COUNT = 256
Additional Inherited Members
Public Types inherited from dw::framework::Node
using Name_t = FixedString< MAX_NAME_LEN >
Public Types inherited from dw::framework::ISensorNode
using DataEventReadCallback = dw::core::Function< bool(DataEvent &)>
enum class DataEventType {
PRODUCE ,
DROP ,
NONE
}
using DataEventWriteCallback = dw::core::Function< void(DataEvent)>
Protected Attributes inherited from dw::framework::ExceptionSafeSensorNode
std::unique_ptr< Node > m_impl
ISensorNode * m_sensorNodeImpl
Constructor & Destructor Documentation
dwLidarBatchNode() [1/2]
dw::framework::dwLidarBatchNode::dwLidarBatchNode (const char * sensorName, dwConstRigHandle_t rigHandle, dwSALHandle_t sal, dwContextHandle_t ctx, const FixedString< 32 > & frameSkipMask)
dwLidarBatchNode() [2/2]
dw::framework::dwLidarBatchNode::dwLidarBatchNode (const dwSensorParams & params, dwSALHandle_t sal, dwContextHandle_t ctx)
Member Function Documentation
create()
static std::unique_ptr< dwLidarBatchNode > dw::framework::dwLidarBatchNode::create (ParameterProvider & provider) static
describeInputPorts()
static constexpr auto dw::framework::dwLidarBatchNode::describeInputPorts () inline static constexpr
Definition at line 58 of file dwLidarBatchNode.hpp.
References dw::framework::describePortCollection(), and DW_DESCRIBE_PORT.
describeOutputPorts()
static constexpr auto dw::framework::dwLidarBatchNode::describeOutputPorts () inline static constexpr
Definition at line 64 of file dwLidarBatchNode.hpp.
References dw::framework::describePortCollection(), and DW_DESCRIBE_PORT.
describeParameters()
static constexpr auto dw::framework::dwLidarBatchNode::describeParameters () inline static constexpr
Definition at line 83 of file dwLidarBatchNode.hpp.
References dw::framework::describeConstructorArgument(), DW_DESCRIBE_INDEX_PARAMETER_WITH_SEMANTIC, DW_DESCRIBE_PARAMETER, and DW_DESCRIBE_UNNAMED_PARAMETER.
describePasses()
static constexpr auto dw::framework::dwLidarBatchNode::describePasses () inline static constexpr
Definition at line 74 of file dwLidarBatchNode.hpp.
References dw::framework::describePass(), and dw::framework::describePassCollection().
getLidarProperties()
dwStatus dw::framework::dwLidarBatchNode::getLidarProperties (dwLidarProperties * prop)
Member Data Documentation
LOG_TAG
constexpr char dw::framework::dwLidarBatchNode::LOG_TAG[] = "dwLidarBatchNode" static constexpr
Definition at line 56 of file dwLidarBatchNode.hpp.
The documentation for this class was generated from the following file:
src/dwframework/dwnodes/sensors/dwlidarnode/dwLidarBatchNode.hpp