Compute Graph Framework SDK Reference: dw::framework Namespace Reference
dw::framework Namespace Reference
Namespaces
namespace lockstep
namespace semantic_parameter_types
Classes
class Buffer
class BufferBase
class BufferCPU
class BufferCUDA
struct BufferProperties
class ChannelConnector
struct ChannelEvent
class ChannelFactory
struct ChannelMetadata
class ChannelNvSciPacketDefault
class ChannelNvSciStreamParams
class ChannelObject
class ChannelPacket
class ChannelPacket< dwCodecPacket >
class ChannelPacket< dwEgomotionStateHandle_t >
class ChannelPacket< dwFeatureArray >
class ChannelPacket< dwFeatureHistoryArray >
class ChannelPacket< dwFeatureNccScores >
class ChannelPacket< dwImageHandle_t >
class ChannelPacket< dwLatency >
class ChannelPacket< dwLidarDecodedPacket >
class ChannelPacket< dwLidarPacketsArray >
class ChannelPacket< dwPointCloud >
class ChannelPacket< dwPyramidImage >
class ChannelPacket< dwSensorNodeRawData >
class ChannelPacket< dwTraceNodeData >
class ChannelPacket< SensorServiceNodeRawData >
class ChannelPacketBase
class ChannelPacketDefault
class ChannelPacketDefaultBase
class ChannelPacketRadarScan
class ChannelParams
class ChannelSocketPacketBase
class ChannelSocketParams
class CodecPacket
class ContextParameterProvider
A parameter provider for the dwContextHandle_t.
struct dwAccumulatorNodeParams
class dwBaseDrainerTemplate
struct dwCalibratedExtrinsics
struct dwCalibratedIMUIntrinsics
struct dwCalibratedSteeringProperties
struct dwCalibratedWheelRadii
struct dwCameraIntrinsics
class dwCameraNode
struct dwCameraNodeParams
Construction parameters for dwCameraNode.
class dwChannelDrainerTemplate
class DWChannelFactory
struct dwCodecMetadata
struct dwDetectorFovealParams
class dwFeatureDetectorNode
class dwFeatureDetectorNodeBase
class dwFeatureDetectorPVANode
struct dwFeatureNccScores
class dwFeatureTrackerNode
class dwFeatureTrackerNodeBase
class dwFeatureTrackerPVANode
class dwGlobalEgomotionNode
This node computes the global vehicle state and motion over time using signals from GPS and relative egomotion.
struct dwGlobalEgomotionNodeInitParams
struct dwGlobalEgomotionState
class dwGPSChannelNode
class dwGPSNode
struct dwGPSNodeParams
class dwIcpNode
class dwIMUChannelNode
class dwIMUNode
struct dwIMUNodeParams
struct dwLatency
class dwLidarBatchNode
class dwLidarNode
struct dwLidarPacketsArray
class dwLidarPointCloudAccumulatorNode
class dwLidarPointCloudStitcherNode
struct dwLidarPointCloudStitcherNodeParams
struct dwLidarPose
class dwPointCloudAccumulatorNode
struct dwPointCloudAccumulatorNodeParams
class dwPyramidNode
class dwPyramidNodeBase
class dwPyramidPVANode
class dwRadarChannelNode
class dwRadarDopplerMotionNode
struct dwRadarDopplerMotionNodeParams
class dwRadarNode
class dwRelativeEgomotionIMUNode
This node computes the vehicle state and relative motion over time using signals from IMU and wheelspeed sensors.
class dwRelativeEgomotionIMUNodeImpl
struct dwRelativeEgomotionIMUNodeInitParams
class dwRigNode
dwRigNode receives extrinsic calibrations from sensors in the system, and maintains that state to update the vehicle's rig file on program exit.
struct dwRoadCastNodeCalibrationData
struct dwRoadCastNodeCalibrationDataArray
struct dwRoadCastNodeCalibrationWheelRadiiData
class dwSelfCalibrationNode
struct dwSelfCalibrationNodeCameraParams
struct dwSelfCalibrationNodeLidarParams
struct dwSelfCalibrationNodeParam
struct dwSelfCalibrationNodeRadarParams
class dwSelfCalibrationRoadcastAggregatorNode
struct dwSelfCalibrationRoadcastAggregatorNodeParam
class dwSelfCalibrationSingleIMUNode
struct dwSelfCalibrationSingleIMUNodeParam
struct dwSensorDrainerParams
class dwSensorDrainerTemplate
class dwSensorNode
struct dwSensorNodeProperties
struct dwSensorNodeRawData
class dwTraceCollectorNode
class dwTraceNode
struct dwTraceNodeData
class dwUltrasonicChannelNode
class dwUltrasonicNode
class dwVehicleStateChannelDrainer
class dwVehicleStateChannelNewNode
class dwVehicleStateChannelNode
class dwVehicleStateDrainer
class dwVehicleStateNode
class EgomotionStateHandlePacket
struct EnumDescription
struct EnumDescription< dwEgomotionLinearAccelerationFilterMode >
struct EnumDescription< dwEgomotionSpeedMeasurementType >
struct EnumDescription< dwFovealMode >
struct EnumDescription< dwImageFormat >
struct EnumDescription< dwImageMemoryType >
struct EnumDescription< dwImageType >
struct EnumDescription< dwMemoryType >
struct EnumDescription< dwMotionModel >
struct EnumDescription< dwPointCloudFormat >
struct EnumDescription< dwPrecision >
struct EnumDescription< dwProcessorType >
struct EnumDescription< dwSensorType >
struct EnumDescription< dwTrivialDataType >
class ExceptionSafeProcessNode
class ExceptionSafeSensorNode
class FeatureArrayPacket
class FeatureHistoryArrayPacket
class FeatureNccScoresPacket
class GenericData
struct GenericDataReference
struct GPSNodeChannelParams
class IAsyncResetable
class IChannelDebugConsumer
class IChannelDebugProducer
class IChannelPacket
class IChannelPacketFactory
class IChannelsConnectedListener
class IContainsPreShutdownAction
class ImageHandlePacket
struct IMUNodeChannelParams
class IResetable
class ISensorNode
class ITypeBasedParameterProviderChild
The additional interface a ParameterProvider can implement so it can be registered at a TypeBasedParameterProvider.
struct ITypeInformation
class JsonParameterProvider
A parameter provider which retrieves parameter values from JSON data.
class LatencyPacket
class ManagedPortBase
class ManagedPortInput
class ManagedPortInputBase
class ManagedPortOutput
class ManagedPortOutputBase
struct MetadataPayload
class Node
struct NodeAllocationParams
class NodeConcept
The class only exists for documentation.
struct packet_traits
struct parameter_traits
class ParameterCollectionDescriptor
A collection of parameter descriptors.
class ParameterDescriptor
The description of a parameter.
class ParameterDescriptorWithDefault
The description of a parameter with a default value.
class ParameterProvider
The interface to access parameter values identified by name and/or (semantic) type.
class Pass
Pass is a runnable describes the metadata of a pass.
class PassCollectionDescriptor
A collection of pass descriptors.
class PassDescriptor
The description of a pass.
class PassImpl
PassImpl contains the function to invoke on run().
class PointCloudChannelPacket
class Port
class PortBase
class PortCollectionDescriptor
class PortDescriptor
class PortInput
class PortOutput
class PyramidImagePacket
class RadarScanNvSciPacket
struct ReadProcessedDataFromChannel
struct RegisteredPort
class RegisteredPortInput
class RegisteredPortOutput
class SensorCommonImpl
class SensorNode
struct SensorServiceNodeRawData
class SensorServiceNodeRawDataPacket
class SimpleNode
class SimpleNodeT
class SimpleProcessNode
class SimpleProcessNodeT
class SimpleSensorNode
class SimpleSensorNodeT
struct SyncPortHelper
class SyncPortHelperInput
class SyncPortHelperOutput
class TypeBasedParameterProvider
A parameter provider which dispatches the retrieval of the parameter value to registered handlers which are selected based on the name, size, and optional array index of the parameter.
struct TypeInformation
struct VehicleStateNodeNewParams
struct VehicleStateNodeParams
Typedefs
using BufferFlags = uint32_t
using CalibrationExtrinsicProfileName = dw::core::FixedString< DW_MAX_EXTRINSIC_PROFILE_NAME_SIZE >
using CalibrationIntrinsicsString = dw::core::FixedString< 64 >
using CalibrationResultsString = dw::core::FixedString< 512 >
using ChannelPacketConstructor = dw::core::Function< std::unique_ptr< IChannelPacket >(GenericData dataSpecimen, dwContextHandle_t context)>
using ChannelPacketConstructorRegistration = std::pair< ChannelPacketConstructorSignature, ChannelPacketConstructor >
using ChannelPacketConstructorSignature = std::pair< ChannelPacketTypeID, ChannelType >
using ChannelPacketFactoryPtr = std::shared_ptr< IChannelPacketFactory >
using ChannelPacketTypeID = uint32_t
using ChannelParamStr = dw::core::FixedString< MAX_CHANNEL_PARAM_SIZE >
using ChannelType = enum ChannelType :uint8_t { DW_CHANNEL_TYPE_SHMEM_LOCAL=0, DW_CHANNEL_TYPE_SHMEM_REMOTE=1, DW_CHANNEL_TYPE_EGLSTREAM=2, DW_CHANNEL_TYPE_SOCKET=3, DW_CHANNEL_TYPE_DDS=4, DW_CHANNEL_TYPE_NVSCI=5, }
using CycleCountFetcher = dw::core::Function< uint32_t(void)>
using dwFeatureDetectorNodeParams = dwFeatureDetectorNodeParams { bool initForCamera
using dwFeatureDetectorNodeRuntimeParams = dwFeatureDetectorNodeRuntimeParams { uint8_t *d_mask
using dwFeatureTrackerNodeParams = dwFeatureTrackerNodeParams { bool initForCamera
using dwIcpNodeParams = dwIcpNodeParams { dwRigHandle_t rigHandle
using dwPyramidNodeParams = dwPyramidNodeParams { uint32_t width
using dwRigNodeParams = dwRigNodeParams { bool serialization
using dwTraceCollectorNodeParams = dwTraceCollectorNodeParams { bool stmControlTracing
using dwTraceNodeParams = dwTraceNodeParams { bool stmControlTracing
using OnSetSyncAttrs = dw::core::Function< void(NvSciSyncAttrList)>
template<typename T >
using UniquePacketPtr = typename ManagedPortInput< T >::UniquePacketPtr
Enumerations
enum class BufferBackendType : uint32_t {
CPU = 0 ,
CUDA = 1
}
enum class CameraIntrinsicsSource {
RIG ,
EEPROM
}
enum class ChannelConnectionType {
CONNECTION_TYPE_NONE = 0 ,
CONNECTION_TYPE_STATIC ,
CONNECTION_TYPE_DYNAMIC
}
enum class ChannelEventType {
CONNECTED ,
DISCONNECTED ,
ERROR ,
READY
}
enum class ChannelMode {
FIFO ,
MAILBOX ,
SINGLETON
}
enum class ChannelNvSciStreamEnabledComponents : uint32_t {
COMPONENT_NONE = 0 ,
COMPONENT_CPU = 1 << 0 ,
COMPONENT_EGL = 1 << 1 ,
COMPONENT_CUDA = 1 << 2 ,
COMPONENT_PVA = 1 << 3 ,
COMPONENT_DLA = 1 << 4 ,
COMPONENT_NVMEDIA = 1 << 5
}
enum class ChannelReach {
REACH_NONE = 0 ,
REACH_THREAD ,
REACH_PROCESS ,
REACH_VM ,
REACH_CHIP
}
enum class ChannelRole : uint8_t {
DW_CHANNEL_ROLE_PRODUCER = 0b01 ,
DW_CHANNEL_ROLE_CONSUMER = 0b10 ,
DW_CHANNEL_ROLE_COMPOSITE = 0b11
}
enum class DWChannelPacketTypeID {
DEFAULT = DWFRAMEWORK_PACKET_ID_DEFAULT ,
NUM_TYPES
}
enum class dwFovealMode {
OFF ,
FULL ,
INTERLEAVED
}
enum class dwModeDnnROI {
TOP ,
MIDDLE ,
BOTTOM
}
enum dwSerializationType {
DW_TYPE_INVALID = 0 ,
DW_ACTUATION_SUPERVISOR_STATUS ,
DW_ACTUATED_REPLAY_STATUS ,
DW_ADAS_OBJECT_ARRAY ,
DW_AEB_REQUEST ,
DW_AEB_STATE_INFO ,
DW_AV_STATS ,
DW_AV_CONFIG ,
DW_BEHAVIOR_PLANNER_ACC_INFO ,
DW_BEHAVIOR_PLANNER_LANE_CHANGE_INFO ,
DW_BEHAVIOR_PLANNER_LANE_HANDLE_INFO ,
DW_BEHAVIOR_PLANNER_MERGE_INFO ,
DW_BEHAVIOR_PLANNER_WAIT_ELEMENT_INFO ,
DW_BEHAVIOR_PLANNER_DEBUG_INFO ,
DW_TRAJECTORY_PLANNER_DEBUG_INFO ,
DW_BEHAVIOR_PLANNER_EVALUATION_RESULTS ,
DW_CALIBRATED_STEER_OFFSET ,
DW_CALIBRATED_WHEEL_RADII ,
DW_BLINDNESS_DETECTION_OUTPUT ,
DW_CALIBRATION ,
DW_COMMAND_TO_CONTROL ,
DW_CUBOID_3D ,
DW_CVIP_LIST ,
DW_DISENGAGEMENT_DATA ,
DW_EGOMOTION_RESULT_PAYLOAD ,
DW_EGOMOTION_STATE_HANDLE ,
DW_EGOMOTION_POSE_PAYLOAD ,
DW_ENCODED_FRAME ,
DW_EVENT_FLAG ,
DW_EVENT_SURVEY ,
DW_FEATURE_NCC_SCORES ,
DW_FEATURE_ARRAY ,
DW_FEATURE_HISTORY_ARRAY ,
DW_FREESPACE_DETECTION ,
DW_GLOBAL_EGOMOTION_RESULT_PAYLOAD ,
DW_GLOBAL_EGOMOTION_STATE ,
DW_GPS_FRAME ,
DW_HEARTBEAT ,
DW_IMAGE_HANDLE ,
DW_IMU_FRAME ,
DW_INTERSECTION_ARRAY ,
DW_INTERSECTION_DETECTION ,
DW_KPI_STATUS ,
DW_LANE_ARRAY ,
DW_LANE_ASSIGNMENT_ARRAY ,
DW_LANE_CHUNK_ARRAY ,
DW_LANE_DETECTION ,
DW_LANE_GRAPH ,
DW_LANE_GRAPH_LIST ,
DW_LANE_GRAPH_WORLD_MODEL ,
DW_LANE_PLAN_ACTIONS ,
DW_LANE_PLAN_ACTIONS_NEW ,
DW_LANE_SUPPORT_STATUS ,
DW_LANDMARK_DETECTION ,
DW_DASHMARK_DETECTION ,
DW_ROADMARK_DETECTION ,
DW_EGO_LANE_BIASING_INFO ,
DW_ROAD_SEPARATION ,
DW_CAMERA_VISIBILITY ,
DW_LIGHT_SOURCE_PERCEPTION_AUTO_BEAM_STATUS ,
DW_LIGHT_SOURCE_PERCEPTION_DETECTOR_MASK ,
DW_LIGHT_FUNCTIONS_DATA ,
DW_LIDAR_DECODED_PACKET ,
DW_LSS_REQUEST ,
DW_LDW_HMI_REQUEST ,
DW_LOCALIZATION_RESULT ,
DW_LOCALIZATIONNAVMAP_RESULT ,
DW_LOGIN_SURVEY ,
DW_MSG_VERSION ,
DW_OBJECT_ARRAY ,
DW_OBJECT_CAMERA ,
DW_OBJECT_DETECTION ,
DW_OBJECT_FUSED ,
DW_OBJECT_GENERIC ,
DW_OBJECT_HISTORY_ARRAY ,
DW_OBJECT_LIDAR ,
DW_OBJECT_RADAR ,
DW_OBJECT_ARRAY_RADARDNN ,
DW_OBSTACLE ,
DW_OBSTACLE_ARRAY ,
DW_OBSTACLE_LINK_ARRAY ,
DW_OBSTACLE_RDM ,
DW_OBSTACLE_RDM_RADARDNN ,
DW_PATH ,
DW_PATH_DETECTION ,
DW_PERCEPTION_OBJECT ,
DW_PYRAMID_IMAGE ,
DW_POINT_CLOUD ,
DW_RADAR_DOPPLER_MOTION ,
DW_RADAR_SCAN ,
DW_RADAR_TRACK_EXTENDED ,
DW_RADAR_GRID_RADAR_OBSTACLES ,
DW_RESIM_CONFIG ,
DW_RESIM_FAILURE ,
DW_RESIM_LOG ,
DW_RESIM_METADATA_LOG ,
DW_RESIM_SEGMENT_LOG ,
DW_SAFETY_FORCE_FIELD_METRIC ,
DW_SAFETY_FORCE_FIELD_STATE ,
DW_MATCHED_ROUTE ,
DW_LARGE_LANE_GRAPH_REWARD_ARRAY ,
DW_LARGE_LANE_GRAPH_LINK_ARRAY ,
DW_SENSOR_NODE_RAW_DATA ,
DW_STRATEGY_HEALTH_STATE ,
DW_SURROUND_MONITOR_RADAR_STATE ,
DW_SURROUND_MONITOR_LANECHANGE_SAFEDECISION ,
DW_RADAR_PERCEPTION_RADAR_STATE ,
DW_SURVEY_REQUEST ,
DW_TEXT ,
DW_TELEMETRY_SESSION ,
DW_TEMPORAL_FUSION_DEBUG_INFO ,
DW_PARKING_PLANNER_DEBUG_INFO ,
DW_TIME ,
DW_TIME_SERIES ,
DW_TIME_SERIES_ARRAY ,
DW_HEALTH_SIGNAL_ARRAY ,
DW_GRAPH_HEALTH_SIGNAL ,
DW_ERROR_SIGNAL ,
DW_GRAPH_ERROR_SIGNAL ,
DW_TRAFFIC_SIGNAL_OBJECT_LIST ,
DW_TRANSFORMATION_PAYLOAD ,
DW_TSLOBJECTS ,
DW_VEHICLE_CALIBRATION ,
DW_VEHICLE_CONTROL_KPI ,
DW_VEHICLE_CONTROL_STATUS ,
DW_VEHICLE_IO_STATE ,
DW_VEHICLE_COMMAND ,
DW_VEHICLE_MISC_COMMAND ,
DW_WAIT_GROUP_ARRAY ,
DW_WAIT_ELEMENT_GROUP ,
DW_WAIT_ELEMENT_GROUPS ,
DW_WAIT_LINE_ARRAY ,
DW_DEPTH_IMAGE ,
DW_CAMERA_PROPERTIES ,
DW_CAMERA_MODEL_TRANSFORM_PARAM ,
DW_SPEEDLIMIT_ARRAY ,
DW_SPEEDLIMIT_LANE_ASSOCIATION_ARRAY ,
DW_SPEEDLIMIT_WORLD_MODEL ,
DW_SPEEDLIMIT_POSITIONAL_ARRAY ,
DW_SPEEDLIMIT_ATTRIBUTES_ARRAY ,
DW_TSA_PLANNER_HMI_REQUEST ,
DW_BLIND_SPOT_MONITOR_STATE_INFO ,
DW_TSA_PLANNER_STATE_INFO ,
DW_NEAR_FIELD_ASSIST_STATE_INFO ,
DW_WAIT_ELEMENT_ARRAY ,
DW_PREDICTED_TRAJECTORIES ,
DW_PARKING_SPACE_ARRAY ,
DW_CODEC_PACKET ,
DW_SENSOR_SERVICE_RAW_DATA ,
DW_SENSOR_TS_AND_ID ,
DW_AUTO_EMERGENCY_STEERING_REQUEST ,
DW_RECORDED_PATH ,
FLOAT32 ,
DW_LANE_ASSIGNMENT_DEBUG_INFO ,
DW_OBJECT_FUSION_RUN_METADATA ,
DW_TRAFFIC_LIGHTS_ARRAY ,
DW_TEXT_REGION_ARRAY ,
DW_WC_VIEW_LINE_3D_ARRAY ,
DW_MPPSELECTOROUTPUT ,
DW_LANE_CURVATURE_INFO ,
DW_TRAFFIC_LIGHT_ASSOCIATION_ARRAY ,
DW_ROADPROFILEDATA ,
DW_TYPES_COUNT
}
enum class MetadataFlags : uint16_t {
METADATA_ITERATION_COUNT = 1 << 0 ,
METADATA_EPOCH_TIMESTAMP = 1 << 1 ,
METADATA_VALIDITY_STATUS = 1 << 2 ,
METADATA_TIMESTAMP = 1 << 3
}
enum class PortBinding : uint8_t {
OPTIONAL = 0 ,
REQUIRED = 1
}
enum class PortDirection : uint8_t {
INPUT = 0 ,
OUTPUT ,
COUNT
}
Functions
bool BufferFlagsBackendEnabled (BufferFlags flags, BufferBackendType type)
void BufferFlagsEnableBackend (BufferFlags &flags, BufferBackendType type)
bool checkHeaderValidFlag (ChannelMetadata const &header, MetadataFlags flag)
dwGraphErrorSignal convertToGraphErrorSignal (dwErrorSignal const &signal)
dwGraphHealthSignal convertToGraphHealthSignal (const dwHealthSignal &signal)
template<typename NodeT >
auto create (const ParameterProvider &provider) -> std::unique_ptr< NodeT >
template<typename NodeT >
NodeAllocationParams createAllocationParams ()
template<typename NodeT >
auto createConstructorArguments ()
Create a tuple of constructor argument needed by the constructor of the passed node.
std::unique_ptr< Node > createNode (const dw::core::StringView &className, ParameterProvider &provider)
template<typename NodeT >
static ParameterCollectionDescriptor createParameterCollectionDescriptor ()
Create a parameter collection descriptor for a give node.
template<typename NodeT >
static PassCollectionDescriptor createPassCollectionDescriptor ()
Create a pass collection descriptor for a give node.
template<typename NodeT , PortDirection Direction, typename std::enable_if_t< Direction==PortDirection::INPUT, void > * = nullptr>
static PortCollectionDescriptor createPortCollectionDescriptor ()
template<typename T >
constexpr auto describeAbstractArrayParameter (dw::core::StringView const &&typeName, dw::core::StringView const &&parameterName, size_t arraySize)
template<typename T >
constexpr auto describeAbstractParameter (dw::core::StringView const &&typeName, dw::core::StringView const &&parameterName)
template<typename T , typename S , typename... MemberPointers>
constexpr auto describeArrayParameter (dw::core::StringView const &&typeName, dw::core::StringView const &&parameterName, size_t arraySize, const MemberPointers &&... memberPointers)
template<typename T , typename S , size_t ArraySize, typename... MemberPointers>
constexpr auto describeArrayParameterWithDefault (dw::core::StringView const &&typeName, dw::core::StringView const &&parameterName, std::array< T, ArraySize > defaultValue, const MemberPointers &&... memberPointers)
template<typename... Args>
constexpr auto describeConstructorArgument (const Args &&... args)
constexpr std::tuple describeConstructorArguments ()
template<typename Argument1T , typename Arg1 >
constexpr auto describeConstructorArguments (const Arg1 &&arg1)
template<typename Argument1T , typename Argument2T , typename Arg1 , typename Arg2 >
constexpr auto describeConstructorArguments (const Arg1 &&arg1, const Arg2 &&arg2)
template<typename Argument1T , typename Argument2T , typename Argument3T , typename Arg1 , typename Arg2 , typename Arg3 >
constexpr auto describeConstructorArguments (const Arg1 &&arg1, const Arg2 &&arg2, const Arg3 &&arg3)
template<typename Argument1T , typename Argument2T , typename Argument3T , typename Argument4T , typename Arg1 , typename Arg2 , typename Arg3 , typename Arg4 >
constexpr auto describeConstructorArguments (const Arg1 &&arg1, const Arg2 &&arg2, const Arg3 &&arg3, const Arg4 &&arg4)
template<typename Argument1T , typename Argument2T , typename Argument3T , typename Argument4T , typename Argument5T , typename Arg1 , typename Arg2 , typename Arg3 , typename Arg4 , typename Arg5 >
constexpr auto describeConstructorArguments (const Arg1 &&arg1, const Arg2 &&arg2, const Arg3 &&arg3, const Arg4 &&arg4, const Arg5 &&arg5)
template<typename Argument1T , typename Argument2T , typename Argument3T , typename Argument4T , typename Argument5T , typename Argument6T , typename Arg1 , typename Arg2 , typename Arg3 , typename Arg4 , typename Arg5 , typename Arg6 >
constexpr auto describeConstructorArguments (const Arg1 &&arg1, const Arg2 &&arg2, const Arg3 &&arg3, const Arg4 &&arg4, const Arg5 &&arg5, const Arg6 &&arg6)
template<typename EnumT >
constexpr auto describeEnumerator (dw::core::StringView const &&name, EnumT value)
Describe an enumerator.
template<typename EnumT , typename... Args>
constexpr auto describeEnumeratorCollection (Args const &&... args)
Describe the enumerators.
template<typename T , typename S , typename... MemberPointers>
constexpr auto describeIndexParameter (dw::core::StringView const &&typeName, dw::core::StringView const &&parameterName, const MemberPointers &&... memberPointers)
template<typename Node >
constexpr auto describeInputPorts ()
template<typename Node >
constexpr auto describeOutputPorts ()
template<typename T , typename S , typename... MemberPointers>
constexpr auto describeParameter (dw::core::StringView const &&typeName, dw::core::StringView const &&parameterName, const MemberPointers &&... memberPointers)
template<typename NodeT >
constexpr auto describeParameters ()
Get described parameters for the passed node.
template<typename T , typename S , typename... MemberPointers>
constexpr auto describeParameterWithDefault (dw::core::StringView const &&typeName, dw::core::StringView const &&parameterName, T defaultValue, const MemberPointers &&... memberPointers)
constexpr std::tuple< dw::core::StringView, dwProcessorType > describePass (dw::core::StringView const &&name, dwProcessorType processorType)
template<typename DependenciesT >
constexpr auto describePass (dw::core::StringView const &&name, dwProcessorType processorType, DependenciesT dependencies) -> std::tuple< dw::core::StringView, dwProcessorType, DependenciesT >
template<typename... Args>
constexpr auto describePassCollection (const Args &&... args)
template<typename... Args>
constexpr auto describePassDependencies (const Args &&... args) -> std::array< dw::core::StringView, sizeof...(Args)>
template<typename Node >
constexpr auto describePasses ()
Get described passes for the passed node.
template<typename PortType >
constexpr auto describePort (dw::core::StringView typeName, dw::core::StringView name, dw::core::StringView comment)
template<typename PortType >
constexpr auto describePort (dw::core::StringView typeName, dw::core::StringView name, PortBinding binding=PortBinding::OPTIONAL, dw::core::StringView comment=""_sv)
template<typename PortType , size_t ArraySize, typename std::enable_if_t< ArraySize !=0, void > * = nullptr>
constexpr auto describePortArray (dw::core::StringView typeName, dw::core::StringView name, dw::core::StringView comment)
template<typename PortType , size_t ArraySize, typename std::enable_if_t< ArraySize !=0, void > * = nullptr>
constexpr auto describePortArray (dw::core::StringView typeName, dw::core::StringView name, PortBinding binding=PortBinding::OPTIONAL, dw::core::StringView comment=""_sv)
template<typename... Args>
constexpr auto describePortCollection (Args &&... args)
template<typename Node , PortDirection Direction, typename std::enable_if_t< Direction==PortDirection::INPUT, void > * = nullptr>
constexpr auto describePorts ()
template<typename T , typename S , typename... MemberPointers>
constexpr auto describeUnnamedArrayParameter (dw::core::StringView const &&typeName, size_t arraySize, const MemberPointers &&... memberPointers)
template<typename T , typename S , typename... MemberPointers>
constexpr auto describeUnnamedParameter (dw::core::StringView const &&typeName, const MemberPointers &&... memberPointers)
template<typename Node , PortDirection Direction, size_t PortIndex>
constexpr size_t descriptorIndex ()
template<typename Node , PortDirection Direction, size_t DescriptorIndex>
constexpr bool descriptorPortArray ()
template<typename Node , PortDirection Direction, size_t DescriptorIndex>
constexpr PortBinding descriptorPortBinding ()
template<typename Node , PortDirection Direction, size_t DescriptorIndex>
constexpr dw::core::StringView descriptorPortComment ()
template<typename Node , PortDirection Direction, size_t DescriptorIndex>
constexpr size_t descriptorPortSize ()
MetadataPayload * extractMetadata (GenericData packet)
const PortCollectionDescriptor & getInputPorts (const dw::core::StringView &className)
dw::core::HeapVectorFixed< dw::core::StringView > getNodeNames ()
const PortCollectionDescriptor & getOutputPorts (const dw::core::StringView &className)
const ParameterCollectionDescriptor & getParameters (const dw::core::StringView &className)
const PassCollectionDescriptor & getPasses (const dw::core::StringView &className)
dw::core::Optional< dwTime_t > getTimestamp (ChannelMetadata const &header)
dw::core::Optional< dwValidityStatus > getValidityStatus (ChannelMetadata const &header)
template<typename Node , size_t Index>
constexpr bool hasPassDependencies ()
Check if a pass specifies explicit dependencies.
constexpr bool IsConsumer (ChannelRole role)
constexpr bool IsProducer (ChannelRole role)
template<typename Node >
constexpr bool isValidPass (dw::core::StringView identifier)
Check if given string is a valid pass name.
template<typename Node >
constexpr bool isValidPass (std::size_t passID)
Check if pass index is valid.
template<typename Node , PortDirection Direction>
constexpr bool isValidPortIdentifier (StringView identifier)
template<typename Node , PortDirection Direction>
constexpr bool isValidPortIndex (std::size_t portID)
template<typename T >
static GenericDataReference make_specimen (typename parameter_traits< T >::SpecimenT *specimen)
template<typename NodeT , class ConstructorArguments >
auto makeUniqueFromTuple (const ConstructorArguments &&constructorArguments) -> std::unique_ptr< NodeT >
Instantiate a node using the passed constructor arguments.
template<typename EnumT >
auto mapEnumNameToValue (dw::core::StringView const &name) -> EnumT
Get the enumerator value based on the name.
template<typename EnumT >
dw::core::StringView mapEnumValueToName (EnumT value)
Get the enumerator name based on the value.
const char * nvSciGetErrorName (uint32_t error)
const char * nvSciGetEventName (uint32_t event)
constexpr ChannelNvSciStreamEnabledComponents operator& (ChannelNvSciStreamEnabledComponents a, ChannelNvSciStreamEnabledComponents b)
constexpr ChannelNvSciStreamEnabledComponents operator| (ChannelNvSciStreamEnabledComponents a, ChannelNvSciStreamEnabledComponents b)
template<typename NodeT >
constexpr std::size_t parameterSize ()
Get the number of parameters for a given node.
template<typename... Others>
static void ParseAllChannelParameters (const ChannelParamStr &channelParams, Others &&... others)
template<typename T >
static T ParseChannelParameter (const ChannelParamStr &value)
template<>
int64_t ParseChannelParameter (const ChannelParamStr &value)
template<>
size_t ParseChannelParameter (const ChannelParamStr &value)
template<>
uint32_t ParseChannelParameter (const ChannelParamStr &value)
template<>
uint16_t ParseChannelParameter (const ChannelParamStr &value)
template<>
bool ParseChannelParameter (const ChannelParamStr &value)
template<>
ChannelRole ParseChannelParameter (const ChannelParamStr &value)
template<>
ChannelType ParseChannelParameter (const ChannelParamStr &value)
template<>
ChannelMode ParseChannelParameter (const ChannelParamStr &value)
template<size_t Size>
void ParseChannelParameter (const ChannelParamStr &value, dw::core::FixedString< Size > &result)
template<typename T , size_t N>
void ParseChannelParameter (const ChannelParamStr &value, dw::core::VectorFixed< T, N > &result)
template<typename T >
void ParseChannelParameter (const ChannelParamStr &value, T &result)
static void ParseChannelParameters (const ChannelParamStr &, const ChannelParamStr &)
template<typename T , typename... Others>
static void ParseChannelParameters (const ChannelParamStr &key, const ChannelParamStr &value, const char *staticKey, T &result, Others &&... others)
template<typename Node , size_t Index, typename std::enable_if_t< hasPassDependencies< Node, Index >(), void > * = nullptr>
constexpr auto passDependencies ()
Get the dependencies of a pass.
template<typename Node >
constexpr size_t passIndex (dw::core::StringView identifier)
Get the the pass index for a pass identified by name.
template<typename Node , size_t Index>
constexpr dw::core::StringView passName ()
Get the name of a pass.
template<typename Node , size_t Index>
constexpr dwProcessorType passProcessorType ()
Get the processor type of a pass.
template<typename Node >
constexpr std::size_t passSize ()
Get the number of passes of the passed node.
template<typename NodeT , class ConstructorArguments , typename std::enable_if_t< std::tuple_size< ConstructorArguments >()==1, void > * = nullptr>
void populateParameters (ConstructorArguments &constructorArguments, const ParameterProvider &provider)
Populate the constructor arguments using values from the parameter provider.
template<typename Node , PortDirection Direction>
constexpr size_t portArraySize (StringView identifier)
template<typename Node , PortDirection Direction>
constexpr size_t portDescriptorIndex (StringView identifier)
template<typename Node , PortDirection Direction>
constexpr std::size_t portDescriptorSize ()
template<typename Node , PortDirection Direction, size_t DescriptorIndex>
constexpr auto portDescriptorType ()
template<typename Node , PortDirection Direction>
constexpr size_t portIndex (StringView identifier)
template<typename Node , PortDirection Direction>
constexpr std::size_t portSize ()
template<typename Node , PortDirection Direction, size_t PortIndex>
constexpr auto portType ()
template<typename NodeT >
void registerNode (const char *className)
void setTimestamp (ChannelMetadata &header, dwTime_t const &timestamp)
void setValidityStatus (ChannelMetadata &header, dwValidityStatus const &status)
static const char * ToParam (ChannelType channelType)
Variables
uint32_t accumulatorDownsampleFactor
static constexpr char CALIBRATION_ACCEPTED_STATE_STRING [] = "accepted"
static constexpr char CALIBRATION_FAILED_STATE_STRING [] = "failed"
static constexpr char CALIBRATION_INVALID_STATE_STRING [] = "invalid"
static constexpr char CALIBRATION_NOT_ACCEPTED_STATE_STRING [] = "not-accepted"
char8_t const * calibrationOutputFileName
char8_t const * calibrationOverlayFileName
bool cameraSensorEnabled [framework::SELF_CALIBRATION_NODE_MAX_CAMERAS]
std::uint32_t cameraSensorRigIndices [framework::SELF_CALIBRATION_NODE_MAX_CAMERAS]
uint32_t channelMask
static constexpr dwTime_t CHN_WAIT_TIMEOUT_US = 50'000'000
cudaStream_t cudaStream
cupvaStream_t cupvastream
Data Type of pyramid.
cupvaStream_t cupvaStream
dwTrivialDataType dataType = dwTrivialDataType::DW_TYPE_FLOAT32
Number of levels in the pyramid.
bool diskIOStatsEnabled
static constexpr uint32_t DW_CALIBRATION_MAX_SENSORS = 64
dwFeature2DDetectorConfig dwDetectorParams
constexpr uint32_t DWFRAMEWORK_MAX_INTERNAL_TYPES = 0x400
constexpr uint32_t DWFRAMEWORK_METADATA_PACKET_TYPE_ID_OFFSET = 0x80000000
constexpr ChannelPacketTypeID DWFRAMEWORK_PACKET_ID_DEFAULT = 0U
const dw::core::StaticHashMap< dw::core::FixedString< 64 >, dwSerializationType, dwSerializationType::DW_TYPES_COUNT - 1 > dwSerializationTypeStringToEnumMap
dwFeature2DTrackerConfig dwTrackerParams
bool enable
bool enabled
dwTransformation3f extrinsic
bool fileBackendEnabled
dw::core::FixedString< 384 > filePath
bool ftraceBackendEnabled
bool fullMemUsage
uint32_t height
Width of level 0.
bool imuSensorEnabled [framework::SELF_CALIBRATION_NODE_MAX_IMUS]
std::uint32_t imuSensorRigIndices [framework::SELF_CALIBRATION_NODE_MAX_IMUS]
dwCameraModelHandle_t intrinsic
dw::core::FixedString< 16 > ipAddr
uint32_t levelCount
Height of level 0.
bool lidarICPUsesEgomotion
uint32_t lidarMaxICPIterations
dwLidarProperties lidarProps
bool lidarSensorEnabled [framework::SELF_CALIBRATION_NODE_MAX_LIDARS]
std::uint32_t lidarSensorRigIndices [framework::SELF_CALIBRATION_NODE_MAX_LIDARS]
uint32_t maskHeight
uint32_t maskStrideBytes
uint32_t maskWidth
static constexpr uint16_t MAX_CHANNEL_ALL_PARAMS_SIZE = 1024
static constexpr uint16_t MAX_CHANNEL_CONSUMERS_COUNT = 256
static constexpr uint16_t MAX_CHANNEL_PARAM_SIZE = 1024
static constexpr uint16_t MAX_CHANNEL_PRODUCERS_COUNT = 2048
static constexpr uint32_t MAX_INPUT_TRACE_PORTS = 16
static constexpr uint32_t MAX_LIDAR_STITCHER_PORT_NUM = 8
static constexpr size_t MAX_PORT_DESCRIPTOR_PER_COLLECTION {256U}
uint32_t maxFileSizeMB
uint32_t maxTracesPerChPerEpoch
bool memTraceEnabled
bool networkBackendEnabled
bool nvtxBackendEnabled
static constexpr size_t PARAMETER_ARRAY_SIZE {5U}
static constexpr size_t PARAMETER_CONSTRUCTOR_ARGUMENT_DESCRIPTOR {1U}
static constexpr size_t PARAMETER_CONSTRUCTOR_ARGUMENT_TYPE {0U}
static constexpr size_t PARAMETER_DEFAULT_VALUE {7U}
static constexpr size_t PARAMETER_IS_INDEX {4U}
static constexpr size_t PARAMETER_MEMBER_PTRS {6U}
static constexpr size_t PARAMETER_NAME {1U}
static constexpr size_t PARAMETER_SEMANTIC_TYPE {3U}
static constexpr size_t PARAMETER_TYPE {2U}
static constexpr size_t PARAMETER_TYPE_NAME {0U}
static constexpr size_t PASS_DEPENDENCIES {2U}
static constexpr size_t PASS_NAME {0U}
static constexpr size_t PASS_PROCESSOR_TYPE {1U}
static constexpr size_t PORT_ARRAY_SIZE {3U}
static constexpr size_t PORT_BINDING {4U}
static constexpr size_t PORT_COMMENT {5U}
static constexpr size_t PORT_NAME {1U}
static constexpr size_t PORT_TYPE {2U}
static constexpr size_t PORT_TYPE_NAME {0U}
bool radarSensorEnabled [framework::SELF_CALIBRATION_NODE_MAX_RADARS]
std::uint32_t radarSensorRigIndices [framework::SELF_CALIBRATION_NODE_MAX_RADARS]
dwRigHandle_t rigHandle
char8_t const * rigOutputFileName
static constexpr uint8_t SELF_CALIBRATION_NODE_MAX_CAMERAS = 13
static constexpr uint8_t SELF_CALIBRATION_NODE_MAX_IMUS = 3
static constexpr uint8_t SELF_CALIBRATION_NODE_MAX_LIDARS = 8
static constexpr uint8_t SELF_CALIBRATION_NODE_MAX_RADARS = 9
static constexpr uint8_t SELF_CALIBRATION_NODE_MAX_ROUTINE_COUNT
static constexpr uint8_t SELF_CALIBRATION_NODE_MAX_VEHICLEIO = 1
static constexpr uint8_t SELF_CALIBRATION_NODE_MAX_WHEELS = 4
static constexpr char SELF_CALIBRATION_TAG [] = "self-calibration"
uint32_t sensorIndex
uint16_t serverPort
cudaStream_t stream
static constexpr char SUPPORTS_EEPROM_INTRINSICS_TAG [] = "supports-eeprom-intrinsics"
static constexpr char SUPPORTS_EEPROM_INTRINSICS_TRUE_STRING [] = "true"
uint32_t tracingLevel
Class Documentation
dw::framework::BufferProperties
struct dw::framework::BufferProperties
Class Members
size_t byteSize
BufferFlags enabledBackends
dw::framework::ChannelEvent
struct dw::framework::ChannelEvent
Class Members
dwErrorSignal errorSignal The error signal. Only valid for type=ERROR.
OnDataReady onDataReady The callback set for the channel that is ready. Only valid for type=READY.
void * opaque The opaque pointer set for the channel tthat is ready. Only valid for type=READY.
ChannelEventType type The type of the event.
uint32_t uid unique identifier of the channel
dw::framework::ChannelMetadata
struct dw::framework::ChannelMetadata
Class Members
dwTime_t epochTimestamp
uint32_t iterationCount
uint32_t producerId
uint32_t sequenceNum
dwTime_t timestamp
uint16_t validFields
dwValidityStatus validityStatus
dw::framework::dwAccumulatorNodeParams
struct dw::framework::dwAccumulatorNodeParams
Class Members
dwPointCloudAssemblerParams assmParams
dwMotionCompensatorParams compParams
cudaStream_t cudaStream
dwEgomotionParameters egomotionParams
bool enableCuda
bool enableEgomotionCompensation
dwLidarProperties lidarProperties
bool throttlePipeline
dw::framework::dwCalibratedExtrinsics
struct dw::framework::dwCalibratedExtrinsics
Class Members
bool calibrationStateChanged
dwTransformation3f currentSensor2Rig
CalibrationExtrinsicProfileName extrinsicProfileName
dwCalibrationManeuverArray maneuvers
dwCalibrationSensorPositionState positionState
bool positionStateChanged
dwCalibrationProperties properties
dwCalibrationStatus status
dwTime_t timestamp
dw::framework::dwCalibratedIMUIntrinsics
struct dw::framework::dwCalibratedIMUIntrinsics
Class Members
dwVector3f accelerometerBias
dwVector3f gyroscopeBias
dwCalibrationManeuverArray maneuvers Required calibration maneuvers for accelerometer bias calibration.
dwCalibrationProperties properties Calibration properties for accelerometer bias calibration.
uint32_t sensorID
dwCalibrationStatus status Calibration status for accelerometer bias calibration.
bool validAccelerometerBias
bool validGyroscopeBias
dw::framework::dwCalibratedSteeringProperties
struct dw::framework::dwCalibratedSteeringProperties
Class Members
dwCalibrationManeuverArray maneuvers
dwCalibrationProperties properties
dwCalibrationStatus status
dwVehicleSteeringProperties steeringProperties
dw::framework::dwCalibratedWheelRadii
struct dw::framework::dwCalibratedWheelRadii
Class Members
float32_t currentWheelRadius[DW_VEHICLE_NUM_WHEELS]
dwCalibrationManeuverArray maneuvers
dwCalibrationProperties properties
dwCalibrationStatus status
dwTime_t timestamp
dw::framework::dwCameraIntrinsics
struct dw::framework::dwCameraIntrinsics
Class Members
dwFThetaCameraConfigNew intrinsics
CameraIntrinsicsSource intrinsicsSource
bool intrinsicsVerificationFailed
uint32_t sensorId
dw::framework::dwCodecMetadata
struct dw::framework::dwCodecMetadata
Class Members
dwCodecMimeType_t codecType
dwCodecConfigVideo configVideo
dw::framework::dwDetectorFovealParams
struct dw::framework::dwDetectorFovealParams
Class Members
bool fovealEnable
dwFovealMode fovealMode
dwRect ROI
dwVector2f scales
dw::framework::dwFeatureNccScores
struct dw::framework::dwFeatureNccScores
Class Members
float32_t * d_nccScores
uint32_t size
dw::framework::dwGlobalEgomotionNodeInitParams
struct dw::framework::dwGlobalEgomotionNodeInitParams
Class Members
const char * gpsSensorName
uint32_t historySize
dwConstRigHandle_t rigHandle
dw::framework::dwGPSNodeParams
struct dw::framework::dwGPSNodeParams
Class Members
FixedString< 32 > frameSkipMask
bool inputModeVal
dwConstRigHandle_t rigHandle
const char * sensorName
dw::framework::dwIMUNodeParams
struct dw::framework::dwIMUNodeParams
Class Members
FixedString< 32 > frameSkipMask
bool inputModeVal
dwConstRigHandle_t rigHandle
const char * sensorName
dw::framework::dwLatency
struct dw::framework::dwLatency
Class Members
uint8_t * data
uint64_t senderTime
size_t size
dw::framework::dwLidarPacketsArray
struct dw::framework::dwLidarPacketsArray
Class Members
size_t maxPacketsPerSpin
size_t maxPointsPerPacket
dwLidarDecodedPacket * packets
size_t packetSize
dwLidarPointRTHI * pointsRTHIArray
dwLidarPointXYZI * pointsXYZIArray
dw::framework::dwLidarPointCloudStitcherNodeParams
struct dw::framework::dwLidarPointCloudStitcherNodeParams
Class Members
bool enabledLidar[MAX_LIDAR_STITCHER_PORT_NUM]
dwTransformation3f lidar2RigDefault[MAX_LIDAR_STITCHER_PORT_NUM]
dwLidarProperties lidarProperties[MAX_LIDAR_STITCHER_PORT_NUM]
dwMemoryType memoryType
dwPointCloudFormat outputFormat
cudaStream_t stream
dw::framework::dwLidarPose
struct dw::framework::dwLidarPose
Class Members
dwTransformation3f pose
dwTime_t timeStampBefore
dwTime_t timeStampNow
dw::framework::dwPointCloudAccumulatorNodeParams
struct dw::framework::dwPointCloudAccumulatorNodeParams
Class Members
cudaStream_t cudaStream
dwEgomotionParameters egomotionParams
bool enableEgomotionCompensation
dwLidarProperties lidarProperties
dwPointCloudAccumulatorParams pointCloudAccuParams
bool throttlePipeline
dw::framework::dwRadarDopplerMotionNodeParams
struct dw::framework::dwRadarDopplerMotionNodeParams
Class Members
cudaStream_t cudaStream
bool enable
dw::framework::dwRelativeEgomotionIMUNodeInitParams
struct dw::framework::dwRelativeEgomotionIMUNodeInitParams
Class Members
bool automaticUpdate
bool enableSuspension
bool estimateInitialOrientation
uint32_t historySize
const char * imuSensorName
dwEgomotionLinearAccelerationFilterParams linearAccelerationFilterParameters
dwMotionModel motionModel
dwConstRigHandle_t rigHandle
dwEgomotionSpeedMeasurementType speedMeasurementType
const char * vehicleSensorName
dw::framework::dwRoadCastNodeCalibrationData
struct dw::framework::dwRoadCastNodeCalibrationData
Class Members
bool calibrationStateChanged
char extrinsicProfileName[DW_MAX_EXTRINSIC_PROFILE_NAME_SIZE]
dwCalibrationManeuverArray maneuvers
dwCalibrationSensorPositionState positionState
bool positionStateChanged
dwCalibrationProperties properties
char sensorName[DW_MAX_RIG_SENSOR_NAME_SIZE]
dwTransformation3f sensorToRig
dwCalibrationStatus status
dwTime_t timestamp
dw::framework::dwRoadCastNodeCalibrationDataArray
struct dw::framework::dwRoadCastNodeCalibrationDataArray
Class Members
dwRoadCastNodeCalibrationData calibrationData[DW_CALIBRATION_MAX_SENSORS]
uint32_t count
dw::framework::dwRoadCastNodeCalibrationWheelRadiiData
struct dw::framework::dwRoadCastNodeCalibrationWheelRadiiData
Class Members
dwCalibrationManeuverArray maneuvers
dwCalibrationProperties properties
dwCalibrationStatus status
dwTime_t timestamp
float32_t wheelRadii[DW_VEHICLE_NUM_WHEELS]
dw::framework::dwSelfCalibrationNodeCameraParams
struct dw::framework::dwSelfCalibrationNodeCameraParams
Class Members
uint32_t calibrationMethod
uint32_t calibrationSignals
dwCameraModelHandle_t cameraHandle
dwCameraProperties cameraProps
cudaStream_t cudaStream
bool sensorEnabledCalibrationMask
bool sensorEnabledGlobally
uint32_t sensorIndex
uint32_t trackerMaxFeatureCount
uint32_t trackerMaxHistorySize
dw::framework::dwSelfCalibrationNodeLidarParams
struct dw::framework::dwSelfCalibrationNodeLidarParams
Class Members
cudaStream_t cudaStream
dwLidarProperties lidarProps
bool sensorEnabledCalibrationMask
bool sensorEnabledGlobally
uint32_t sensorIndex
dw::framework::dwSelfCalibrationNodeParam
struct dw::framework::dwSelfCalibrationNodeParam
Class Members
uint32_t accumulatorDownsampleFactor
int32_t calibrateOdometryPropertyRadar
bool calibrateVehicle
dwSelfCalibrationNodeCameraParams cameraParams[SELF_CALIBRATION_NODE_MAX_CAMERAS]
uint32_t channelFifoSize
bool enforceDependencies
bool lidarHandEyeUsesEgomotion
uint32_t lidarMaxICPIterations
dwSelfCalibrationNodeLidarParams lidarParams[SELF_CALIBRATION_NODE_MAX_LIDARS]
dwSelfCalibrationNodeRadarParams radarParams[SELF_CALIBRATION_NODE_MAX_RADARS]
dwRigHandle_t rigHandle
dw::framework::dwSelfCalibrationNodeRadarParams
struct dw::framework::dwSelfCalibrationNodeRadarParams
Class Members
cudaStream_t cudaStream
uint32_t maxDisplayPoints
dwRadarProperties radarProps
bool sensorEnabledCalibrationMask
bool sensorEnabledGlobally
uint32_t sensorIndex
dw::framework::dwSelfCalibrationRoadcastAggregatorNodeParam
struct dw::framework::dwSelfCalibrationRoadcastAggregatorNodeParam
Class Members
uint32_t cameraSensorRigIndices[SELF_CALIBRATION_NODE_MAX_CAMERAS]
uint32_t imuSensorRigIndices[SELF_CALIBRATION_NODE_MAX_IMUS]
uint32_t lidarSensorRigIndices[SELF_CALIBRATION_NODE_MAX_LIDARS]
uint32_t radarSensorRigIndices[SELF_CALIBRATION_NODE_MAX_RADARS]
dwRigHandle_t rigHandle
dw::framework::dwSelfCalibrationSingleIMUNodeParam
struct dw::framework::dwSelfCalibrationSingleIMUNodeParam
Class Members
uint32_t channelFifoSize
bool enableCalibration
dwRigHandle_t rigHandle TODO(lmoltrecht): AVC-2329 Use dwConstRigHandle_t because it's not modified from this node.
dw::framework::dwSensorDrainerParams
struct dw::framework::dwSensorDrainerParams
Class Members
bool autoReset
dwTime_t blockingTimeout
bool drainStaleData
const char * frameReadMask
bool isLockstep
bool isVirtual
const char * nodeName
dwTime_t nonBlockingTimeout
bool waitForNewData
dw::framework::dwSensorNodeProperties
struct dw::framework::dwSensorNodeProperties
Class Members
dwCalibratedExtrinsics extrinsics
uint32_t sensorId
dw::framework::dwSensorNodeRawData
struct dw::framework::dwSensorNodeRawData
Class Members
uint8_t * data
size_t size
dw::framework::dwTraceNodeData
struct dw::framework::dwTraceNodeData
Class Members
uint8_t * data
size_t dataSize
size_t maxDataSize
dw::framework::GenericDataReference
struct dw::framework::GenericDataReference
Class Members
GenericData data GenericData pointing to packet constructor parameters.
ChannelPacketTypeID packetTypeID The ID of the type of the endpoint.
shared_ptr< void > pCopy a shared pointer to packet constructor parameters.
OnSetSyncAttrs setSignalerAttributes lambda to set the signaler attributes of the endpoint.
OnSetSyncAttrs setWaiterAttributes lambda to set the waiter attributes of the endpoint.
size_t typeSize The size of the type of the endpoint.
dw::framework::GPSNodeChannelParams
struct dw::framework::GPSNodeChannelParams
Class Members
FixedString< 32 > frameSkipMask
dwConstRigHandle_t rigHandle
const char * sensorName
dw::framework::IMUNodeChannelParams
struct dw::framework::IMUNodeChannelParams
Class Members
FixedString< 32 > frameSkipMask
dwConstRigHandle_t rigHandle
const char * sensorName
dw::framework::MetadataPayload
struct dw::framework::MetadataPayload
Class Members
GenericData data
ChannelMetadata header
dw::framework::NodeAllocationParams
struct dw::framework::NodeAllocationParams
Class Members
size_t maxInputPortCount
size_t maxOutputPortCount
size_t maxPassCount
dw::framework::packet_traits
struct dw::framework::packet_traits
dw::framework::SensorServiceNodeRawData
struct dw::framework::SensorServiceNodeRawData
Class Members
uint8_t * data
size_t size
dw::framework::VehicleStateNodeNewParams
struct dw::framework::VehicleStateNodeNewParams
Class Members
bool actuationFeedback
FixedString< 32 > frameSkipMask
bool noneSafetyState
dwConstRigHandle_t rigHandle
bool safetyState
const char * sensorName
bool vioStateRcEnabled
dw::framework::VehicleStateNodeParams
struct dw::framework::VehicleStateNodeParams
Class Members
bool external
FixedString< 32 > frameSkipMask
bool legacyExternal
bool legacyInternal
dwConstRigHandle_t rigHandle
const char * sensorName
bool vioStateRcEnabled
Typedef Documentation
BufferFlags
using dw::framework::BufferFlags = typedef uint32_t
Definition at line 51 of file Buffer.hpp.
CalibrationExtrinsicProfileName
using dw::framework::CalibrationExtrinsicProfileName = typedef dw::core::FixedString<DW_MAX_EXTRINSIC_PROFILE_NAME_SIZE>
Definition at line 78 of file SelfCalibrationTypes.hpp.
CalibrationIntrinsicsString
using dw::framework::CalibrationIntrinsicsString = typedef dw::core::FixedString<64>
Definition at line 77 of file SelfCalibrationTypes.hpp.
CalibrationResultsString
using dw::framework::CalibrationResultsString = typedef dw::core::FixedString<512>
Definition at line 76 of file SelfCalibrationTypes.hpp.
ChannelPacketConstructor
using dw::framework::ChannelPacketConstructor = typedef dw::core::Function<std::unique_ptr<IChannelPacket>(GenericData dataSpecimen, dwContextHandle_t context)>
Definition at line 44 of file ChannelFactory.hpp.
ChannelPacketConstructorRegistration
using dw::framework::ChannelPacketConstructorRegistration = typedef std::pair<ChannelPacketConstructorSignature, ChannelPacketConstructor>
Definition at line 46 of file ChannelFactory.hpp.
ChannelPacketConstructorSignature
using dw::framework::ChannelPacketConstructorSignature = typedef std::pair<ChannelPacketTypeID, ChannelType>
Definition at line 45 of file ChannelFactory.hpp.
ChannelPacketFactoryPtr
using dw::framework::ChannelPacketFactoryPtr = typedef std::shared_ptr<IChannelPacketFactory>
Definition at line 223 of file IChannelPacket.hpp.
ChannelPacketTypeID
using dw::framework::ChannelPacketTypeID = typedef uint32_t
The unique id specifying how a data type should be allocated and transported. This id is used to verify that remote peers are expecting the same data type over a connection.
Definition at line 172 of file ChannelPacketTypes.hpp.
ChannelParamStr
using dw::framework::ChannelParamStr = typedef dw::core::FixedString<MAX_CHANNEL_PARAM_SIZE>
Definition at line 115 of file ChannelParameters.hpp.
ChannelType
using dw::framework::ChannelType = typedef enum ChannelType : uint8_t { DW_CHANNEL_TYPE_SHMEM_LOCAL = 0, DW_CHANNEL_TYPE_SHMEM_REMOTE = 1, DW_CHANNEL_TYPE_EGLSTREAM = 2, DW_CHANNEL_TYPE_SOCKET = 3, DW_CHANNEL_TYPE_DDS = 4, DW_CHANNEL_TYPE_NVSCI = 5, }
The backend transport type of a Channel
Definition at line 51 of file ChannelParameters.hpp.
CycleCountFetcher
using dw::framework::CycleCountFetcher = typedef dw::core::Function<uint32_t(void)>
Definition at line 42 of file SyncPortHelper.hpp.
dwFeatureDetectorNodeParams
using dw::framework::dwFeatureDetectorNodeParams = typedef dwFeatureDetectorNodeParams { bool initForCamera
Definition at line 61 of file dwFeatureDetectorNode.hpp.
dwFeatureDetectorNodeRuntimeParams
using dw::framework::dwFeatureDetectorNodeRuntimeParams = typedef dwFeatureDetectorNodeRuntimeParams { uint8_t* d_mask
Definition at line 51 of file dwFeatureDetectorNode.hpp.
dwFeatureTrackerNodeParams
using dw::framework::dwFeatureTrackerNodeParams = typedef dwFeatureTrackerNodeParams { bool initForCamera
Definition at line 53 of file dwFeatureTrackerNode.hpp.
dwIcpNodeParams
using dw::framework::dwIcpNodeParams = typedef dwIcpNodeParams { dwRigHandle_t rigHandle
Definition at line 51 of file dwIcpNode.hpp.
dwPyramidNodeParams
using dw::framework::dwPyramidNodeParams = typedef dwPyramidNodeParams { uint32_t width
Definition at line 53 of file dwPyramidNode.hpp.
dwRigNodeParams
using dw::framework::dwRigNodeParams = typedef dwRigNodeParams { bool serialization
Definition at line 51 of file dwRigNode.hpp.
dwTraceCollectorNodeParams
using dw::framework::dwTraceCollectorNodeParams = typedef dwTraceCollectorNodeParams { bool stmControlTracing
Definition at line 48 of file dwTraceCollectorNode.hpp.
dwTraceNodeParams
using dw::framework::dwTraceNodeParams = typedef dwTraceNodeParams { bool stmControlTracing
Definition at line 46 of file dwTraceNode.hpp.
OnSetSyncAttrs
using dw::framework::OnSetSyncAttrs = typedef dw::core::Function<void(NvSciSyncAttrList)>
Function signature to call back to the application to set the sync attributes when needed.
Definition at line 244 of file ChannelPacketTypes.hpp.
UniquePacketPtr
template<typename T > using dw::framework::UniquePacketPtr = typedef typename ManagedPortInput<T>::UniquePacketPtr
Definition at line 563 of file ManagedPort.hpp.
Enumeration Type Documentation
BufferBackendType
enum class dw::framework::BufferBackendType : uint32_t strong
Enumerator
CPU
CUDA
Definition at line 44 of file Buffer.hpp.
CameraIntrinsicsSource
enum class dw::framework::CameraIntrinsicsSource strong
Enumerator
RIG
EEPROM
Definition at line 53 of file SensorCommonTypes.hpp.
ChannelConnectionType
enum class dw::framework::ChannelConnectionType strong
Enumerator
CONNECTION_TYPE_NONE
CONNECTION_TYPE_STATIC
CONNECTION_TYPE_DYNAMIC
Definition at line 143 of file ChannelParameters.hpp.
ChannelEventType
enum class dw::framework::ChannelEventType strong
Enumerator
CONNECTED
Channel became connected.
DISCONNECTED
Channel became disconnected.
ERROR
Channel encountered error.
READY
Channel is ready.
Definition at line 50 of file ChannelFactory.hpp.
ChannelMode
enum class dw::framework::ChannelMode strong
Enumerator
FIFO
MAILBOX
SINGLETON
Definition at line 117 of file ChannelParameters.hpp.
ChannelNvSciStreamEnabledComponents
enum class dw::framework::ChannelNvSciStreamEnabledComponents : uint32_t strong
Enumerator
COMPONENT_NONE
COMPONENT_CPU
COMPONENT_EGL
COMPONENT_CUDA
COMPONENT_PVA
COMPONENT_DLA
COMPONENT_NVMEDIA
Definition at line 130 of file ChannelParameters.hpp.
ChannelReach
enum class dw::framework::ChannelReach strong
Enumerator
REACH_NONE
REACH_THREAD
REACH_PROCESS
REACH_VM
REACH_CHIP
Definition at line 153 of file ChannelParameters.hpp.
ChannelRole
enum class dw::framework::ChannelRole : uint8_t strong
The roles a channel allows.
Enumerator
DW_CHANNEL_ROLE_PRODUCER
allows producer only
DW_CHANNEL_ROLE_CONSUMER
allows consumer only
DW_CHANNEL_ROLE_COMPOSITE
allows both producer and consumer
Definition at line 93 of file ChannelParameters.hpp.
DWChannelPacketTypeID
enum class dw::framework::DWChannelPacketTypeID strong
Enumerator
DEFAULT
NUM_TYPES
Definition at line 209 of file ChannelPacketTypes.hpp.
dwFovealMode
enum class dw::framework::dwFovealMode strong
Enumerator
OFF
FULL
INTERLEAVED
Definition at line 42 of file DetectorTypes.hpp.
dwModeDnnROI
enum class dw::framework::dwModeDnnROI strong
ROI mode for detector input from original input image. Horizontal rows of the input image may differ based on FPS setting.
30fps: 1920x1208, use MIDDLE as default
36fps: 1920x1008, use BOTTOM as default
Enumerator
TOP
MIDDLE
BOTTOM
Definition at line 53 of file DetectorTypes.hpp.
dwSerializationType
enum dw::framework::dwSerializationType
Enumerator
DW_TYPE_INVALID
DW_ACTUATION_SUPERVISOR_STATUS
DW_ACTUATED_REPLAY_STATUS
DW_ADAS_OBJECT_ARRAY
DW_AEB_REQUEST
DW_AEB_STATE_INFO
DW_AV_STATS
DW_AV_CONFIG
DW_BEHAVIOR_PLANNER_ACC_INFO
DW_BEHAVIOR_PLANNER_LANE_CHANGE_INFO
DW_BEHAVIOR_PLANNER_LANE_HANDLE_INFO
DW_BEHAVIOR_PLANNER_MERGE_INFO
DW_BEHAVIOR_PLANNER_WAIT_ELEMENT_INFO
DW_BEHAVIOR_PLANNER_DEBUG_INFO
DW_TRAJECTORY_PLANNER_DEBUG_INFO
DW_BEHAVIOR_PLANNER_EVALUATION_RESULTS
DW_CALIBRATED_STEER_OFFSET
DW_CALIBRATED_WHEEL_RADII
DW_BLINDNESS_DETECTION_OUTPUT
DW_CALIBRATION
DW_COMMAND_TO_CONTROL
DW_CUBOID_3D
DW_CVIP_LIST
DW_DISENGAGEMENT_DATA
DW_EGOMOTION_RESULT_PAYLOAD
DW_EGOMOTION_STATE_HANDLE
DW_EGOMOTION_POSE_PAYLOAD
DW_ENCODED_FRAME
DW_EVENT_FLAG
DW_EVENT_SURVEY
DW_FEATURE_NCC_SCORES
DW_FEATURE_ARRAY
DW_FEATURE_HISTORY_ARRAY
DW_FREESPACE_DETECTION
DW_GLOBAL_EGOMOTION_RESULT_PAYLOAD
DW_GLOBAL_EGOMOTION_STATE
DW_GPS_FRAME
DW_HEARTBEAT
DW_IMAGE_HANDLE
DW_IMU_FRAME
DW_INTERSECTION_ARRAY
DW_INTERSECTION_DETECTION
DW_KPI_STATUS
DW_LANE_ARRAY
DW_LANE_ASSIGNMENT_ARRAY
DW_LANE_CHUNK_ARRAY
DW_LANE_DETECTION
DW_LANE_GRAPH
DW_LANE_GRAPH_LIST
DW_LANE_GRAPH_WORLD_MODEL
DW_LANE_PLAN_ACTIONS
DW_LANE_PLAN_ACTIONS_NEW
DW_LANE_SUPPORT_STATUS
DW_LANDMARK_DETECTION
DW_DASHMARK_DETECTION
DW_ROADMARK_DETECTION
DW_EGO_LANE_BIASING_INFO
DW_ROAD_SEPARATION
DW_CAMERA_VISIBILITY
DW_LIGHT_SOURCE_PERCEPTION_AUTO_BEAM_STATUS
DW_LIGHT_SOURCE_PERCEPTION_DETECTOR_MASK
DW_LIGHT_FUNCTIONS_DATA
DW_LIDAR_DECODED_PACKET
DW_LSS_REQUEST
DW_LDW_HMI_REQUEST
DW_LOCALIZATION_RESULT
DW_LOCALIZATIONNAVMAP_RESULT
DW_LOGIN_SURVEY
DW_MSG_VERSION
DW_OBJECT_ARRAY
DW_OBJECT_CAMERA
DW_OBJECT_DETECTION
DW_OBJECT_FUSED
DW_OBJECT_GENERIC
DW_OBJECT_HISTORY_ARRAY
DW_OBJECT_LIDAR
DW_OBJECT_RADAR
DW_OBJECT_ARRAY_RADARDNN
DW_OBSTACLE
DW_OBSTACLE_ARRAY
DW_OBSTACLE_LINK_ARRAY
DW_OBSTACLE_RDM
DW_OBSTACLE_RDM_RADARDNN
DW_PATH
DW_PATH_DETECTION
DW_PERCEPTION_OBJECT
DW_PYRAMID_IMAGE
DW_POINT_CLOUD
DW_RADAR_DOPPLER_MOTION
DW_RADAR_SCAN
DW_RADAR_TRACK_EXTENDED
DW_RADAR_GRID_RADAR_OBSTACLES
DW_RESIM_CONFIG
DW_RESIM_FAILURE
DW_RESIM_LOG
DW_RESIM_METADATA_LOG
DW_RESIM_SEGMENT_LOG
DW_SAFETY_FORCE_FIELD_METRIC
DW_SAFETY_FORCE_FIELD_STATE
DW_MATCHED_ROUTE
DW_LARGE_LANE_GRAPH_REWARD_ARRAY
DW_LARGE_LANE_GRAPH_LINK_ARRAY
DW_SENSOR_NODE_RAW_DATA
DW_STRATEGY_HEALTH_STATE
DW_SURROUND_MONITOR_RADAR_STATE
DW_SURROUND_MONITOR_LANECHANGE_SAFEDECISION
DW_RADAR_PERCEPTION_RADAR_STATE
DW_SURVEY_REQUEST
DW_TEXT
DW_TELEMETRY_SESSION
DW_TEMPORAL_FUSION_DEBUG_INFO
DW_PARKING_PLANNER_DEBUG_INFO
DW_TIME
DW_TIME_SERIES
DW_TIME_SERIES_ARRAY
DW_HEALTH_SIGNAL_ARRAY
DW_GRAPH_HEALTH_SIGNAL
DW_ERROR_SIGNAL
DW_GRAPH_ERROR_SIGNAL
DW_TRAFFIC_SIGNAL_OBJECT_LIST
DW_TRANSFORMATION_PAYLOAD
DW_TSLOBJECTS
DW_VEHICLE_CALIBRATION
DW_VEHICLE_CONTROL_KPI
DW_VEHICLE_CONTROL_STATUS
DW_VEHICLE_IO_STATE
DW_VEHICLE_COMMAND
DW_VEHICLE_MISC_COMMAND
DW_WAIT_GROUP_ARRAY
DW_WAIT_ELEMENT_GROUP
DW_WAIT_ELEMENT_GROUPS
DW_WAIT_LINE_ARRAY
DW_DEPTH_IMAGE
DW_CAMERA_PROPERTIES
DW_CAMERA_MODEL_TRANSFORM_PARAM
DW_SPEEDLIMIT_ARRAY
DW_SPEEDLIMIT_LANE_ASSOCIATION_ARRAY
DW_SPEEDLIMIT_WORLD_MODEL
DW_SPEEDLIMIT_POSITIONAL_ARRAY
DW_SPEEDLIMIT_ATTRIBUTES_ARRAY
DW_TSA_PLANNER_HMI_REQUEST
DW_BLIND_SPOT_MONITOR_STATE_INFO
DW_TSA_PLANNER_STATE_INFO
DW_NEAR_FIELD_ASSIST_STATE_INFO
DW_WAIT_ELEMENT_ARRAY
DW_PREDICTED_TRAJECTORIES
DW_PARKING_SPACE_ARRAY
DW_CODEC_PACKET
DW_SENSOR_SERVICE_RAW_DATA
DW_SENSOR_TS_AND_ID
DW_AUTO_EMERGENCY_STEERING_REQUEST
DW_RECORDED_PATH
FLOAT32
DW_LANE_ASSIGNMENT_DEBUG_INFO
DW_OBJECT_FUSION_RUN_METADATA
DW_TRAFFIC_LIGHTS_ARRAY
DW_TEXT_REGION_ARRAY
DW_WC_VIEW_LINE_3D_ARRAY
DW_MPPSELECTOROUTPUT
DW_LANE_CURVATURE_INFO
DW_TRAFFIC_LIGHT_ASSOCIATION_ARRAY
DW_ROADPROFILEDATA
DW_TYPES_COUNT
Definition at line 41 of file Types.hpp.
MetadataFlags
enum class dw::framework::MetadataFlags : uint16_t strong
Enumerator
METADATA_ITERATION_COUNT
METADATA_EPOCH_TIMESTAMP
METADATA_VALIDITY_STATUS
METADATA_TIMESTAMP
Definition at line 216 of file ChannelPacketTypes.hpp.
PortBinding
enum class dw::framework::PortBinding : uint8_t strong
Enumerator
OPTIONAL
REQUIRED
Definition at line 76 of file PortDescriptor.hpp.
PortDirection
enum class dw::framework::PortDirection : uint8_t strong
Enumerator
INPUT
OUTPUT
COUNT
Definition at line 51 of file Port.hpp.
Function Documentation
BufferFlagsBackendEnabled()
bool dw::framework::BufferFlagsBackendEnabled (BufferFlags flags, BufferBackendType type) inline
Definition at line 53 of file Buffer.hpp.
BufferFlagsEnableBackend()
void dw::framework::BufferFlagsEnableBackend (BufferFlags & flags, BufferBackendType type) inline
Definition at line 58 of file Buffer.hpp.
checkHeaderValidFlag()
bool dw::framework::checkHeaderValidFlag (ChannelMetadata const & header, MetadataFlags flag)
convertToGraphErrorSignal()
dwGraphErrorSignal dw::framework::convertToGraphErrorSignal (dwErrorSignal const & signal)
convertToGraphHealthSignal()
dwGraphHealthSignal dw::framework::convertToGraphHealthSignal (const dwHealthSignal & signal)
create()
template<typename NodeT > auto dw::framework::create (const ParameterProvider & provider) -> std::unique_ptr<NodeT>
Instantiate a node using parameters from the passed provider.
Syntactic sugar chaining the following calls:
createConstructorArguments()
populateParameters()
makeUniqueFromTuple()
Definition at line 1008 of file ParameterDescriptor.hpp.
createAllocationParams()
template<typename NodeT > NodeAllocationParams dw::framework::createAllocationParams ()
Definition at line 65 of file SimpleNode.hpp.
References dw::framework::NodeAllocationParams::maxInputPortCount, dw::framework::NodeAllocationParams::maxOutputPortCount, and dw::framework::NodeAllocationParams::maxPassCount.
createConstructorArguments()
template<typename NodeT > auto dw::framework::createConstructorArguments ()
Create a tuple of constructor argument needed by the constructor of the passed node.
Definition at line 972 of file ParameterDescriptor.hpp.
createNode()
std::unique_ptr< Node > dw::framework::createNode (const dw::core::StringView & className, ParameterProvider & provider)
createParameterCollectionDescriptor()
template<typename NodeT > static ParameterCollectionDescriptor dw::framework::createParameterCollectionDescriptor () static
Create a parameter collection descriptor for a give node.
Definition at line 294 of file ParameterCollectionDescriptor.hpp.
References dw::framework::ParameterCollectionDescriptor::addDescriptors().
createPassCollectionDescriptor()
template<typename NodeT > static PassCollectionDescriptor dw::framework::createPassCollectionDescriptor () static
Create a pass collection descriptor for a give node.
Definition at line 159 of file PassCollectionDescriptor.hpp.
createPortCollectionDescriptor()
template<typename NodeT , PortDirection Direction, typename std::enable_if_t< Direction==PortDirection::INPUT, void > * = nullptr> static PortCollectionDescriptor dw::framework::createPortCollectionDescriptor () static
Definition at line 158 of file PortCollectionDescriptor.hpp.
describeAbstractArrayParameter()
template<typename T > constexpr auto dw::framework::describeAbstractArrayParameter (dw::core::StringView const && typeName, dw::core::StringView const && parameterName, size_t arraySize) constexpr
Describe an abstract array parameter.
The values aren't stored anywhere automatically but the nodes create() function should retrieve the parameters from the provider and use custom logic to use the values.
Definition at line 332 of file ParameterDescriptor.hpp.
describeAbstractParameter()
template<typename T > constexpr auto dw::framework::describeAbstractParameter (dw::core::StringView const && typeName, dw::core::StringView const && parameterName) constexpr
Describe an abstract parameter.
The value isn't stored anywhere automatically but the nodes create() function should retrieve the parameter from the provider and use custom logic to use the value.
Definition at line 314 of file ParameterDescriptor.hpp.
describeArrayParameter()
template<typename T , typename S , typename... MemberPointers> constexpr auto dw::framework::describeArrayParameter (dw::core::StringView const && typeName, dw::core::StringView const && parameterName, size_t arraySize, const MemberPointers &&... memberPointers) constexpr
Describe an array parameter.
Regarding the member pointers see describeParameter().
Definition at line 393 of file ParameterDescriptor.hpp.
describeArrayParameterWithDefault()
template<typename T , typename S , size_t ArraySize, typename... MemberPointers> constexpr auto dw::framework::describeArrayParameterWithDefault (dw::core::StringView const && typeName, dw::core::StringView const && parameterName, std::array< T, ArraySize > defaultValue, const MemberPointers &&... memberPointers) constexpr
Describe an array parameter with a default value.
See describeArrayParameter().
Definition at line 509 of file ParameterDescriptor.hpp.
describeConstructorArgument()
template<typename... Args> constexpr auto dw::framework::describeConstructorArgument (const Args &&... args) constexpr
Describe a specific constructor argument of a node.
The function is used to create the arguments for describeConstructorArguments(). Each argument of the function is created by one of the describe parameter functions below.
Definition at line 230 of file ParameterDescriptor.hpp.
Referenced by dw::framework::dwLidarPointCloudAccumulatorNode::describeParameters(), dw::framework::dwLidarPointCloudStitcherNode::describeParameters(), dw::framework::dwRadarDopplerMotionNode::describeParameters(), dw::framework::dwRigNode::describeParameters(), dw::framework::dwTraceCollectorNode::describeParameters(), dw::framework::dwTraceNode::describeParameters(), dw::framework::dwGlobalEgomotionNode::describeParameters(), dw::framework::dwRelativeEgomotionIMUNode::describeParameters(), dw::framework::dwFeatureDetectorNode::describeParameters(), dw::framework::dwFeatureDetectorPVANode::describeParameters(), dw::framework::dwFeatureTrackerNode::describeParameters(), dw::framework::dwFeatureTrackerPVANode::describeParameters(), dw::framework::dwPyramidNode::describeParameters(), dw::framework::dwPyramidPVANode::describeParameters(), dw::framework::dwPointCloudAccumulatorNode::describeParameters(), dw::framework::dwIcpNode::describeParameters(), dw::framework::dwSelfCalibrationNode::describeParameters(), dw::framework::dwSelfCalibrationRoadcastAggregatorNode::describeParameters(), dw::framework::dwSelfCalibrationSingleIMUNode::describeParameters(), dw::framework::dwCameraNode::describeParameters(), dw::framework::dwGPSChannelNode::describeParameters(), dw::framework::dwGPSNode::describeParameters(), dw::framework::dwIMUChannelNode::describeParameters(), dw::framework::dwIMUNode::describeParameters(), dw::framework::dwLidarBatchNode::describeParameters(), dw::framework::dwLidarNode::describeParameters(), dw::framework::dwRadarChannelNode::describeParameters(), dw::framework::dwRadarNode::describeParameters(), dw::framework::dwUltrasonicChannelNode::describeParameters(), dw::framework::dwUltrasonicNode::describeParameters(), dw::framework::dwVehicleStateChannelNewNode::describeParameters(), dw::framework::dwVehicleStateChannelNode::describeParameters(), and dw::framework::dwVehicleStateNode::describeParameters().
describeConstructorArguments() [1/7]
constexpr std::tuple dw::framework::describeConstructorArguments () constexpr
Describe the constructor arguments of a node.
The function is used to implement NodeConcept::describeParameters(). Each argument of the function is created by describeConstructorArgument().
Definition at line 58 of file ParameterDescriptor.hpp.
Referenced by dw::framework::dwLidarPointCloudAccumulatorNode::describeParameters(), and dw::framework::dwPointCloudAccumulatorNode::describeParameters().
describeConstructorArguments() [2/7]
template<typename Argument1T , typename Arg1 > constexpr auto dw::framework::describeConstructorArguments (const Arg1 && arg1) constexpr
Describe the constructor arguments of a node.
The function is used to implement NodeConcept::describeParameters(). Each argument of the function is created by describeConstructorArgument().
Definition at line 74 of file ParameterDescriptor.hpp.
describeConstructorArguments() [3/7]
template<typename Argument1T , typename Argument2T , typename Arg1 , typename Arg2 > constexpr auto dw::framework::describeConstructorArguments (const Arg1 && arg1, const Arg2 && arg2) constexpr
Describe the constructor arguments of a node.
The function is used to implement NodeConcept::describeParameters(). Each argument of the function is created by describeConstructorArgument().
Definition at line 93 of file ParameterDescriptor.hpp.
describeConstructorArguments() [4/7]
template<typename Argument1T , typename Argument2T , typename Argument3T , typename Arg1 , typename Arg2 , typename Arg3 > constexpr auto dw::framework::describeConstructorArguments (const Arg1 && arg1, const Arg2 && arg2, const Arg3 && arg3) constexpr
Describe the constructor arguments of a node.
The function is used to implement NodeConcept::describeParameters(). Each argument of the function is created by describeConstructorArgument().
Definition at line 115 of file ParameterDescriptor.hpp.
describeConstructorArguments() [5/7]
template<typename Argument1T , typename Argument2T , typename Argument3T , typename Argument4T , typename Arg1 , typename Arg2 , typename Arg3 , typename Arg4 > constexpr auto dw::framework::describeConstructorArguments (const Arg1 && arg1, const Arg2 && arg2, const Arg3 && arg3, const Arg4 && arg4) constexpr
Describe the constructor arguments of a node.
The function is used to implement NodeConcept::describeParameters(). Each argument of the function is created by describeConstructorArgument().
Definition at line 140 of file ParameterDescriptor.hpp.
describeConstructorArguments() [6/7]
template<typename Argument1T , typename Argument2T , typename Argument3T , typename Argument4T , typename Argument5T , typename Arg1 , typename Arg2 , typename Arg3 , typename Arg4 , typename Arg5 > constexpr auto dw::framework::describeConstructorArguments (const Arg1 && arg1, const Arg2 && arg2, const Arg3 && arg3, const Arg4 && arg4, const Arg5 && arg5) constexpr
Describe the constructor arguments of a node.
The function is used to implement NodeConcept::describeParameters(). Each argument of the function is created by describeConstructorArgument().
Definition at line 168 of file ParameterDescriptor.hpp.
describeConstructorArguments() [7/7]
template<typename Argument1T , typename Argument2T , typename Argument3T , typename Argument4T , typename Argument5T , typename Argument6T , typename Arg1 , typename Arg2 , typename Arg3 , typename Arg4 , typename Arg5 , typename Arg6 > constexpr auto dw::framework::describeConstructorArguments (const Arg1 && arg1, const Arg2 && arg2, const Arg3 && arg3, const Arg4 && arg4, const Arg5 && arg5, const Arg6 && arg6) constexpr
Describe the constructor arguments of a node.
The function is used to implement NodeConcept::describeParameters(). Each argument of the function is created by describeConstructorArgument().
Definition at line 200 of file ParameterDescriptor.hpp.
describeEnumerator()
template<typename EnumT > constexpr auto dw::framework::describeEnumerator (dw::core::StringView const && name, EnumT value) constexpr
Describe an enumerator.
This function is used to create arguments for describeEnumeratorCollection(). To avoid having to specify both explicitly - the enumerator name as well as the value - the macro DW_DESCRIBE_ENUMERATOR() is used.
Parameters
[in] name The enumerator name
[in] value The enumerator value
Returns
The pair with the enumerator name and value
Definition at line 124 of file EnumDescriptor.hpp.
describeEnumeratorCollection()
template<typename EnumT , typename... Args> constexpr auto dw::framework::describeEnumeratorCollection (Args const &&... args) constexpr
Describe the enumerators.
This function is used in specializations of EnumDescription::get() to describe all enumerators.
Parameters
args Each argument describes an enumerator created by describeEnumerator()
Returns
The array of enumerators
Definition at line 106 of file EnumDescriptor.hpp.
describeIndexParameter()
template<typename T , typename S , typename... MemberPointers> constexpr auto dw::framework::describeIndexParameter (dw::core::StringView const && typeName, dw::core::StringView const && parameterName, const MemberPointers &&... memberPointers) constexpr
Describe an index parameter.
The value represent an index which is used to retrieve a specific item from an array parameter identified by the semantic type. Regarding the member pointers see describeParameter().
Definition at line 362 of file ParameterDescriptor.hpp.
describeInputPorts()
template<typename Node > constexpr auto dw::framework::describeInputPorts () constexpr
Definition at line 148 of file PortDescriptor.hpp.
References describeInputPorts().
Referenced by describeInputPorts().
describeOutputPorts()
template<typename Node > constexpr auto dw::framework::describeOutputPorts () constexpr
Definition at line 154 of file PortDescriptor.hpp.
References describeOutputPorts().
Referenced by describeOutputPorts().
describeParameter()
template<typename T , typename S , typename... MemberPointers> constexpr auto dw::framework::describeParameter (dw::core::StringView const && typeName, dw::core::StringView const && parameterName, const MemberPointers &&... memberPointers) constexpr
Describe a parameter.
The value is stored within the constructor argument where this parameter is described in (see describeConstructorArgument()). When no member pointers are provided the value is stored directly in the constructor argument. When one member pointer is provided the value is stored in that member of the constructor argument. When more than one member pointer is provided the value is stored in the recursive member of the constructor argument.
Definition at line 283 of file ParameterDescriptor.hpp.
describeParameters()
template<typename NodeT > constexpr auto dw::framework::describeParameters () constexpr
Get described parameters for the passed node.
Definition at line 526 of file ParameterDescriptor.hpp.
References describeParameters().
Referenced by describeParameters().
describeParameterWithDefault()
template<typename T , typename S , typename... MemberPointers> constexpr auto dw::framework::describeParameterWithDefault (dw::core::StringView const && typeName, dw::core::StringView const && parameterName, T defaultValue, const MemberPointers &&... memberPointers) constexpr
Describe a parameter with a default value.
See describeParameter().
Definition at line 478 of file ParameterDescriptor.hpp.
describePass() [1/2]
constexpr std::tuple< dw::core::StringView, dwProcessorType > dw::framework::describePass (dw::core::StringView const && name, dwProcessorType processorType) constexpr
Describe a specific pass of a node.
The function is used to create the arguments for describePassCollection().
Definition at line 75 of file PassDescriptor.hpp.
Referenced by dw::framework::dwLidarPointCloudAccumulatorNode::describePasses(), dw::framework::dwLidarPointCloudStitcherNode::describePasses(), dw::framework::dwRadarDopplerMotionNode::describePasses(), dw::framework::dwRigNode::describePasses(), dw::framework::dwTraceCollectorNode::describePasses(), dw::framework::dwTraceNode::describePasses(), dw::framework::dwGlobalEgomotionNode::describePasses(), dw::framework::dwRelativeEgomotionIMUNode::describePasses(), dw::framework::dwFeatureDetectorNode::describePasses(), dw::framework::dwFeatureDetectorPVANode::describePasses(), dw::framework::dwFeatureTrackerNode::describePasses(), dw::framework::dwFeatureTrackerPVANode::describePasses(), dw::framework::dwPyramidNode::describePasses(), dw::framework::dwPyramidPVANode::describePasses(), dw::framework::dwPointCloudAccumulatorNode::describePasses(), dw::framework::dwIcpNode::describePasses(), dw::framework::dwSelfCalibrationNode::describePasses(), dw::framework::dwSelfCalibrationRoadcastAggregatorNode::describePasses(), dw::framework::dwSelfCalibrationSingleIMUNode::describePasses(), dw::framework::dwCameraNode::describePasses(), dw::framework::dwGPSChannelNode::describePasses(), dw::framework::dwGPSNode::describePasses(), dw::framework::dwIMUChannelNode::describePasses(), dw::framework::dwIMUNode::describePasses(), dw::framework::dwLidarBatchNode::describePasses(), dw::framework::dwLidarNode::describePasses(), dw::framework::dwRadarChannelNode::describePasses(), dw::framework::dwRadarNode::describePasses(), dw::framework::dwUltrasonicChannelNode::describePasses(), dw::framework::dwUltrasonicNode::describePasses(), dw::framework::dwVehicleStateChannelNewNode::describePasses(), dw::framework::dwVehicleStateChannelNode::describePasses(), and dw::framework::dwVehicleStateNode::describePasses().
describePass() [2/2]
template<typename DependenciesT > constexpr auto dw::framework::describePass (dw::core::StringView const && name, dwProcessorType processorType, DependenciesT dependencies) -> std::tuple<dw::core::StringView, dwProcessorType, DependenciesT> constexpr
Describe a specific pass of a node with custom inter-pass dependencies.
The function is used to create the arguments for describePassCollection(). The dependencies argument is created by describePassDependencies().
Definition at line 92 of file PassDescriptor.hpp.
describePassCollection()
template<typename... Args> constexpr auto dw::framework::describePassCollection (const Args &&... args) constexpr
Describe the passes of a node.
The function is used to implement NodeConcept::describePasses(). Each argument of the function is created by describePass().
Definition at line 55 of file PassDescriptor.hpp.
Referenced by dw::framework::dwLidarPointCloudAccumulatorNode::describePasses(), dw::framework::dwLidarPointCloudStitcherNode::describePasses(), dw::framework::dwRadarDopplerMotionNode::describePasses(), dw::framework::dwRigNode::describePasses(), dw::framework::dwTraceCollectorNode::describePasses(), dw::framework::dwTraceNode::describePasses(), dw::framework::dwGlobalEgomotionNode::describePasses(), dw::framework::dwRelativeEgomotionIMUNode::describePasses(), dw::framework::dwFeatureDetectorNode::describePasses(), dw::framework::dwFeatureDetectorPVANode::describePasses(), dw::framework::dwFeatureTrackerNode::describePasses(), dw::framework::dwFeatureTrackerPVANode::describePasses(), dw::framework::dwPyramidNode::describePasses(), dw::framework::dwPyramidPVANode::describePasses(), dw::framework::dwPointCloudAccumulatorNode::describePasses(), dw::framework::dwIcpNode::describePasses(), dw::framework::dwSelfCalibrationNode::describePasses(), dw::framework::dwSelfCalibrationRoadcastAggregatorNode::describePasses(), dw::framework::dwSelfCalibrationSingleIMUNode::describePasses(), dw::framework::dwCameraNode::describePasses(), dw::framework::dwGPSChannelNode::describePasses(), dw::framework::dwGPSNode::describePasses(), dw::framework::dwIMUChannelNode::describePasses(), dw::framework::dwIMUNode::describePasses(), dw::framework::dwLidarBatchNode::describePasses(), dw::framework::dwLidarNode::describePasses(), dw::framework::dwRadarChannelNode::describePasses(), dw::framework::dwRadarNode::describePasses(), dw::framework::dwUltrasonicChannelNode::describePasses(), dw::framework::dwUltrasonicNode::describePasses(), dw::framework::dwVehicleStateChannelNewNode::describePasses(), dw::framework::dwVehicleStateChannelNode::describePasses(), and dw::framework::dwVehicleStateNode::describePasses().
describePassDependencies()
template<typename... Args> constexpr auto dw::framework::describePassDependencies (const Args &&... args) -> std::array<dw::core::StringView, sizeof...(Args)> constexpr
Describe the custom inter-pass dependencies of a pass.
The function is used to create the dependencies argument for describePass().
Definition at line 107 of file PassDescriptor.hpp.
describePasses()
template<typename Node > constexpr auto dw::framework::describePasses () constexpr
Get described passes for the passed node.
Definition at line 114 of file PassDescriptor.hpp.
References describePasses().
Referenced by describePasses().
describePort() [1/2]
template<typename PortType > constexpr auto dw::framework::describePort (dw::core::StringView typeName, dw::core::StringView name, dw::core::StringView comment) constexpr
Definition at line 101 of file PortDescriptor.hpp.
References OPTIONAL.
describePort() [2/2]
template<typename PortType > constexpr auto dw::framework::describePort (dw::core::StringView typeName, dw::core::StringView name, PortBinding binding = PortBinding::OPTIONAL, dw::core::StringView comment = ""_sv) constexpr
Definition at line 86 of file PortDescriptor.hpp.
describePortArray() [1/2]
template<typename PortType , size_t ArraySize, typename std::enable_if_t< ArraySize !=0, void > * = nullptr> constexpr auto dw::framework::describePortArray (dw::core::StringView typeName, dw::core::StringView name, dw::core::StringView comment) constexpr
Definition at line 135 of file PortDescriptor.hpp.
References OPTIONAL.
describePortArray() [2/2]
template<typename PortType , size_t ArraySize, typename std::enable_if_t< ArraySize !=0, void > * = nullptr> constexpr auto dw::framework::describePortArray (dw::core::StringView typeName, dw::core::StringView name, PortBinding binding = PortBinding::OPTIONAL, dw::core::StringView comment = ""_sv) constexpr
Definition at line 117 of file PortDescriptor.hpp.
describePortCollection()
template<typename... Args> constexpr auto dw::framework::describePortCollection (Args &&... args) constexpr
Definition at line 52 of file PortDescriptor.hpp.
Referenced by dw::framework::dwLidarPointCloudAccumulatorNode::describeInputPorts(), dw::framework::dwLidarPointCloudStitcherNode::describeInputPorts(), dw::framework::dwRadarDopplerMotionNode::describeInputPorts(), dw::framework::dwRigNode::describeInputPorts(), dw::framework::dwTraceCollectorNode::describeInputPorts(), dw::framework::dwTraceNode::describeInputPorts(), dw::framework::dwGlobalEgomotionNode::describeInputPorts(), dw::framework::dwRelativeEgomotionIMUNode::describeInputPorts(), dw::framework::dwFeatureDetectorNodeBase::describeInputPorts(), dw::framework::dwFeatureTrackerNodeBase::describeInputPorts(), dw::framework::dwPyramidNodeBase::describeInputPorts(), dw::framework::dwPointCloudAccumulatorNode::describeInputPorts(), dw::framework::dwIcpNode::describeInputPorts(), dw::framework::dwSelfCalibrationNode::describeInputPorts(), dw::framework::dwSelfCalibrationRoadcastAggregatorNode::describeInputPorts(), dw::framework::dwSelfCalibrationSingleIMUNode::describeInputPorts(), dw::framework::dwCameraNode::describeInputPorts(), dw::framework::dwGPSChannelNode::describeInputPorts(), dw::framework::dwGPSNode::describeInputPorts(), dw::framework::dwIMUChannelNode::describeInputPorts(), dw::framework::dwIMUNode::describeInputPorts(), dw::framework::dwLidarBatchNode::describeInputPorts(), dw::framework::dwLidarNode::describeInputPorts(), dw::framework::dwRadarChannelNode::describeInputPorts(), dw::framework::dwRadarNode::describeInputPorts(), dw::framework::dwUltrasonicChannelNode::describeInputPorts(), dw::framework::dwUltrasonicNode::describeInputPorts(), dw::framework::dwVehicleStateChannelNewNode::describeInputPorts(), dw::framework::dwVehicleStateChannelNode::describeInputPorts(), dw::framework::dwVehicleStateNode::describeInputPorts(), dw::framework::dwLidarPointCloudAccumulatorNode::describeOutputPorts(), dw::framework::dwLidarPointCloudStitcherNode::describeOutputPorts(), dw::framework::dwRadarDopplerMotionNode::describeOutputPorts(), dw::framework::dwRigNode::describeOutputPorts(), dw::framework::dwTraceCollectorNode::describeOutputPorts(), dw::framework::dwTraceNode::describeOutputPorts(), dw::framework::dwGlobalEgomotionNode::describeOutputPorts(), dw::framework::dwRelativeEgomotionIMUNode::describeOutputPorts(), dw::framework::dwFeatureDetectorNodeBase::describeOutputPorts(), dw::framework::dwFeatureTrackerNodeBase::describeOutputPorts(), dw::framework::dwPyramidNodeBase::describeOutputPorts(), dw::framework::dwPointCloudAccumulatorNode::describeOutputPorts(), dw::framework::dwIcpNode::describeOutputPorts(), dw::framework::dwSelfCalibrationNode::describeOutputPorts(), dw::framework::dwSelfCalibrationRoadcastAggregatorNode::describeOutputPorts(), dw::framework::dwSelfCalibrationSingleIMUNode::describeOutputPorts(), dw::framework::dwCameraNode::describeOutputPorts(), dw::framework::dwGPSChannelNode::describeOutputPorts(), dw::framework::dwGPSNode::describeOutputPorts(), dw::framework::dwIMUChannelNode::describeOutputPorts(), dw::framework::dwIMUNode::describeOutputPorts(), dw::framework::dwLidarBatchNode::describeOutputPorts(), dw::framework::dwLidarNode::describeOutputPorts(), dw::framework::dwRadarChannelNode::describeOutputPorts(), dw::framework::dwRadarNode::describeOutputPorts(), dw::framework::dwUltrasonicChannelNode::describeOutputPorts(), dw::framework::dwUltrasonicNode::describeOutputPorts(), dw::framework::dwVehicleStateChannelNewNode::describeOutputPorts(), dw::framework::dwVehicleStateChannelNode::describeOutputPorts(), and dw::framework::dwVehicleStateNode::describeOutputPorts().
describePorts()
template<typename Node , PortDirection Direction, typename std::enable_if_t< Direction==PortDirection::INPUT, void > * = nullptr> constexpr auto dw::framework::describePorts () constexpr
Definition at line 163 of file PortDescriptor.hpp.
describeUnnamedArrayParameter()
template<typename T , typename S , typename... MemberPointers> constexpr auto dw::framework::describeUnnamedArrayParameter (dw::core::StringView const && typeName, size_t arraySize, const MemberPointers &&... memberPointers) constexpr
Describe an unnamed array parameter.
The value isn't identified by a name but solely by the semantic type. Regarding the member pointers see describeParameter().
Definition at line 452 of file ParameterDescriptor.hpp.
describeUnnamedParameter()
template<typename T , typename S , typename... MemberPointers> constexpr auto dw::framework::describeUnnamedParameter (dw::core::StringView const && typeName, const MemberPointers &&... memberPointers) constexpr
Describe an unnamed parameter.
The value isn't identified by a name but solely by the semantic type. Regarding the member pointers see describeParameter().
Definition at line 425 of file ParameterDescriptor.hpp.
descriptorIndex()
template<typename Node , PortDirection Direction, size_t PortIndex> constexpr size_t dw::framework::descriptorIndex () constexpr
Definition at line 302 of file PortDescriptor.hpp.
References OUTPUT.
descriptorPortArray()
template<typename Node , PortDirection Direction, size_t DescriptorIndex> constexpr bool dw::framework::descriptorPortArray () constexpr
Definition at line 190 of file PortDescriptor.hpp.
Referenced by dw::framework::SimpleNode::getInputPort(), and dw::framework::SimpleNode::getOutputPort().
descriptorPortBinding()
template<typename Node , PortDirection Direction, size_t DescriptorIndex> constexpr PortBinding dw::framework::descriptorPortBinding () constexpr
Definition at line 213 of file PortDescriptor.hpp.
descriptorPortComment()
template<typename Node , PortDirection Direction, size_t DescriptorIndex> constexpr dw::core::StringView dw::framework::descriptorPortComment () constexpr
Definition at line 222 of file PortDescriptor.hpp.
descriptorPortSize()
template<typename Node , PortDirection Direction, size_t DescriptorIndex> constexpr size_t dw::framework::descriptorPortSize () constexpr
Definition at line 200 of file PortDescriptor.hpp.
extractMetadata()
MetadataPayload * dw::framework::extractMetadata (GenericData packet)
Referenced by dw::framework::PortOutput< T >::getFreeElement().
getInputPorts()
const PortCollectionDescriptor & dw::framework::getInputPorts (const dw::core::StringView & className)
getNodeNames()
dw::core::HeapVectorFixed< dw::core::StringView > dw::framework::getNodeNames ()
getOutputPorts()
const PortCollectionDescriptor & dw::framework::getOutputPorts (const dw::core::StringView & className)
getParameters()
const ParameterCollectionDescriptor & dw::framework::getParameters (const dw::core::StringView & className)
getPasses()
const PassCollectionDescriptor & dw::framework::getPasses (const dw::core::StringView & className)
getTimestamp()
dw::core::Optional< dwTime_t > dw::framework::getTimestamp (ChannelMetadata const & header)
getValidityStatus()
dw::core::Optional< dwValidityStatus > dw::framework::getValidityStatus (ChannelMetadata const & header)
hasPassDependencies()
template<typename Node , size_t Index> constexpr bool dw::framework::hasPassDependencies () constexpr
Check if a pass specifies explicit dependencies.
Definition at line 199 of file PassDescriptor.hpp.
References PASS_DEPENDENCIES.
IsConsumer()
constexpr bool dw::framework::IsConsumer (ChannelRole role) inline constexpr
Definition at line 105 of file ChannelParameters.hpp.
References DW_CHANNEL_ROLE_CONSUMER.
IsProducer()
constexpr bool dw::framework::IsProducer (ChannelRole role) inline constexpr
Definition at line 100 of file ChannelParameters.hpp.
References DW_CHANNEL_ROLE_PRODUCER.
isValidPass() [1/2]
template<typename Node > constexpr bool dw::framework::isValidPass (dw::core::StringView identifier) constexpr
Check if given string is a valid pass name.
Definition at line 177 of file PassDescriptor.hpp.
isValidPass() [2/2]
template<typename Node > constexpr bool dw::framework::isValidPass (std::size_t passID) constexpr
Check if pass index is valid.
Definition at line 130 of file PassDescriptor.hpp.
isValidPortIdentifier()
template<typename Node , PortDirection Direction> constexpr bool dw::framework::isValidPortIdentifier (StringView identifier) constexpr
Definition at line 419 of file PortDescriptor.hpp.
isValidPortIndex()
template<typename Node , PortDirection Direction> constexpr bool dw::framework::isValidPortIndex (std::size_t portID) constexpr
Definition at line 321 of file PortDescriptor.hpp.
References OUTPUT.
make_specimen()
template<typename T > static GenericDataReference dw::framework::make_specimen (typename parameter_traits< T >::SpecimenT * specimen) inline static
Definition at line 288 of file ChannelPacketTypes.hpp.
References dw::framework::GenericDataReference::packetTypeID.
makeUniqueFromTuple()
template<typename NodeT , class ConstructorArguments > auto dw::framework::makeUniqueFromTuple (const ConstructorArguments && constructorArguments) -> std::unique_ptr<NodeT>
Instantiate a node using the passed constructor arguments.
Definition at line 992 of file ParameterDescriptor.hpp.
mapEnumNameToValue()
template<typename EnumT > auto dw::framework::mapEnumNameToValue (dw::core::StringView const & name) -> EnumT
Get the enumerator value based on the name.
Parameters
[in] name The enumerator name
Returns
The enumerator value
Exceptions
Exception if the enumerator name is invalid
Definition at line 137 of file EnumDescriptor.hpp.
References dw::framework::EnumDescription< EnumT >::get().
mapEnumValueToName()
template<typename EnumT > dw::core::StringView dw::framework::mapEnumValueToName (EnumT value)
Get the enumerator name based on the value.
Parameters
[in] value The enumerator value
Returns
The enumerator name
Exceptions
Exception if the enumerator value is invalid
Definition at line 163 of file EnumDescriptor.hpp.
References dw::framework::EnumDescription< EnumT >::get().
nvSciGetErrorName()
const char * dw::framework::nvSciGetErrorName (uint32_t error)
nvSciGetEventName()
const char * dw::framework::nvSciGetEventName (uint32_t event)
operator&()
constexpr ChannelNvSciStreamEnabledComponents dw::framework::operator& (ChannelNvSciStreamEnabledComponents a, ChannelNvSciStreamEnabledComponents b) inline constexpr
Definition at line 163 of file ChannelParameters.hpp.
operator|()
constexpr ChannelNvSciStreamEnabledComponents dw::framework::operator| (ChannelNvSciStreamEnabledComponents a, ChannelNvSciStreamEnabledComponents b) inline constexpr
Definition at line 169 of file ChannelParameters.hpp.
parameterSize()
template<typename NodeT > constexpr std::size_t dw::framework::parameterSize () constexpr
Get the number of parameters for a given node.
Definition at line 1047 of file ParameterDescriptor.hpp.
ParseAllChannelParameters()
template<typename... Others> static void dw::framework::ParseAllChannelParameters (const ChannelParamStr & channelParams, Others &&... others) inline static
Definition at line 360 of file ChannelParameters.hpp.
References ParseChannelParameters().
Referenced by dw::framework::ChannelNvSciStreamParams::ChannelNvSciStreamParams(), dw::framework::ChannelParams::ChannelParams(), and dw::framework::ChannelSocketParams::ChannelSocketParams().
ParseChannelParameter() [1/12]
template<typename T > static T dw::framework::ParseChannelParameter (const ChannelParamStr & value) inline static
Referenced by ParseChannelParameter(), and ParseChannelParameters().
ParseChannelParameter() [2/12]
template<> int64_t dw::framework::ParseChannelParameter (const ChannelParamStr & value)
Definition at line 178 of file ChannelParameters.hpp.
ParseChannelParameter() [3/12]
template<> size_t dw::framework::ParseChannelParameter (const ChannelParamStr & value)
Definition at line 185 of file ChannelParameters.hpp.
ParseChannelParameter() [4/12]
template<> uint32_t dw::framework::ParseChannelParameter (const ChannelParamStr & value)
Definition at line 197 of file ChannelParameters.hpp.
ParseChannelParameter() [5/12]
template<> uint16_t dw::framework::ParseChannelParameter (const ChannelParamStr & value)
Definition at line 205 of file ChannelParameters.hpp.
ParseChannelParameter() [6/12]
template<> bool dw::framework::ParseChannelParameter (const ChannelParamStr & value)
Definition at line 217 of file ChannelParameters.hpp.
ParseChannelParameter() [7/12]
template<> ChannelRole dw::framework::ParseChannelParameter (const ChannelParamStr & value)
Definition at line 236 of file ChannelParameters.hpp.
References DW_CHANNEL_ROLE_COMPOSITE, DW_CHANNEL_ROLE_CONSUMER, and DW_CHANNEL_ROLE_PRODUCER.
ParseChannelParameter() [8/12]
template<> ChannelType dw::framework::ParseChannelParameter (const ChannelParamStr & value)
Definition at line 259 of file ChannelParameters.hpp.
ParseChannelParameter() [9/12]
template<> ChannelMode dw::framework::ParseChannelParameter (const ChannelParamStr & value)
Definition at line 295 of file ChannelParameters.hpp.
References MAILBOX, and SINGLETON.
ParseChannelParameter() [10/12]
template<size_t Size> void dw::framework::ParseChannelParameter (const ChannelParamStr & value, dw::core::FixedString< Size > & result)
Definition at line 320 of file ChannelParameters.hpp.
ParseChannelParameter() [11/12]
template<typename T , size_t N> void dw::framework::ParseChannelParameter (const ChannelParamStr & value, dw::core::VectorFixed< T, N > & result)
Definition at line 326 of file ChannelParameters.hpp.
References ParseChannelParameter().
ParseChannelParameter() [12/12]
template<typename T > void dw::framework::ParseChannelParameter (const ChannelParamStr & value, T & result)
Definition at line 314 of file ChannelParameters.hpp.
ParseChannelParameters() [1/2]
static void dw::framework::ParseChannelParameters (const ChannelParamStr & , const ChannelParamStr &) inline static
Definition at line 343 of file ChannelParameters.hpp.
Referenced by ParseAllChannelParameters(), and ParseChannelParameters().
ParseChannelParameters() [2/2]
template<typename T , typename... Others> static void dw::framework::ParseChannelParameters (const ChannelParamStr & key, const ChannelParamStr & value, const char * staticKey, T & result, Others &&... others) inline static
Definition at line 349 of file ChannelParameters.hpp.
References ParseChannelParameter(), and ParseChannelParameters().
passDependencies()
template<typename Node , size_t Index, typename std::enable_if_t< hasPassDependencies< Node, Index >(), void > * = nullptr> constexpr auto dw::framework::passDependencies () constexpr
Get the dependencies of a pass.
Get the dependencies of a pass (which returns an empty collection for passes without explicit dependencies).
Definition at line 209 of file PassDescriptor.hpp.
passIndex()
template<typename Node > constexpr size_t dw::framework::passIndex (dw::core::StringView identifier) constexpr
Get the the pass index for a pass identified by name.
Definition at line 170 of file PassDescriptor.hpp.
passName()
template<typename Node , size_t Index> constexpr dw::core::StringView dw::framework::passName () constexpr
Get the name of a pass.
Definition at line 185 of file PassDescriptor.hpp.
passProcessorType()
template<typename Node , size_t Index> constexpr dwProcessorType dw::framework::passProcessorType () constexpr
Get the processor type of a pass.
Definition at line 192 of file PassDescriptor.hpp.
passSize()
template<typename Node > constexpr std::size_t dw::framework::passSize () constexpr
Get the number of passes of the passed node.
Definition at line 121 of file PassDescriptor.hpp.
populateParameters()
template<typename NodeT , class ConstructorArguments , typename std::enable_if_t< std::tuple_size< ConstructorArguments >()==1, void > * = nullptr> void dw::framework::populateParameters (ConstructorArguments & constructorArguments, const ParameterProvider & provider)
Populate the constructor arguments using values from the parameter provider.
Definition at line 826 of file ParameterDescriptor.hpp.
portArraySize()
template<typename Node , PortDirection Direction> constexpr size_t dw::framework::portArraySize (StringView identifier) constexpr
Definition at line 363 of file PortDescriptor.hpp.
portDescriptorIndex()
template<typename Node , PortDirection Direction> constexpr size_t dw::framework::portDescriptorIndex (StringView identifier) constexpr
Definition at line 456 of file PortDescriptor.hpp.
portDescriptorSize()
template<typename Node , PortDirection Direction> constexpr std::size_t dw::framework::portDescriptorSize () constexpr
Definition at line 183 of file PortDescriptor.hpp.
portDescriptorType()
template<typename Node , PortDirection Direction, size_t DescriptorIndex> constexpr auto dw::framework::portDescriptorType () constexpr
Definition at line 231 of file PortDescriptor.hpp.
References PORT_TYPE.
portIndex()
template<typename Node , PortDirection Direction> constexpr size_t dw::framework::portIndex (StringView identifier) constexpr
Definition at line 406 of file PortDescriptor.hpp.
References OUTPUT.
portSize()
template<typename Node , PortDirection Direction> constexpr std::size_t dw::framework::portSize () constexpr
Definition at line 267 of file PortDescriptor.hpp.
portType()
template<typename Node , PortDirection Direction, size_t PortIndex> constexpr auto dw::framework::portType () constexpr
Definition at line 313 of file PortDescriptor.hpp.
registerNode()
template<typename NodeT > void dw::framework::registerNode (const char * className)
Definition at line 131 of file NodeFactory.hpp.
setTimestamp()
void dw::framework::setTimestamp (ChannelMetadata & header, dwTime_t const & timestamp)
setValidityStatus()
void dw::framework::setValidityStatus (ChannelMetadata & header, dwValidityStatus const & status)
ToParam()
static const char * dw::framework::ToParam (ChannelType channelType) inline static
Definition at line 60 of file ChannelParameters.hpp.
Variable Documentation
accumulatorDownsampleFactor
uint32_t dw::framework::accumulatorDownsampleFactor
Definition at line 57 of file dwIcpNode.hpp.
Referenced by dw::framework::dwIcpNode::describeParameters().
CALIBRATION_ACCEPTED_STATE_STRING
constexpr char dw::framework::CALIBRATION_ACCEPTED_STATE_STRING[] = "accepted" static constexpr
Definition at line 67 of file SelfCalibrationTypes.hpp.
CALIBRATION_FAILED_STATE_STRING
constexpr char dw::framework::CALIBRATION_FAILED_STATE_STRING[] = "failed" static constexpr
Definition at line 69 of file SelfCalibrationTypes.hpp.
CALIBRATION_INVALID_STATE_STRING
constexpr char dw::framework::CALIBRATION_INVALID_STATE_STRING[] = "invalid" static constexpr
Definition at line 70 of file SelfCalibrationTypes.hpp.
CALIBRATION_NOT_ACCEPTED_STATE_STRING
constexpr char dw::framework::CALIBRATION_NOT_ACCEPTED_STATE_STRING[] = "not-accepted" static constexpr
Definition at line 68 of file SelfCalibrationTypes.hpp.
calibrationOutputFileName
char8_t const* dw::framework::calibrationOutputFileName
Output path where calibration overlay will be written
Definition at line 62 of file dwRigNode.hpp.
Referenced by dw::framework::dwRigNode::describeParameters().
calibrationOverlayFileName
char8_t const* dw::framework::calibrationOverlayFileName
Input/Output path of persistent calibration overlay
Definition at line 65 of file dwRigNode.hpp.
Referenced by dw::framework::dwRigNode::describeParameters().
cameraSensorEnabled
bool dw::framework::cameraSensorEnabled[framework::SELF_CALIBRATION_NODE_MAX_CAMERAS]
Definition at line 70 of file dwRigNode.hpp.
Referenced by dw::framework::dwRigNode::describeParameters().
cameraSensorRigIndices
std::uint32_t dw::framework::cameraSensorRigIndices[framework::SELF_CALIBRATION_NODE_MAX_CAMERAS]
Definition at line 71 of file dwRigNode.hpp.
Referenced by dw::framework::dwRigNode::describeParameters().
channelMask
uint64_t dw::framework::channelMask
Definition at line 53 of file dwTraceNode.hpp.
Referenced by dw::framework::dwTraceCollectorNode::describeParameters(), and dw::framework::dwTraceNode::describeParameters().
CHN_WAIT_TIMEOUT_US
constexpr dwTime_t dw::framework::CHN_WAIT_TIMEOUT_US = 50'000'000 static constexpr
Definition at line 51 of file Channel.hpp.
cudaStream
cudaStream_t dw::framework::cudaStream
Definition at line 60 of file dwIcpNode.hpp.
Referenced by dw::framework::dwFeatureDetectorNode::describeParameters(), dw::framework::dwFeatureDetectorPVANode::describeParameters(), dw::framework::dwFeatureTrackerNode::describeParameters(), dw::framework::dwFeatureTrackerPVANode::describeParameters(), dw::framework::dwIcpNode::describeParameters(), and dw::framework::PassImpl< PassFunctionT >::PassImpl().
cupvastream
cupvaStream_t dw::framework::cupvastream
Data Type of pyramid.
Definition at line 66 of file dwFeatureDetectorNode.hpp.
Referenced by dw::framework::dwFeatureDetectorPVANode::describeParameters(), and dw::framework::dwPyramidPVANode::describeParameters().
cupvaStream
cupvaStream_t dw::framework::cupvaStream
Definition at line 60 of file dwFeatureTrackerNode.hpp.
Referenced by dw::framework::dwFeatureTrackerPVANode::describeParameters().
dataType
dwTrivialDataType dw::framework::dataType = dwTrivialDataType::DW_TYPE_FLOAT32
Number of levels in the pyramid.
Definition at line 58 of file dwPyramidNode.hpp.
diskIOStatsEnabled
bool dw::framework::diskIOStatsEnabled
Definition at line 81 of file dwTraceCollectorNode.hpp.
Referenced by dw::framework::dwTraceCollectorNode::describeParameters().
DW_CALIBRATION_MAX_SENSORS
constexpr uint32_t dw::framework::DW_CALIBRATION_MAX_SENSORS = 64 static constexpr
Definition at line 45 of file DwRoadCastCommonTypes.hpp.
dwDetectorParams
dwFeature2DDetectorConfig dw::framework::dwDetectorParams
Definition at line 67 of file dwFeatureDetectorNode.hpp.
Referenced by dw::framework::dwFeatureDetectorNode::describeParameters(), and dw::framework::dwFeatureDetectorPVANode::describeParameters().
DWFRAMEWORK_MAX_INTERNAL_TYPES
constexpr uint32_t dw::framework::DWFRAMEWORK_MAX_INTERNAL_TYPES = 0x400 constexpr
Definition at line 179 of file ChannelPacketTypes.hpp.
DWFRAMEWORK_METADATA_PACKET_TYPE_ID_OFFSET
constexpr uint32_t dw::framework::DWFRAMEWORK_METADATA_PACKET_TYPE_ID_OFFSET = 0x80000000 constexpr
Definition at line 178 of file ChannelPacketTypes.hpp.
DWFRAMEWORK_PACKET_ID_DEFAULT
constexpr ChannelPacketTypeID dw::framework::DWFRAMEWORK_PACKET_ID_DEFAULT = 0U constexpr
The id of a data type that is flat and zero initialized. In this case, only the size will be checked against remote peers.
Definition at line 177 of file ChannelPacketTypes.hpp.
dwSerializationTypeStringToEnumMap
const dw::core::StaticHashMap<dw::core::FixedString<64>, dwSerializationType, dwSerializationType::DW_TYPES_COUNT - 1> dw::framework::dwSerializationTypeStringToEnumMap
Definition at line 52 of file SerializationTypeStringToEnumMap.hpp.
dwTrackerParams
dwFeature2DTrackerConfig dw::framework::dwTrackerParams
Definition at line 59 of file dwFeatureTrackerNode.hpp.
Referenced by dw::framework::dwFeatureTrackerNode::describeParameters(), and dw::framework::dwFeatureTrackerPVANode::describeParameters().
enable
bool dw::framework::enable
Definition at line 54 of file dwIcpNode.hpp.
Referenced by dw::framework::dwIcpNode::describeParameters(), and dw::framework::dwBaseDrainerTemplate< ProcessedDataType, ReadProcessedDataFunc, DataSourceType >::setLockstepDeterministicMode().
enabled
bool dw::framework::enabled
Definition at line 54 of file dwTraceCollectorNode.hpp.
Referenced by dw::framework::dwTraceCollectorNode::describeParameters().
extrinsic
dwTransformation3f dw::framework::extrinsic
Definition at line 65 of file dwFeatureDetectorNode.hpp.
Referenced by dw::framework::dwFeatureDetectorNode::describeParameters(), dw::framework::dwFeatureDetectorPVANode::describeParameters(), dw::framework::dwFeatureTrackerNode::describeParameters(), and dw::framework::dwFeatureTrackerPVANode::describeParameters().
fileBackendEnabled
bool dw::framework::fileBackendEnabled
Definition at line 61 of file dwTraceCollectorNode.hpp.
Referenced by dw::framework::dwTraceCollectorNode::describeParameters().
filePath
dw::core::FixedString<384> dw::framework::filePath
Definition at line 56 of file dwTraceCollectorNode.hpp.
Referenced by dw::framework::dwTraceCollectorNode::describeParameters().
ftraceBackendEnabled
bool dw::framework::ftraceBackendEnabled
Definition at line 73 of file dwTraceCollectorNode.hpp.
Referenced by dw::framework::dwTraceCollectorNode::describeParameters().
fullMemUsage
bool dw::framework::fullMemUsage
Definition at line 77 of file dwTraceCollectorNode.hpp.
Referenced by dw::framework::dwTraceCollectorNode::describeParameters().
height
uint32_t dw::framework::height
Width of level 0.
Definition at line 56 of file dwPyramidNode.hpp.
Referenced by dw::framework::dwPyramidNode::describeParameters(), and dw::framework::dwPyramidPVANode::describeParameters().
imuSensorEnabled
bool dw::framework::imuSensorEnabled[framework::SELF_CALIBRATION_NODE_MAX_IMUS]
Definition at line 68 of file dwRigNode.hpp.
Referenced by dw::framework::dwRigNode::describeParameters().
imuSensorRigIndices
std::uint32_t dw::framework::imuSensorRigIndices[framework::SELF_CALIBRATION_NODE_MAX_IMUS]
Definition at line 69 of file dwRigNode.hpp.
Referenced by dw::framework::dwRigNode::describeParameters().
intrinsic
dwCameraModelHandle_t dw::framework::intrinsic
Definition at line 64 of file dwFeatureDetectorNode.hpp.
Referenced by dw::framework::dwFeatureDetectorNode::describeParameters(), dw::framework::dwFeatureDetectorPVANode::describeParameters(), dw::framework::dwFeatureTrackerNode::describeParameters(), and dw::framework::dwFeatureTrackerPVANode::describeParameters().
ipAddr
dw::core::FixedString<16> dw::framework::ipAddr
Definition at line 65 of file dwTraceCollectorNode.hpp.
Referenced by dw::framework::dwTraceCollectorNode::describeParameters().
levelCount
uint32_t dw::framework::levelCount
Height of level 0.
Definition at line 57 of file dwPyramidNode.hpp.
Referenced by dw::framework::dwPyramidNode::describeParameters(), and dw::framework::dwPyramidPVANode::describeParameters().
lidarICPUsesEgomotion
bool dw::framework::lidarICPUsesEgomotion
Definition at line 58 of file dwIcpNode.hpp.
Referenced by dw::framework::dwIcpNode::describeParameters().
lidarMaxICPIterations
uint32_t dw::framework::lidarMaxICPIterations
Definition at line 56 of file dwIcpNode.hpp.
Referenced by dw::framework::dwIcpNode::describeParameters().
lidarProps
dwLidarProperties dw::framework::lidarProps
Definition at line 59 of file dwIcpNode.hpp.
Referenced by dw::framework::dwIcpNode::describeParameters().
lidarSensorEnabled
bool dw::framework::lidarSensorEnabled[framework::SELF_CALIBRATION_NODE_MAX_LIDARS]
Definition at line 74 of file dwRigNode.hpp.
Referenced by dw::framework::dwRigNode::describeParameters().
lidarSensorRigIndices
std::uint32_t dw::framework::lidarSensorRigIndices[framework::SELF_CALIBRATION_NODE_MAX_LIDARS]
Definition at line 75 of file dwRigNode.hpp.
Referenced by dw::framework::dwRigNode::describeParameters().
maskHeight
uint32_t dw::framework::maskHeight
Definition at line 57 of file dwFeatureDetectorNode.hpp.
maskStrideBytes
uint32_t dw::framework::maskStrideBytes
Definition at line 55 of file dwFeatureDetectorNode.hpp.
maskWidth
uint32_t dw::framework::maskWidth
Definition at line 56 of file dwFeatureDetectorNode.hpp.
MAX_CHANNEL_ALL_PARAMS_SIZE
constexpr uint16_t dw::framework::MAX_CHANNEL_ALL_PARAMS_SIZE = 1024 static constexpr
Definition at line 111 of file ChannelParameters.hpp.
MAX_CHANNEL_CONSUMERS_COUNT
constexpr uint16_t dw::framework::MAX_CHANNEL_CONSUMERS_COUNT = 256 static constexpr
Definition at line 113 of file ChannelParameters.hpp.
MAX_CHANNEL_PARAM_SIZE
constexpr uint16_t dw::framework::MAX_CHANNEL_PARAM_SIZE = 1024 static constexpr
Definition at line 110 of file ChannelParameters.hpp.
MAX_CHANNEL_PRODUCERS_COUNT
constexpr uint16_t dw::framework::MAX_CHANNEL_PRODUCERS_COUNT = 2048 static constexpr
Definition at line 112 of file ChannelParameters.hpp.
MAX_INPUT_TRACE_PORTS
constexpr uint32_t dw::framework::MAX_INPUT_TRACE_PORTS = 16 static constexpr
Definition at line 46 of file dwTraceCollectorNode.hpp.
Referenced by dw::framework::dwTraceCollectorNode::describeInputPorts().
MAX_LIDAR_STITCHER_PORT_NUM
constexpr uint32_t dw::framework::MAX_LIDAR_STITCHER_PORT_NUM = 8 static constexpr
Definition at line 48 of file PointCloudProcessingCommonTypes.hpp.
Referenced by dw::framework::dwLidarPointCloudStitcherNode::describeInputPorts(), and dw::framework::dwLidarPointCloudStitcherNode::describeParameters().
MAX_PORT_DESCRIPTOR_PER_COLLECTION
constexpr size_t dw::framework::MAX_PORT_DESCRIPTOR_PER_COLLECTION {256U} static constexpr
Definition at line 88 of file PortCollectionDescriptor.hpp.
maxFileSizeMB
uint32_t dw::framework::maxFileSizeMB
Definition at line 83 of file dwTraceCollectorNode.hpp.
Referenced by dw::framework::dwTraceCollectorNode::describeParameters().
maxTracesPerChPerEpoch
uint32_t dw::framework::maxTracesPerChPerEpoch
Definition at line 55 of file dwTraceNode.hpp.
Referenced by dw::framework::dwTraceNode::describeParameters().
memTraceEnabled
bool dw::framework::memTraceEnabled
Definition at line 75 of file dwTraceCollectorNode.hpp.
Referenced by dw::framework::dwTraceCollectorNode::describeParameters().
networkBackendEnabled
bool dw::framework::networkBackendEnabled
Definition at line 63 of file dwTraceCollectorNode.hpp.
Referenced by dw::framework::dwTraceCollectorNode::describeParameters().
nvtxBackendEnabled
bool dw::framework::nvtxBackendEnabled
Definition at line 69 of file dwTraceCollectorNode.hpp.
Referenced by dw::framework::dwTraceCollectorNode::describeParameters().
PARAMETER_ARRAY_SIZE
constexpr size_t dw::framework::PARAMETER_ARRAY_SIZE {5U} static constexpr
Definition at line 254 of file ParameterDescriptor.hpp.
PARAMETER_CONSTRUCTOR_ARGUMENT_DESCRIPTOR
constexpr size_t dw::framework::PARAMETER_CONSTRUCTOR_ARGUMENT_DESCRIPTOR {1U} static constexpr
Definition at line 50 of file ParameterDescriptor.hpp.
PARAMETER_CONSTRUCTOR_ARGUMENT_TYPE
constexpr size_t dw::framework::PARAMETER_CONSTRUCTOR_ARGUMENT_TYPE {0U} static constexpr
Definition at line 47 of file ParameterDescriptor.hpp.
PARAMETER_DEFAULT_VALUE
constexpr size_t dw::framework::PARAMETER_DEFAULT_VALUE {7U} static constexpr
Definition at line 260 of file ParameterDescriptor.hpp.
PARAMETER_IS_INDEX
constexpr size_t dw::framework::PARAMETER_IS_INDEX {4U} static constexpr
Definition at line 251 of file ParameterDescriptor.hpp.
PARAMETER_MEMBER_PTRS
constexpr size_t dw::framework::PARAMETER_MEMBER_PTRS {6U} static constexpr
Definition at line 257 of file ParameterDescriptor.hpp.
PARAMETER_NAME
constexpr size_t dw::framework::PARAMETER_NAME {1U} static constexpr
Definition at line 242 of file ParameterDescriptor.hpp.
PARAMETER_SEMANTIC_TYPE
constexpr size_t dw::framework::PARAMETER_SEMANTIC_TYPE {3U} static constexpr
Definition at line 248 of file ParameterDescriptor.hpp.
PARAMETER_TYPE
constexpr size_t dw::framework::PARAMETER_TYPE {2U} static constexpr
Definition at line 245 of file ParameterDescriptor.hpp.
PARAMETER_TYPE_NAME
constexpr size_t dw::framework::PARAMETER_TYPE_NAME {0U} static constexpr
Definition at line 239 of file ParameterDescriptor.hpp.
PASS_DEPENDENCIES
constexpr size_t dw::framework::PASS_DEPENDENCIES {2U} static constexpr
Definition at line 68 of file PassDescriptor.hpp.
Referenced by hasPassDependencies().
PASS_NAME
constexpr size_t dw::framework::PASS_NAME {0U} static constexpr
Definition at line 62 of file PassDescriptor.hpp.
PASS_PROCESSOR_TYPE
constexpr size_t dw::framework::PASS_PROCESSOR_TYPE {1U} static constexpr
Definition at line 65 of file PassDescriptor.hpp.
PORT_ARRAY_SIZE
constexpr size_t dw::framework::PORT_ARRAY_SIZE {3U} static constexpr
Definition at line 68 of file PortDescriptor.hpp.
PORT_BINDING
constexpr size_t dw::framework::PORT_BINDING {4U} static constexpr
Definition at line 71 of file PortDescriptor.hpp.
PORT_COMMENT
constexpr size_t dw::framework::PORT_COMMENT {5U} static constexpr
Definition at line 74 of file PortDescriptor.hpp.
PORT_NAME
constexpr size_t dw::framework::PORT_NAME {1U} static constexpr
Definition at line 62 of file PortDescriptor.hpp.
PORT_TYPE
constexpr size_t dw::framework::PORT_TYPE {2U} static constexpr
Definition at line 65 of file PortDescriptor.hpp.
Referenced by portDescriptorType().
PORT_TYPE_NAME
constexpr size_t dw::framework::PORT_TYPE_NAME {0U} static constexpr
Definition at line 59 of file PortDescriptor.hpp.
radarSensorEnabled
bool dw::framework::radarSensorEnabled[framework::SELF_CALIBRATION_NODE_MAX_RADARS]
Definition at line 72 of file dwRigNode.hpp.
Referenced by dw::framework::dwRigNode::describeParameters().
radarSensorRigIndices
std::uint32_t dw::framework::radarSensorRigIndices[framework::SELF_CALIBRATION_NODE_MAX_RADARS]
Definition at line 73 of file dwRigNode.hpp.
Referenced by dw::framework::dwRigNode::describeParameters().
rigHandle
dwRigHandle_t dw::framework::rigHandle
Definition at line 56 of file dwRigNode.hpp.
Referenced by dw::framework::dwRigNode::describeParameters(), and dw::framework::dwIcpNode::describeParameters().
rigOutputFileName
char8_t const* dw::framework::rigOutputFileName
Output path where full serialized rig will be written
Definition at line 59 of file dwRigNode.hpp.
Referenced by dw::framework::dwRigNode::describeParameters().
SELF_CALIBRATION_NODE_MAX_CAMERAS
constexpr uint8_t dw::framework::SELF_CALIBRATION_NODE_MAX_CAMERAS = 13 static constexpr
Definition at line 50 of file SelfCalibrationTypes.hpp.
Referenced by dw::framework::dwRigNode::describeInputPorts(), dw::framework::dwSelfCalibrationNode::describeInputPorts(), dw::framework::dwSelfCalibrationRoadcastAggregatorNode::describeInputPorts(), dw::framework::dwSelfCalibrationNode::describeOutputPorts(), dw::framework::dwRigNode::describeParameters(), dw::framework::dwSelfCalibrationNode::describeParameters(), and dw::framework::dwSelfCalibrationRoadcastAggregatorNode::describeParameters().
SELF_CALIBRATION_NODE_MAX_IMUS
constexpr uint8_t dw::framework::SELF_CALIBRATION_NODE_MAX_IMUS = 3 static constexpr
Definition at line 48 of file SelfCalibrationTypes.hpp.
Referenced by dw::framework::dwSelfCalibrationRoadcastAggregatorNode::describeInputPorts(), dw::framework::dwRigNode::describeParameters(), and dw::framework::dwSelfCalibrationRoadcastAggregatorNode::describeParameters().
SELF_CALIBRATION_NODE_MAX_LIDARS
constexpr uint8_t dw::framework::SELF_CALIBRATION_NODE_MAX_LIDARS = 8 static constexpr
Definition at line 52 of file SelfCalibrationTypes.hpp.
Referenced by dw::framework::dwRigNode::describeInputPorts(), dw::framework::dwSelfCalibrationNode::describeInputPorts(), dw::framework::dwSelfCalibrationRoadcastAggregatorNode::describeInputPorts(), dw::framework::dwSelfCalibrationNode::describeOutputPorts(), dw::framework::dwRigNode::describeParameters(), dw::framework::dwSelfCalibrationNode::describeParameters(), and dw::framework::dwSelfCalibrationRoadcastAggregatorNode::describeParameters().
SELF_CALIBRATION_NODE_MAX_RADARS
constexpr uint8_t dw::framework::SELF_CALIBRATION_NODE_MAX_RADARS = 9 static constexpr
Definition at line 51 of file SelfCalibrationTypes.hpp.
Referenced by dw::framework::dwRigNode::describeInputPorts(), dw::framework::dwSelfCalibrationNode::describeInputPorts(), dw::framework::dwSelfCalibrationRoadcastAggregatorNode::describeInputPorts(), dw::framework::dwSelfCalibrationNode::describeOutputPorts(), dw::framework::dwRigNode::describeParameters(), dw::framework::dwSelfCalibrationNode::describeParameters(), and dw::framework::dwSelfCalibrationRoadcastAggregatorNode::describeParameters().
SELF_CALIBRATION_NODE_MAX_ROUTINE_COUNT
constexpr uint8_t dw::framework::SELF_CALIBRATION_NODE_MAX_ROUTINE_COUNT static constexpr
Initial value:
= SELF_CALIBRATION_NODE_MAX_CAMERAS * MAX_EXTRINSIC_PROFILE_COUNT +
                                                                   SELF_CALIBRATION_NODE_MAX_RADARS +
                                                                   SELF_CALIBRATION_NODE_MAX_LIDARS +
                                                                   SELF_CALIBRATION_NODE_MAX_IMUS +
                                                                   SELF_CALIBRATION_NODE_MAX_VEHICLEIO
Definition at line 53 of file SelfCalibrationTypes.hpp.
SELF_CALIBRATION_NODE_MAX_VEHICLEIO
constexpr uint8_t dw::framework::SELF_CALIBRATION_NODE_MAX_VEHICLEIO = 1 static constexpr
Definition at line 49 of file SelfCalibrationTypes.hpp.
SELF_CALIBRATION_NODE_MAX_WHEELS
constexpr uint8_t dw::framework::SELF_CALIBRATION_NODE_MAX_WHEELS = 4 static constexpr
Definition at line 58 of file SelfCalibrationTypes.hpp.
SELF_CALIBRATION_TAG
constexpr char dw::framework::SELF_CALIBRATION_TAG[] = "self-calibration" static constexpr
Definition at line 66 of file SelfCalibrationTypes.hpp.
sensorIndex
uint32_t dw::framework::sensorIndex
Definition at line 55 of file dwIcpNode.hpp.
Referenced by dw::framework::dwIcpNode::describeParameters().
serverPort
uint16_t dw::framework::serverPort
Definition at line 67 of file dwTraceCollectorNode.hpp.
Referenced by dw::framework::dwTraceCollectorNode::describeParameters().
stream
cudaStream_t dw::framework::stream
Definition at line 60 of file dwPyramidNode.hpp.
Referenced by dw::framework::dwPyramidNode::describeParameters(), and dw::framework::dwPyramidPVANode::describeParameters().
SUPPORTS_EEPROM_INTRINSICS_TAG
constexpr char dw::framework::SUPPORTS_EEPROM_INTRINSICS_TAG[] = "supports-eeprom-intrinsics" static constexpr
Definition at line 73 of file SelfCalibrationTypes.hpp.
SUPPORTS_EEPROM_INTRINSICS_TRUE_STRING
constexpr char dw::framework::SUPPORTS_EEPROM_INTRINSICS_TRUE_STRING[] = "true" static constexpr
Definition at line 74 of file SelfCalibrationTypes.hpp.
tracingLevel
uint32_t dw::framework::tracingLevel
Definition at line 71 of file dwTraceCollectorNode.hpp.
Referenced by dw::framework::dwTraceCollectorNode::describeParameters().