Compute Graph Framework SDK Reference: dw::framework::ReadProcessedDataFromChannel< OutputProcessedDataType, InputProcessedDataType > Struct Template Reference
dw::framework::ReadProcessedDataFromChannel< OutputProcessedDataType, InputProcessedDataType > Struct Template Reference abstract
Detailed Description
template<typename OutputProcessedDataType, typename InputProcessedDataType = OutputProcessedDataType>
struct dw::framework::ReadProcessedDataFromChannel< OutputProcessedDataType, InputProcessedDataType >
Definition at line 60 of file dwChannelDrainerTemplate.hpp.
Public Types
using InputDataPort = PortInput< InputProcessedDataType > *
Public Member Functions
virtual dwStatus getNextData (OutputProcessedDataType *outDataFrame, InputDataPort)=0
virtual dwStatus getNextDataTimestamp (dwTime_t &outTimestamp)=0
virtual dwStatus readNextData (dwTime_t inTimeout_us, InputDataPort inputPort)
dwStatus reset ()
Public Attributes
std::shared_ptr< InputProcessedDataType > m_nextDataEvent = nullptr
Member Typedef Documentation
InputDataPort
template<typename OutputProcessedDataType , typename InputProcessedDataType = OutputProcessedDataType> using dw::framework::ReadProcessedDataFromChannel< OutputProcessedDataType, InputProcessedDataType >::InputDataPort = PortInput<InputProcessedDataType>*
Definition at line 62 of file dwChannelDrainerTemplate.hpp.
Member Function Documentation
getNextData()
template<typename OutputProcessedDataType , typename InputProcessedDataType = OutputProcessedDataType> virtual dwStatus dw::framework::ReadProcessedDataFromChannel< OutputProcessedDataType, InputProcessedDataType >::getNextData (OutputProcessedDataType * outDataFrame, InputDataPort) pure virtual
getNextDataTimestamp()
template<typename OutputProcessedDataType , typename InputProcessedDataType = OutputProcessedDataType> virtual dwStatus dw::framework::ReadProcessedDataFromChannel< OutputProcessedDataType, InputProcessedDataType >::getNextDataTimestamp (dwTime_t & outTimestamp) pure virtual
readNextData()
template<typename OutputProcessedDataType , typename InputProcessedDataType = OutputProcessedDataType> virtual dwStatus dw::framework::ReadProcessedDataFromChannel< OutputProcessedDataType, InputProcessedDataType >::readNextData (dwTime_t inTimeout_us, InputDataPort inputPort) inline virtual
Definition at line 65 of file dwChannelDrainerTemplate.hpp.
References dw::framework::PortInput< T >::isBound(), dw::framework::ReadProcessedDataFromChannel< OutputProcessedDataType, InputProcessedDataType >::m_nextDataEvent, dw::framework::PortInput< T >::recv(), and dw::framework::PortInput< T >::wait().
reset()
template<typename OutputProcessedDataType , typename InputProcessedDataType = OutputProcessedDataType> dwStatus dw::framework::ReadProcessedDataFromChannel< OutputProcessedDataType, InputProcessedDataType >::reset () inline
Definition at line 86 of file dwChannelDrainerTemplate.hpp.
References dw::framework::ReadProcessedDataFromChannel< OutputProcessedDataType, InputProcessedDataType >::m_nextDataEvent.
Member Data Documentation
m_nextDataEvent
template<typename OutputProcessedDataType , typename InputProcessedDataType = OutputProcessedDataType> std::shared_ptr<InputProcessedDataType> dw::framework::ReadProcessedDataFromChannel< OutputProcessedDataType, InputProcessedDataType >::m_nextDataEvent = nullptr
Definition at line 63 of file dwChannelDrainerTemplate.hpp.
Referenced by dw::framework::ReadProcessedDataFromChannel< OutputProcessedDataType, InputProcessedDataType >::readNextData(), and dw::framework::ReadProcessedDataFromChannel< OutputProcessedDataType, InputProcessedDataType >::reset().
The documentation for this struct was generated from the following file:
src/dwframework/dwnodes/sensors/dwsensornode/dwChannelDrainerTemplate.hpp