/////////////////////////////////////////////////////////////////////////////////////////
//
// Notice
// ALL NVIDIA DESIGN SPECIFICATIONS AND CODE ("MATERIALS") ARE PROVIDED "AS IS" NVIDIA MAKES
// NO REPRESENTATIONS, WARRANTIES, EXPRESSED, IMPLIED, STATUTORY, OR OTHERWISE WITH RESPECT TO
// THE MATERIALS, AND EXPRESSLY DISCLAIMS ANY IMPLIED WARRANTIES OF NONINFRINGEMENT,
// MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
//
// NVIDIA CORPORATION & AFFILIATES assumes no responsibility for the consequences of use of such
// information or for any infringement of patents or other rights of third parties that may
// result from its use. No license is granted by implication or otherwise under any patent
// or patent rights of NVIDIA CORPORATION & AFFILIATES. No third party distribution is allowed unless
// expressly authorized by NVIDIA. Details are subject to change without notice.
// This code supersedes and replaces all information previously supplied.
// NVIDIA CORPORATION & AFFILIATES products are not authorized for use as critical
// components in life support devices or systems without express written approval of
// NVIDIA CORPORATION & AFFILIATES.
//
// SPDX-FileCopyrightText: Copyright (c) 2018-2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: LicenseRef-NvidiaProprietary
//
// NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
// property and proprietary rights in and to this material, related
// documentation and any modifications thereto. Any use, reproduction,
// disclosure or distribution of this material and related documentation
// without an express license agreement from NVIDIA CORPORATION or
// its affiliates is strictly prohibited.
//
/////////////////////////////////////////////////////////////////////////////////////////

#ifndef DW_FRAMEWORK_TYPES_HPP_
#define DW_FRAMEWORK_TYPES_HPP_

namespace dw
{
namespace framework
{

using dwSerializationType = enum dwSerializationType {
    DW_TYPE_INVALID = 0,
    DW_ACTUATION_SUPERVISOR_STATUS,
    DW_ACTUATED_REPLAY_STATUS,
    DW_ADAS_OBJECT_ARRAY,
    DW_AEB_REQUEST,
    DW_AEB_STATE_INFO,
    DW_AV_STATS,
    DW_AV_CONFIG,
    DW_BEHAVIOR_PLANNER_ACC_INFO,
    DW_BEHAVIOR_PLANNER_LANE_CHANGE_INFO,
    DW_BEHAVIOR_PLANNER_LANE_HANDLE_INFO,
    DW_BEHAVIOR_PLANNER_MERGE_INFO,
    DW_BEHAVIOR_PLANNER_WAIT_ELEMENT_INFO,
    DW_BEHAVIOR_PLANNER_DEBUG_INFO,
    DW_BEHAVIOR_PLANNER_EVALUATION_RESULTS,
    DW_CALIBRATED_STEER_OFFSET,
    DW_CALIBRATED_WHEEL_RADII,
    DW_BLINDNESS_DETECTION_OUTPUT,
    DW_CALIBRATION,
    DW_COMMAND_TO_CONTROL,
    DW_CUBOID_3D,
    DW_CVIP_LIST,
    DW_DISENGAGEMENT_DATA,
    DW_EGOMOTION_RESULT_PAYLOAD,
    DW_EGOMOTION_STATE_HANDLE,
    DW_ENCODED_FRAME,
    DW_EVENT_FLAG,
    DW_EVENT_SURVEY,
    DW_FEATURE_NCC_SCORES,
    DW_FEATURE_ARRAY,
    DW_FEATURE_HISTORY_ARRAY,
    DW_FREESPACE_DETECTION,
    DW_GLOBAL_EGOMOTION_RESULT_PAYLOAD,
    DW_GLOBAL_EGOMOTION_STATE,
    DW_GPS_FRAME,
    DW_HEARTBEAT,
    DW_IMAGE_HANDLE,
    DW_IMU_FRAME,
    DW_INTERSECTION_ARRAY,
    DW_INTERSECTION_DETECTION,
    DW_KPI_STATUS,
    DW_LANE_ARRAY,
    DW_LANE_ASSIGNMENT_ARRAY,
    DW_LANE_CHUNK_ARRAY,
    DW_LANE_DETECTION,
    DW_LANE_GRAPH,
    DW_LANE_GRAPH_LIST,
    DW_LANE_GRAPH_WORLD_MODEL,
    DW_LANE_PLAN_ACTIONS,
    DW_LANE_PLAN_ACTIONS_NEW,
    DW_LANE_SUPPORT_STATUS,
    DW_LANDMARK_DETECTION,
    DW_ROADMARK_DETECTION,
    DW_EGO_LANE_BIASING_INFO,
    DW_ROAD_SEPARATION,
    DW_CAMERA_VISIBILITY,
    DW_LIGHT_SOURCE_PERCEPTION_AUTO_BEAM_STATUS,
    DW_LIGHT_SOURCE_PERCEPTION_DETECTOR_MASK,
    DW_LIGHT_FUNCTIONS_DATA,
    DW_LIDAR_DECODED_PACKET,
    DW_LSS_REQUEST,
    DW_LDW_HMI_REQUEST,
    DW_LOCALIZATION_RESULT,
    DW_LOCALIZATIONNAVMAP_RESULT,
    DW_LOGIN_SURVEY,
    DW_MSG_VERSION,
    DW_OBJECT_ARRAY,
    DW_OBJECT_CAMERA,
    DW_OBJECT_DETECTION,
    DW_OBJECT_FUSED,
    DW_OBJECT_GENERIC,
    DW_OBJECT_HISTORY_ARRAY,
    DW_OBJECT_LIDAR,
    DW_OBJECT_RADAR,
    DW_OBJECT_ARRAY_RADARDNN,
    DW_OBSTACLE,
    DW_OBSTACLE_ARRAY,
    DW_OBSTACLE_LINK_ARRAY,
    DW_OBSTACLE_RDM,
    DW_PARK_DETECTION,
    DW_PATH,
    DW_PATH_DETECTION,
    DW_PERCEPTION_OBJECT,
    DW_PYRAMID_IMAGE,
    DW_POINT_CLOUD,
    DW_RADAR_SCAN,
    DW_RADAR_TRACK_EXTENDED,
    DW_RESIM_CONFIG,
    DW_RESIM_FAILURE,
    DW_RESIM_LOG,
    DW_RESIM_METADATA_LOG,
    DW_RESIM_SEGMENT_LOG,
    DW_SAFETY_FORCE_FIELD_METRIC,
    DW_SAFETY_FORCE_FIELD_STATE,
    DW_MATCHED_ROUTE,
    DW_LARGE_LANE_GRAPH_REWARD_ARRAY,
    DW_LARGE_LANE_GRAPH_LINK_ARRAY,
    DW_SENSOR_NODE_RAW_DATA,
    DW_STRATEGY_HEALTH_STATE,
    DW_SURROUND_MONITOR_RADAR_STATE,
    DW_SURROUND_MONITOR_LANECHANGE_SAFEDECISION,
    DW_RADAR_PERCEPTION_RADAR_STATE,
    DW_SURVEY_REQUEST,
    DW_TEXT,
    DW_TELEMETRY_SESSION,
    DW_TEMPORAL_FUSION_DEBUG_INFO,
    DW_TIME,
    DW_TIME_SERIES,
    DW_TIME_SERIES_ARRAY,
    DW_HEALTH_SIGNAL_ARRAY,
    DW_GRAPH_HEALTH_SIGNAL,
    DW_TRAFFIC_SIGNAL_OBJECT_LIST,
    DW_TRANSFORMATION_PAYLOAD,
    DW_TSLOBJECTS,
    DW_VEHICLE_CALIBRATION,
    DW_VEHICLE_CONTROL_KPI,
    DW_VEHICLE_CONTROL_STATUS,
    DW_VEHICLE_IO_STATE,
    DW_VEHICLE_COMMAND,
    DW_VEHICLE_MISC_COMMAND,
    DW_WAIT_ELEMENT_GROUP,
    DW_WAIT_ELEMENT_GROUPS,
    DW_WAIT_LINE_ARRAY,
    DW_DEPTH_IMAGE,
    DW_CAMERA_PROPERTIES,
    DW_CAMERA_MODEL_TRANSFORM_PARAM,
    DW_SPEEDLIMIT_ARRAY,
    DW_SPEEDLIMIT_LANE_ASSOCIATION_ARRAY,
    DW_SPEEDLIMIT_POSITIONAL_ARRAY,
    DW_TSA_PLANNER_HMI_REQUEST,
    DW_BLIND_SPOT_MONITOR_STATE_INFO,
    DW_TSA_PLANNER_STATE_INFO,
    DW_NEAR_FIELD_ASSIST_STATE_INFO,
    DW_WAIT_ELEMENT_ARRAY,
    DW_PREDICTED_TRAJECTORIES,
    DW_PARKING_SPACE_ARRAY,
    DW_CODEC_PACKET,
    DW_SENSOR_SERVICE_RAW_DATA,
    DW_SENSOR_TS_AND_ID,
    DW_AUTO_EMERGENCY_STEERING_REQUEST,
    DW_RECORDED_PATH,
    FLOAT32,
    DW_LANE_ASSIGNMENT_DEBUG_INFO,
    DW_OBJECT_FUSION_RUN_METADATA,
    DW_TRAFFIC_LIGHTS_ARRAY,
    DW_TEXT_REGION_ARRAY,
    DW_WC_VIEW_LINE_3D_ARRAY,
    DW_TYPES_COUNT
};

} // namespace framework
} // namespace dw

#endif // DW_FRAMEWORK_TYPES_HPP_
