/////////////////////////////////////////////////////////////////////////////////////////
//
// Notice
// ALL NVIDIA DESIGN SPECIFICATIONS AND CODE ("MATERIALS") ARE PROVIDED "AS IS" NVIDIA MAKES
// NO REPRESENTATIONS, WARRANTIES, EXPRESSED, IMPLIED, STATUTORY, OR OTHERWISE WITH RESPECT TO
// THE MATERIALS, AND EXPRESSLY DISCLAIMS ANY IMPLIED WARRANTIES OF NONINFRINGEMENT,
// MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
//
// NVIDIA CORPORATION & AFFILIATES assumes no responsibility for the consequences of use of such
// information or for any infringement of patents or other rights of third parties that may
// result from its use. No license is granted by implication or otherwise under any patent
// or patent rights of NVIDIA CORPORATION & AFFILIATES. No third party distribution is allowed unless
// expressly authorized by NVIDIA. Details are subject to change without notice.
// This code supersedes and replaces all information previously supplied.
// NVIDIA CORPORATION & AFFILIATES products are not authorized for use as critical
// components in life support devices or systems without express written approval of
// NVIDIA CORPORATION & AFFILIATES.
//
// SPDX-FileCopyrightText: Copyright (c) 2016-2021 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: LicenseRef-NvidiaProprietary
//
// NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
// property and proprietary rights in and to this material, related
// documentation and any modifications thereto. Any use, reproduction,
// disclosure or distribution of this material and related documentation
// without an express license agreement from NVIDIA CORPORATION or
// its affiliates is strictly prohibited.
//
// Parser Version: 0.7.5
// SSM Version:    0.9.1
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
* The following file has been generated by SSM's parser.
* Please do not manually modify the files
*/


#pragma once

#include <stdint.h>
#include <map>
#include <iostream>
#include <ssm/SMBaseClass.hpp>
#include <sm2/SSMNames.hpp>

namespace SystemStateManager
{
namespace SM2
{

// Helper methods for SM2 that returns state enums for strings
SM2States SM2_strToEnum(std::string state);

SM2States get_SM2State(SMBaseClass *obj);

// Helper method for SM2 that returns strings for state enums
const char* SM2_enumToStr(SM2States e);

//Overload << operator to help pretty print state enums
std::ostream& operator<<(std::ostream& out, const SM2States state_enum);

// Helper methods for SM1 that returns state enums for strings
SM1States SM1_strToEnum(std::string state);

SM1States get_SM1State(SMBaseClass *obj);

// Helper method for SM1 that returns strings for state enums
const char* SM1_enumToStr(SM1States e);

//Overload << operator to help pretty print state enums
std::ostream& operator<<(std::ostream& out, const SM1States state_enum);

// Helper methods for SSM that returns state enums for strings
SSMStates SSM_strToEnum(std::string state);

SSMStates get_SSMState(SMBaseClass *obj);

// Helper method for SSM that returns strings for state enums
const char* SSM_enumToStr(SSMStates e);

//Overload << operator to help pretty print state enums
std::ostream& operator<<(std::ostream& out, const SSMStates state_enum);

//Helper method to return string for a state machine enum
const char* SmEnumToStr(StateMachines e);

 // Helper method: Returns an enum for state machine string passed as an argument
StateMachines getSmEnum(std::string sm);

}
}
