/////////////////////////////////////////////////////////////////////////////////////////
//
// Notice
// ALL NVIDIA DESIGN SPECIFICATIONS AND CODE ("MATERIALS") ARE PROVIDED "AS IS" NVIDIA MAKES
// NO REPRESENTATIONS, WARRANTIES, EXPRESSED, IMPLIED, STATUTORY, OR OTHERWISE WITH RESPECT TO
// THE MATERIALS, AND EXPRESSLY DISCLAIMS ANY IMPLIED WARRANTIES OF NONINFRINGEMENT,
// MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
//
// NVIDIA CORPORATION & AFFILIATES assumes no responsibility for the consequences of use of such
// information or for any infringement of patents or other rights of third parties that may
// result from its use. No license is granted by implication or otherwise under any patent
// or patent rights of NVIDIA CORPORATION & AFFILIATES. No third party distribution is allowed unless
// expressly authorized by NVIDIA. Details are subject to change without notice.
// This code supersedes and replaces all information previously supplied.
// NVIDIA CORPORATION & AFFILIATES products are not authorized for use as critical
// components in life support devices or systems without express written approval of
// NVIDIA CORPORATION & AFFILIATES.
//
// SPDX-FileCopyrightText: Copyright (c) 2016-2021 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: LicenseRef-NvidiaProprietary
//
// NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
// property and proprietary rights in and to this material, related
// documentation and any modifications thereto. Any use, reproduction,
// disclosure or distribution of this material and related documentation
// without an express license agreement from NVIDIA CORPORATION or
// its affiliates is strictly prohibited.
//
// Parser Version: 0.7.5
// SSM Version:    0.9.1
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
* The following file has been generated by SSM's parser.
* Please do not manually modify the files
*/

#include <sm3/SM1.hpp>

namespace SystemStateManager
{

namespace SM3
{

bool SM1::registerLockedCommand(SystemStateManager::SM3::LockSteppedCommands command, SSMFunctionHandler ptr)
{
    return registerLockSteppedFunction((int)command, ptr);
}

void SM1::executeStateMachine()
{
    runnableHist.startTimer();
    if (mySMPtr->getCurrentState() == ENTER_STATE)
    {
        bool isStateChangeValid = false;
        if (executeResetHandlerFlag)
        {
            if (resetFunctionHandlerPtr)
            {
                resetFunctionHandlerPtr(this);
            }
            executeResetHandlerFlag = false;
        }
        ENTER();
        isStateChangeValid = mySMPtr->changeStateByString(mySMPtr->getStartState());
        if (!isStateChangeValid)
        {
            runnableHist.endTimer(SSM_LATENCY_THRESHOLD);
            SSM_ERROR("Invalid state transition requested: " + mySMPtr->getCurrentState() + " -> " + mySMPtr->getStartState());
            return;
        }
        broadCastStateChange(name, mySMPtr->getStartState());
        activateChildren(mySMPtr);
    }

    if (mySMPtr->getCurrentState() == EXIT_STATE)
    {
        EXIT();
    }

    if (mySMPtr->getCurrentState() == PRE_INIT_STATE)
    {
        PRE_INIT();
    }

    if (mySMPtr->getCurrentState() == INIT_STATE)
    {
        INIT();
    }

    if (mySMPtr->getCurrentState() == POST_INIT_STATE)
    {
        POST_INIT();
    }

    if (mySMPtr->getCurrentState() == PRE_READY_STATE)
    {
        PRE_READY();
    }

    if (mySMPtr->getCurrentState() == READY_STATE)
    {
        READY();
    }

    if (mySMPtr->getCurrentState() == SSM_SM1_A1_str)
    {
        A1();
    }
    else if (mySMPtr->getCurrentState() == SSM_SM1_B1_str)
    {
        B1();
    }
    else if (mySMPtr->getCurrentState() == SSM_SM1_C1_str)
    {
        C1();
    }
    else if (mySMPtr->getCurrentState() == SSM_SM1_D1_str)
    {
        D1();
    }
    std::string currState = mySMPtr->getCurrentState();
    bool printLatency     = true;
    if (currState == "PRE_INIT_STATE" ||
        currState == "INIT_STATE" ||
        currState == "POST_INIT_STATE" ||
        currState == "PRE_READY_STATE" ||
        currState == "READY_STATE")
    {
        printLatency = false;
    }
    runnableHist.endTimer(SSM_LATENCY_THRESHOLD, printLatency);
}

void SM1::runInitPhase(int micros)
{
    initHierarchy();
    while (!isStartStateMachineMsgReceived())
    {
        sleep(1);
    }
    initClientComm();
    while (!isSMReadyForScheduler())
    {
        runStateMachine();
        usleep(micros);
    }
}

bool SM1::setupTreeHierarchy(StateMachineVector& smv, StateMachinePtr& hPtr)
{
    return setupHierarchy(smv, hPtr);
}

void SM1::printClientHistogram()
{
    runnableHist.printHistogram("executeStateMachine");
}

void SM1::initLockSteppedCommands()
{
    for (int index = 0; index < (int)SystemStateManager::SM3::LockSteppedCommands::MAX_CMD; index++)
    {
        addLockSteppedCommand(index);
    }
}

void SM1::documentStateChangeExternally()
{
    documentStateChange((int)stateMachineId, (int)getState());
}


bool SM1::changeState(SM1States e)
{
    return changeStateByString(SM1_enumToStr(e));
}

int SM1::sendDataByID(StateMachines e, void *data, int datalen, std::string dataStructID)
{
    return sendData(SmEnumToStr(e), data, datalen, dataStructID);
}

SM1States SM1::getState()
{
    return SM1_strToEnum(mySMPtr->getCurrentState());
}


bool SM1::getUserSpecificData(UserDataPkt &pkt)
{
    UserDataPktInternal internalPkt;

    bool status = getUserSpecificDataInternal(internalPkt);
    if(status != false)
    {
        if(internalPkt.dataType.size() > MAX_DATA_TYPE_SIZE)
        {
            SSM_ERROR("Data type size is greater than "+ std::to_string(MAX_DATA_TYPE_SIZE) + " characters");
            return false;
        }
        strcpy(pkt.dataType,internalPkt.dataType.c_str());
        pkt.timestamp=internalPkt.timestamp;
        pkt.targetStateMachine=getSmEnum(internalPkt.targetStateMachine);
        pkt.sourceStateMachine=getSmEnum(internalPkt.sourceStateMachine);
        pkt.timestamp=internalPkt.timestamp;
        pkt.size=internalPkt.size;
        memcpy(pkt.data,internalPkt.data,sizeof(internalPkt.data));
    }
    return status;
}

}
}
