////////////////////////////////////////////////////////////////////////////////
// This code contains NVIDIA Confidential Information and is disclosed
// under the Mutual Non-Disclosure Agreement.
//
// Notice
// ALL NVIDIA DESIGN SPECIFICATIONS AND CODE ("MATERIALS") ARE PROVIDED "AS IS"
// NVIDIA MAKES NO REPRESENTATIONS, WARRANTIES, EXPRESSED, IMPLIED, STATUTORY,
// OR OTHERWISE WITH RESPECT TO THE MATERIALS, AND EXPRESSLY DISCLAIMS ANY
// IMPLIED WARRANTIES OF NONINFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// NVIDIA Corporation assumes no responsibility for the consequences of use of
// such information or for any infringement of patents or other rights of third
// parties that may result from its use. No license is granted by implication or
// otherwise under any patent or patent rights of NVIDIA Corporation. No third
// party distribution is allowed unless expressly authorized by NVIDIA.  Details
// are subject to change without notice. This code supersedes and replaces all
// information previously supplied. NVIDIA Corporation products are not
// authorized for use as critical components in life support devices or systems
// without express written approval of NVIDIA Corporation.
//
// Copyright (c) 2024 NVIDIA Corporation. All rights reserved.
//
// NVIDIA Corporation and its licensors retain all intellectual property and
// proprietary rights in and to this software and related documentation and any
// modifications thereto. Any use, reproduction, disclosure or distribution of
// this software and related documentation without an express license agreement
// from NVIDIA Corporation is strictly prohibited.
//
////////////////////////////////////////////////////////////////////////////////
#ifndef DW_SENSORS_CODECS_SENSORINFO_H_
#define DW_SENSORS_CODECS_SENSORINFO_H_
// Generated by dwProto from sensor_info.proto DO NOT EDIT BY HAND!
// See //3rdparty/shared/dwproto/README.md for more information

#include <stdbool.h>
#include <stdint.h>

#include <dw/core/base/BasicTypes.h>

#ifdef __cplusplus
extern "C" {
#endif

/// Holds the sensor firmware version information
typedef struct dwSensorFirmwareInformation
{
    /// Separate the fwVersion string into three pieces.
    /// Numbers are normalized based on SAL parser.
    /// Firmware version major number.
    uint64_t versionMajor;

    /// Firmware version minor number.
    uint64_t versionMinor;

    /// Firmware version patch number.
    uint64_t versionPatch;

    /// Firmware version string.
    char8_t versionString[64];
} dwSensorFirmwareInformation;

/// Holds the sensor information
typedef struct dwSensorInformation
{
    /// Holds the sensor firmware version information
    dwSensorFirmwareInformation firmware;

    /// Holds the sensor serial number information
    char8_t serialNumber[32];
} dwSensorInformation;

#ifdef __cplusplus
}
#endif

#endif // DW_SENSORS_CODECS_SENSORINFO_H_
